<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 13 Cuando los supuestos no se cumplen | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R</title>
  <meta name="description" content="Capítulo 13 Cuando los supuestos no se cumplen | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 13 Cuando los supuestos no se cumplen | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/imagenes/cover.jpg" />
  
  <meta name="github-repo" content="jcrodriguez1989/EstadisticaParaCienciasSocialesConR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 13 Cuando los supuestos no se cumplen | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  
  
  <meta name="twitter:image" content="/imagenes/cover.jpg" />

<meta name="author" content="Eduardo Bologna" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prueba-de-hipótesis-las-aplicaciones.html"/>
<link rel="next" href="tamaño-del-efecto.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística para Ciencias Sociales con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Colaboradores</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#comit%C3%A9-editorial"><i class="fa fa-check"></i>Comité Editorial</a></li>
<li class="chapter" data-level="" data-path=""><a href="#edici%C3%B3n-en-bookdown"><i class="fa fa-check"></i>Edición en bookdown</a></li>
<li class="chapter" data-level="" data-path=""><a href="#revisi%C3%B3n-de-lenguaje-incluyente"><i class="fa fa-check"></i>Revisión de lenguaje incluyente</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#presentaci%C3%B3n"><i class="fa fa-check"></i>Presentación</a>
<ul>
<li class="chapter" data-level="" data-path="presentación.html"><a href="presentación.html"><i class="fa fa-check"></i>Recorridos posibles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#introducci%C3%B3n"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html"><i class="fa fa-check"></i>Antes de empezar</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#materiales"><i class="fa fa-check"></i>Materiales</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-permanente-de-hogares"><i class="fa fa-check"></i>Encuesta Permanente de Hogares</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-nacional-de-factores-de-riesgo"><i class="fa fa-check"></i>Encuesta Nacional de Factores de Riesgo</a></li>
<li class="chapter" data-level="" data-path=""><a href="#latinobar%C3%B3metro"><i class="fa fa-check"></i>Latinobarómetro</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-nacional-sobre-prevalencias-de-consumo-de-sustancias-psicoactivas"><i class="fa fa-check"></i>Encuesta Nacional sobre Prevalencias de Consumo de Sustancias Psicoactivas</a></li>
<li class="chapter" data-level="" data-path=""><a href="#aplicaci%C3%B3n-de-la-escala-de-bayley"><i class="fa fa-check"></i>Aplicación de la escala de Bayley</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#tercera-edad"><i class="fa fa-check"></i>Tercera edad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#herramientas"><i class="fa fa-check"></i>Herramientas</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#la-elecci%C3%B3n-de-r"><i class="fa fa-check"></i>La elección de R</a></li>
<li class="chapter" data-level="" data-path=""><a href="#instalaci%C3%B3n-de-r-y-rstudio"><i class="fa fa-check"></i>Instalación de R y RStudio</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#los-componentes-de-rstudio"><i class="fa fa-check"></i>Los componentes de RStudio</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#operaciones-en-el-script"><i class="fa fa-check"></i>Operaciones en el script</a></li>
<li class="chapter" data-level="" data-path=""><a href="#instalaci%C3%B3n-de-paquetes"><i class="fa fa-check"></i>Instalación de paquetes</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Estadística Descriptiva</b></span></li>
<li class="chapter" data-level="1" data-path="14-capitulo13.html"><a href="#los-datos-estad%C3%ADsticos"><i class="fa fa-check"></i><b>1</b> Los datos estadísticos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="14-capitulo13.html"><a href="#la-selecci%C3%B3n-de-la-informaci%C3%B3n-pertinente"><i class="fa fa-check"></i><b>1.1</b> La selección de la información pertinente</a></li>
<li class="chapter" data-level="1.2" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html"><i class="fa fa-check"></i><b>1.2</b> Las entidades</a></li>
<li class="chapter" data-level="1.3" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#las-variables"><i class="fa fa-check"></i><b>1.3</b> Las variables</a></li>
<li class="chapter" data-level="1.4" data-path="14-capitulo13.html"><a href="#las-categor%C3%ADas"><i class="fa fa-check"></i><b>1.4</b> Las categorías</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="14-capitulo13.html"><a href="#requisitos-de-las-categor%C3%ADas"><i class="fa fa-check"></i><b>1.4.1</b> Requisitos de las categorías</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="14-capitulo13.html"><a href="#los-s%C3%ADmbolos-num%C3%A9ricos"><i class="fa fa-check"></i><b>1.5</b> Los símbolos numéricos</a></li>
<li class="chapter" data-level="1.6" data-path="14-capitulo13.html"><a href="#la-medici%C3%B3n"><i class="fa fa-check"></i><b>1.6</b> La medición</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="14-capitulo13.html"><a href="#niveles-de-medici%C3%B3n"><i class="fa fa-check"></i><b>1.6.1</b> Niveles de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="14-capitulo13.html"><a href="#resumen-de-los-niveles-de-medici%C3%B3n"><i class="fa fa-check"></i><b>1.7</b> Resumen de los niveles de medición</a></li>
<li class="chapter" data-level="1.8" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#hacerlo-en-r"><i class="fa fa-check"></i><b>1.8</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#lectura-de-la-base"><i class="fa fa-check"></i><b>1.8.1</b> Lectura de la base</a></li>
<li class="chapter" data-level="1.8.2" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#las-variables-1"><i class="fa fa-check"></i><b>1.8.2</b> Las variables</a></li>
<li class="chapter" data-level="1.8.3" data-path="14-capitulo13.html"><a href="#los-niveles-de-medici%C3%B3n-en-r"><i class="fa fa-check"></i><b>1.8.3</b> Los niveles de medición en R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html"><i class="fa fa-check"></i><b>2</b> Distribuciones de frecuencia</a>
<ul>
<li class="chapter" data-level="2.1" data-path="14-capitulo13.html"><a href="#tablas-de-distribuci%C3%B3n-de-frecuencia"><i class="fa fa-check"></i><b>2.1</b> Tablas de distribución de frecuencia</a></li>
<li class="chapter" data-level="2.2" data-path="14-capitulo13.html"><a href="#recategorizaci%C3%B3n"><i class="fa fa-check"></i><b>2.2</b> Recategorización</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="14-capitulo13.html"><a href="#variable-discreta-con-muchas-categor%C3%ADas"><i class="fa fa-check"></i><b>2.2.1</b> Variable discreta con muchas categorías</a></li>
<li class="chapter" data-level="2.2.2" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#variable-continua"><i class="fa fa-check"></i><b>2.2.2</b> Variable continua</a></li>
<li class="chapter" data-level="2.2.3" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#formas-de-recategorizar"><i class="fa fa-check"></i><b>2.2.3</b> Formas de recategorizar</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="14-capitulo13.html"><a href="#la-presentaci%C3%B3n-gr%C3%A1fica-de-los-resultados"><i class="fa fa-check"></i><b>2.3</b> La presentación gráfica de los resultados</a></li>
<li class="chapter" data-level="2.4" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#hacerlo-en-r-1"><i class="fa fa-check"></i><b>2.4</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#tablas-univariadas"><i class="fa fa-check"></i><b>2.4.1</b> Tablas univariadas</a></li>
<li class="chapter" data-level="2.4.2" data-path="14-capitulo13.html"><a href="#recategorizaci%C3%B3n-1"><i class="fa fa-check"></i><b>2.4.2</b> Recategorización</a></li>
<li class="chapter" data-level="2.4.3" data-path="14-capitulo13.html"><a href="#representaciones-gr%C3%A1ficas"><i class="fa fa-check"></i><b>2.4.3</b> Representaciones gráficas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="14-capitulo13.html"><a href="#la-expresi%C3%B3n-resumida-de-la-informaci%C3%B3n"><i class="fa fa-check"></i><b>3</b> La expresión resumida de la información</a>
<ul>
<li class="chapter" data-level="3.1" data-path="14-capitulo13.html"><a href="#medidas-de-posici%C3%B3n"><i class="fa fa-check"></i><b>3.1</b> Medidas de posición</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html"><i class="fa fa-check"></i><b>3.1.1</b> Variables nominales: proporciones</a></li>
<li class="chapter" data-level="3.1.2" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-tasas"><i class="fa fa-check"></i><b>3.1.2</b> Variables nominales: tasas</a></li>
<li class="chapter" data-level="3.1.3" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-razones"><i class="fa fa-check"></i><b>3.1.3</b> Variables nominales: razones</a></li>
<li class="chapter" data-level="3.1.4" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-el-modo"><i class="fa fa-check"></i><b>3.1.4</b> Variables nominales: el modo</a></li>
<li class="chapter" data-level="3.1.5" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-ordinales-cuantiles"><i class="fa fa-check"></i><b>3.1.5</b> Variables ordinales: cuantiles</a></li>
<li class="chapter" data-level="3.1.6" data-path="14-capitulo13.html"><a href="#variables-m%C3%A9tricas-la-media-o-promedio"><i class="fa fa-check"></i><b>3.1.6</b> Variables métricas: la media o promedio</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="14-capitulo13.html"><a href="#la-forma-de-la-distribuci%C3%B3n"><i class="fa fa-check"></i><b>3.2</b> La forma de la distribución</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="14-capitulo13.html"><a href="#asimetr%C3%ADa"><i class="fa fa-check"></i><b>3.2.1</b> Asimetría</a></li>
<li class="chapter" data-level="3.2.2" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#curtosis"><i class="fa fa-check"></i><b>3.2.2</b> Curtosis</a></li>
<li class="chapter" data-level="3.2.3" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#box-plots"><i class="fa fa-check"></i><b>3.2.3</b> Box-plots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="14-capitulo13.html"><a href="#medidas-de-dispersi%C3%B3n"><i class="fa fa-check"></i><b>3.3</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#recorrido"><i class="fa fa-check"></i><b>3.3.1</b> Recorrido</a></li>
<li class="chapter" data-level="3.3.2" data-path="14-capitulo13.html"><a href="#amplitud-intercuart%C3%ADlica"><i class="fa fa-check"></i><b>3.3.2</b> Amplitud intercuartílica</a></li>
<li class="chapter" data-level="3.3.3" data-path="14-capitulo13.html"><a href="#medidas-de-dispersi%C3%B3n-basadas-en-la-media"><i class="fa fa-check"></i><b>3.3.3</b> Medidas de dispersión basadas en la media</a></li>
<li class="chapter" data-level="3.3.4" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#varianza"><i class="fa fa-check"></i><b>3.3.4</b> Varianza</a></li>
<li class="chapter" data-level="3.3.5" data-path="14-capitulo13.html"><a href="#desviaci%C3%B3n-est%C3%A1ndar"><i class="fa fa-check"></i><b>3.3.5</b> Desviación estándar</a></li>
<li class="chapter" data-level="3.3.6" data-path="14-capitulo13.html"><a href="#coeficiente-de-variaci%C3%B3n"><i class="fa fa-check"></i><b>3.3.6</b> Coeficiente de variación</a></li>
<li class="chapter" data-level="3.3.7" data-path="14-capitulo13.html"><a href="#box-plots-y-dispersi%C3%B3n"><i class="fa fa-check"></i><b>3.3.7</b> Box-plots y dispersión</a></li>
<li class="chapter" data-level="3.3.8" data-path="14-capitulo13.html"><a href="#medida-de-la-dispersi%C3%B3n-cuando-no-hay-distancias"><i class="fa fa-check"></i><b>3.3.8</b> Medida de la dispersión cuando no hay distancias</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="14-capitulo13.html"><a href="#el-individuo-en-relaci%C3%B3n-a-su-grupo"><i class="fa fa-check"></i><b>3.4</b> El individuo en relación a su grupo</a></li>
<li class="chapter" data-level="3.5" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#resumen-de-medidas-descriptivas"><i class="fa fa-check"></i><b>3.5</b> Resumen de medidas descriptivas</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="14-capitulo13.html"><a href="#medidas-de-posici%C3%B3n-1"><i class="fa fa-check"></i><b>3.5.1</b> Medidas de posición</a></li>
<li class="chapter" data-level="3.5.2" data-path="14-capitulo13.html"><a href="#medidas-de-dispersi%C3%B3n-1"><i class="fa fa-check"></i><b>3.5.2</b> Medidas de dispersión</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#hacerlo-en-r-2"><i class="fa fa-check"></i><b>3.6</b> Hacerlo en R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="14-capitulo13.html"><a href="#relaci%C3%B3n-entre-variables-los-fundamentos"><i class="fa fa-check"></i><b>4</b> Relación entre variables: los fundamentos</a>
<ul>
<li class="chapter" data-level="4.1" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html"><i class="fa fa-check"></i><b>4.1</b> Tablas de contingencia</a></li>
<li class="chapter" data-level="4.2" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#frecuencias-relativas"><i class="fa fa-check"></i><b>4.2</b> Frecuencias relativas</a></li>
<li class="chapter" data-level="4.3" data-path="14-capitulo13.html"><a href="#una-clasificaci%C3%B3n-en-referencia-al-tiempo"><i class="fa fa-check"></i><b>4.3</b> Una clasificación en referencia al tiempo</a></li>
<li class="chapter" data-level="4.4" data-path="14-capitulo13.html"><a href="#la-direcci%C3%B3n-de-la-relaci%C3%B3n"><i class="fa fa-check"></i><b>4.4</b> La dirección de la relación</a></li>
<li class="chapter" data-level="4.5" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#concepto-de-riesgo-relativo"><i class="fa fa-check"></i><b>4.5</b> Concepto de riesgo relativo</a></li>
<li class="chapter" data-level="4.6" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#la-intensidad"><i class="fa fa-check"></i><b>4.6</b> La intensidad</a></li>
<li class="chapter" data-level="4.7" data-path="14-capitulo13.html"><a href="#el-concepto-de-independencia-estad%C3%ADstica"><i class="fa fa-check"></i><b>4.7</b> El concepto de independencia estadística</a></li>
<li class="chapter" data-level="4.8" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#hacerlo-en-r-3"><i class="fa fa-check"></i><b>4.8</b> Hacerlo en R</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="14-capitulo13.html"><a href="#relaci%C3%B3n-entre-variables-el-an%C3%A1lisis"><i class="fa fa-check"></i><b>5</b> Relación entre variables: el análisis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="14-capitulo13.html"><a href="#relaciones-entre-variables-vs.-comparaci%C3%B3n-de-grupos"><i class="fa fa-check"></i><b>5.1</b> Relaciones entre variables vs. comparación de grupos</a></li>
<li class="chapter" data-level="5.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html"><i class="fa fa-check"></i><b>5.2</b> Variables nominales</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="14-capitulo13.html"><a href="#coeficientes-de-asociaci%C3%B3n-para-variables-nominales"><i class="fa fa-check"></i><b>5.2.1</b> Coeficientes de asociación para variables nominales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#variables-de-nivel-ordinal"><i class="fa fa-check"></i><b>5.3</b> Variables de nivel ordinal</a></li>
<li class="chapter" data-level="5.4" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#nivel-intervalar-o-proporcional"><i class="fa fa-check"></i><b>5.4</b> Nivel intervalar o proporcional</a></li>
<li class="chapter" data-level="5.5" data-path="14-capitulo13.html"><a href="#dicotom%C3%ADas-reales-y-artificiales"><i class="fa fa-check"></i><b>5.5</b> Dicotomías reales y artificiales</a></li>
<li class="chapter" data-level="5.6" data-path="14-capitulo13.html"><a href="#niveles-de-medici%C3%B3n-combinados"><i class="fa fa-check"></i><b>5.6</b> Niveles de medición combinados</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="14-capitulo13.html"><a href="#una-variable-dicot%C3%B3mica-real-y-una-proporcional"><i class="fa fa-check"></i><b>5.6.1</b> Una variable dicotómica real y una proporcional</a></li>
<li class="chapter" data-level="5.6.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#una-variable-continua-dicotomizada-y-una-proporcional"><i class="fa fa-check"></i><b>5.6.2</b> Una variable continua dicotomizada y una proporcional</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="14-capitulo13.html"><a href="#resumen-de-coeficientes-de-asociaci%C3%B3n"><i class="fa fa-check"></i><b>5.7</b> Resumen de coeficientes de asociación</a></li>
<li class="chapter" data-level="5.8" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#matriz-de-correlaciones"><i class="fa fa-check"></i><b>5.8</b> Matriz de correlaciones</a></li>
<li class="chapter" data-level="5.9" data-path="14-capitulo13.html"><a href="#la-forma-de-la-relaci%C3%B3n"><i class="fa fa-check"></i><b>5.9</b> La forma de la relación</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#ordenada-al-origen"><i class="fa fa-check"></i><b>5.9.1</b> Ordenada al origen</a></li>
<li class="chapter" data-level="5.9.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#pendiente"><i class="fa fa-check"></i><b>5.9.2</b> Pendiente</a></li>
<li class="chapter" data-level="5.9.3" data-path="14-capitulo13.html"><a href="#obtenci%C3%B3n-de-la-recta-de-regresi%C3%B3n"><i class="fa fa-check"></i><b>5.9.3</b> Obtención de la recta de regresión</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="14-capitulo13.html"><a href="#la-visualizaci%C3%B3n-de-los-datos"><i class="fa fa-check"></i><b>5.10</b> La visualización de los datos</a></li>
<li class="chapter" data-level="5.11" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#hacerlo-en-r-4"><i class="fa fa-check"></i><b>5.11</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#distancia-chi2"><i class="fa fa-check"></i><b>5.11.1</b> Distancia <span class="math inline">\(\chi^{2}\)</span></a></li>
<li class="chapter" data-level="5.11.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#coeficientes"><i class="fa fa-check"></i><b>5.11.2</b> Coeficientes</a></li>
<li class="chapter" data-level="5.11.3" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#modelo-lineal"><i class="fa fa-check"></i><b>5.11.3</b> Modelo lineal</a></li>
<li class="chapter" data-level="5.11.4" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#cuarteto-de-anscombe"><i class="fa fa-check"></i><b>5.11.4</b> Cuarteto de Anscombe</a></li>
<li class="chapter" data-level="5.11.5" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#datasaurus"><i class="fa fa-check"></i><b>5.11.5</b> Datasaurus</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II De la descripción a la inferencia</b></span></li>
<li class="chapter" data-level="6" data-path="14-capitulo13.html"><a href="#obtenci%C3%B3n-de-la-muestra"><i class="fa fa-check"></i><b>6</b> Obtención de la muestra</a>
<ul>
<li class="chapter" data-level="6.1" data-path="14-capitulo13.html"><a href="#poblaci%C3%B3n"><i class="fa fa-check"></i><b>6.1</b> Población</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html"><i class="fa fa-check"></i><b>6.1.1</b> Muestra</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="14-capitulo13.html"><a href="#muestreos-probabil%C3%ADsticos"><i class="fa fa-check"></i><b>6.2</b> Muestreos probabilísticos</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-irrestricto-aleatorio-o-aleatorio-simple"><i class="fa fa-check"></i><b>6.2.1</b> Muestreo irrestricto aleatorio o aleatorio simple</a></li>
<li class="chapter" data-level="6.2.2" data-path="14-capitulo13.html"><a href="#muestreo-sistem%C3%A1tico"><i class="fa fa-check"></i><b>6.2.2</b> Muestreo sistemático</a></li>
<li class="chapter" data-level="6.2.3" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-estratificado"><i class="fa fa-check"></i><b>6.2.3</b> Muestreo estratificado</a></li>
<li class="chapter" data-level="6.2.4" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-por-conglomerados"><i class="fa fa-check"></i><b>6.2.4</b> Muestreo por conglomerados</a></li>
<li class="chapter" data-level="6.2.5" data-path="14-capitulo13.html"><a href="#m%C3%A9todo-de-kish"><i class="fa fa-check"></i><b>6.2.5</b> Método de Kish</a></li>
<li class="chapter" data-level="6.2.6" data-path="14-capitulo13.html"><a href="#uso-combinado-de-t%C3%A9cnicas-de-muestreo"><i class="fa fa-check"></i><b>6.2.6</b> Uso combinado de técnicas de muestreo</a></li>
<li class="chapter" data-level="6.2.7" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-de-panel"><i class="fa fa-check"></i><b>6.2.7</b> Muestreo de panel</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="14-capitulo13.html"><a href="#muestreos-no-probabil%C3%ADsticos"><i class="fa fa-check"></i><b>6.3</b> Muestreos no probabilísticos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-por-cuotas"><i class="fa fa-check"></i><b>6.3.1</b> Muestreo por cuotas</a></li>
<li class="chapter" data-level="6.3.2" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-de-juicio-o-intencional"><i class="fa fa-check"></i><b>6.3.2</b> Muestreo de juicio o intencional</a></li>
<li class="chapter" data-level="6.3.3" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-autoelegido"><i class="fa fa-check"></i><b>6.3.3</b> Muestreo autoelegido</a></li>
<li class="chapter" data-level="6.3.4" data-path="14-capitulo13.html"><a href="#muestreo-accidental-o-seg%C3%BAn-disponibilidad"><i class="fa fa-check"></i><b>6.3.4</b> Muestreo accidental o según disponibilidad</a></li>
<li class="chapter" data-level="6.3.5" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-bola-de-nieve"><i class="fa fa-check"></i><b>6.3.5</b> Muestreo bola de nieve</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#hacerlo-en-r-5"><i class="fa fa-check"></i><b>6.4</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#aleatorio-simple"><i class="fa fa-check"></i><b>6.4.1</b> Aleatorio simple</a></li>
<li class="chapter" data-level="6.4.2" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#estratificado"><i class="fa fa-check"></i><b>6.4.2</b> Estratificado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html"><i class="fa fa-check"></i><b>7</b> Probabilidad: los fundamentos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#formas-para-asignar-probabilidades"><i class="fa fa-check"></i><b>7.1</b> Formas para asignar probabilidades</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="14-capitulo13.html"><a href="#asignaci%C3%B3n-a-priori"><i class="fa fa-check"></i><b>7.1.1</b> Asignación a priori</a></li>
<li class="chapter" data-level="7.1.2" data-path="14-capitulo13.html"><a href="#asignaci%C3%B3n-a-posteriori"><i class="fa fa-check"></i><b>7.1.2</b> Asignación a posteriori</a></li>
<li class="chapter" data-level="7.1.3" data-path="14-capitulo13.html"><a href="#la-relaci%C3%B3n-entre-asignaci%C3%B3n-a-priori-y-a-posteriori"><i class="fa fa-check"></i><b>7.1.3</b> La relación entre asignación a priori y a posteriori</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#operando-con-probabilidades"><i class="fa fa-check"></i><b>7.2</b> Operando con probabilidades</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#con-probabilidades-frecuenciales"><i class="fa fa-check"></i><b>7.2.1</b> Con probabilidades frecuenciales</a></li>
<li class="chapter" data-level="7.2.2" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#con-probabilidades-a-priori"><i class="fa fa-check"></i><b>7.2.2</b> Con probabilidades a priori</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#el-teorema-de-bayes"><i class="fa fa-check"></i><b>7.3</b> El teorema de Bayes</a></li>
<li class="chapter" data-level="7.4" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#variables-aleatorias"><i class="fa fa-check"></i><b>7.4</b> Variables aleatorias</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html"><i class="fa fa-check"></i><b>8</b> Probabilidad: los modelos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="14-capitulo13.html"><a href="#concepto-de-modelizaci%C3%B3n"><i class="fa fa-check"></i><b>8.1</b> Concepto de modelización</a></li>
<li class="chapter" data-level="8.2" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-binomial"><i class="fa fa-check"></i><b>8.2</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#esperanza-y-varianza"><i class="fa fa-check"></i><b>8.2.1</b> Esperanza y varianza</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-normal"><i class="fa fa-check"></i><b>8.3</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#cuantiles"><i class="fa fa-check"></i><b>8.3.1</b> Cuantiles</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#la-idea-de-grados-de-libertad"><i class="fa fa-check"></i><b>8.4</b> La idea de grados de libertad</a></li>
<li class="chapter" data-level="8.5" data-path="14-capitulo13.html"><a href="#la-distribuci%C3%B3n-ji-cuadrado-chi2"><i class="fa fa-check"></i><b>8.5</b> La distribución ji cuadrado (<span class="math inline">\(\chi^{2}\)</span>)</a></li>
<li class="chapter" data-level="8.6" data-path="14-capitulo13.html"><a href="#la-distribuci%C3%B3n-t-de-student"><i class="fa fa-check"></i><b>8.6</b> La distribución t de Student</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="14-capitulo13.html"><a href="#la-distribuci%C3%B3n-f"><i class="fa fa-check"></i><b>8.6.1</b> La distribución F</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#hacerlo-en-r-6"><i class="fa fa-check"></i><b>8.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#probabilidades-exactas"><i class="fa fa-check"></i><b>8.7.1</b> Probabilidades exactas</a></li>
<li class="chapter" data-level="8.7.2" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#probabilidades-acumuladas"><i class="fa fa-check"></i><b>8.7.2</b> Probabilidades acumuladas</a></li>
<li class="chapter" data-level="8.7.3" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#cuantiles-1"><i class="fa fa-check"></i><b>8.7.3</b> Cuantiles</a></li>
<li class="chapter" data-level="8.7.4" data-path="14-capitulo13.html"><a href="#%C3%A1reas-centrales"><i class="fa fa-check"></i><b>8.7.4</b> Áreas centrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html"><i class="fa fa-check"></i><b>9</b> Distribuciones en el muestreo</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#variabilidad-muestral"><i class="fa fa-check"></i><b>9.1</b> Variabilidad muestral</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#dos-aspectos-importantes-para-recordar-cuando-se-usan-muestras"><i class="fa fa-check"></i><b>9.1.1</b> Dos aspectos importantes para recordar cuando se usan muestras:</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="14-capitulo13.html"><a href="#caracter%C3%ADsticas-de-los-estimadores"><i class="fa fa-check"></i><b>9.2</b> Características de los estimadores</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#insesgabilidad"><i class="fa fa-check"></i><b>9.2.1</b> Insesgabilidad</a></li>
<li class="chapter" data-level="9.2.2" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#consistencia"><i class="fa fa-check"></i><b>9.2.2</b> Consistencia</a></li>
<li class="chapter" data-level="9.2.3" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#eficiencia"><i class="fa fa-check"></i><b>9.2.3</b> Eficiencia</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#distribuciones-de-probabilidad-de-los-estimadores"><i class="fa fa-check"></i><b>9.3</b> Distribuciones de probabilidad de los estimadores</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="14-capitulo13.html"><a href="#primera-aproximaci%C3%B3n"><i class="fa fa-check"></i><b>9.3.1</b> Primera aproximación</a></li>
<li class="chapter" data-level="9.3.2" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-de-la-media-muestral"><i class="fa fa-check"></i><b>9.3.2</b> Distribución de la media muestral</a></li>
<li class="chapter" data-level="9.3.3" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-de-la-proporci%C3%B3n-muestral"><i class="fa fa-check"></i><b>9.3.3</b> Distribución de la proporción muestral</a></li>
<li class="chapter" data-level="9.3.4" data-path="14-capitulo13.html"><a href="#muestras-peque%C3%B1as"><i class="fa fa-check"></i><b>9.3.4</b> Muestras pequeñas</a></li>
<li class="chapter" data-level="9.3.5" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-de-la-varianza"><i class="fa fa-check"></i><b>9.3.5</b> Distribución de la varianza</a></li>
<li class="chapter" data-level="9.3.6" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#muestreo-desde-dos-poblaciones"><i class="fa fa-check"></i><b>9.3.6</b> Muestreo desde dos poblaciones</a></li>
<li class="chapter" data-level="9.3.7" data-path="14-capitulo13.html"><a href="#distribuci%C3%B3n-del-cociente-de-varianzas"><i class="fa fa-check"></i><b>9.3.7</b> Distribución del cociente de varianzas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="14-capitulo13.html"><a href="#resumen-de-la-relaci%C3%B3n-entre-estimadores-y-par%C3%A1metros"><i class="fa fa-check"></i><b>9.4</b> Resumen de la relación entre estimadores y parámetros</a></li>
<li class="chapter" data-level="9.5" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#hacerlo-en-r-7"><i class="fa fa-check"></i><b>9.5</b> Hacerlo en R</a></li>
</ul></li>
<li class="part"><span><b>III Estadística inferencial</b></span></li>
<li class="chapter" data-level="10" data-path="14-capitulo13.html"><a href="#estimaci%C3%B3n-por-intervalo"><i class="fa fa-check"></i><b>10</b> Estimación por intervalo</a>
<ul>
<li class="chapter" data-level="10.1" data-path="14-capitulo13.html"><a href="#estimaci%C3%B3n-puntual"><i class="fa fa-check"></i><b>10.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="10.2" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html"><i class="fa fa-check"></i><b>10.2</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="10.3" data-path="14-capitulo13.html"><a href="#estimaci%C3%B3n-de-la-media"><i class="fa fa-check"></i><b>10.3</b> Estimación de la media</a></li>
<li class="chapter" data-level="10.4" data-path="14-capitulo13.html"><a href="#estimaci%C3%B3n-de-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.4</b> Estimación de la proporción</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-clopper-pearson"><i class="fa fa-check"></i><b>10.4.1</b> Intervalo de Clopper-Pearson</a></li>
<li class="chapter" data-level="10.4.2" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-wald"><i class="fa fa-check"></i><b>10.4.2</b> Intervalo de Wald</a></li>
<li class="chapter" data-level="10.4.3" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-wilson"><i class="fa fa-check"></i><b>10.4.3</b> Intervalo de Wilson</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#la-calidad-de-las-estimaciones-por-intervalo"><i class="fa fa-check"></i><b>10.5</b> La calidad de las estimaciones por intervalo</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="14-capitulo13.html"><a href="#el-error-de-estimaci%C3%B3n-en-la-media"><i class="fa fa-check"></i><b>10.5.1</b> El error de estimación en la media</a></li>
<li class="chapter" data-level="10.5.2" data-path="14-capitulo13.html"><a href="#el-error-de-estimaci%C3%B3n-en-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.5.2</b> El error de estimación en la proporción</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#probabilidad-de-cobertura"><i class="fa fa-check"></i><b>10.6</b> Probabilidad de cobertura</a></li>
<li class="chapter" data-level="10.7" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#hacerlo-en-r-8"><i class="fa fa-check"></i><b>10.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-para-la-media"><i class="fa fa-check"></i><b>10.7.1</b> Intervalo para la media</a></li>
<li class="chapter" data-level="10.7.2" data-path="14-capitulo13.html"><a href="#intervalo-para-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.7.2</b> Intervalo para la proporción</a></li>
<li class="chapter" data-level="10.7.3" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#cobertura"><i class="fa fa-check"></i><b>10.7.3</b> Cobertura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="14-capitulo13.html"><a href="#prueba-de-hip%C3%B3tesis-la-l%C3%B3gica"><i class="fa fa-check"></i><b>11</b> Prueba de hipótesis: la lógica</a>
<ul>
<li class="chapter" data-level="11.1" data-path="14-capitulo13.html"><a href="#el-razonamiento-de-la-prueba-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>11.1</b> El razonamiento de la prueba de hipótesis</a></li>
<li class="chapter" data-level="11.2" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html"><i class="fa fa-check"></i><b>11.2</b> Prueba sobre la media</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="14-capitulo13.html"><a href="#la-toma-de-decisi%C3%B3n"><i class="fa fa-check"></i><b>11.2.1</b> La toma de decisión</a></li>
<li class="chapter" data-level="11.2.2" data-path="14-capitulo13.html"><a href="#los-puntos-cr%C3%ADticos-en-t%C3%A9rminos-del-estimador"><i class="fa fa-check"></i><b>11.2.2</b> Los puntos críticos en términos del estimador</a></li>
<li class="chapter" data-level="11.2.3" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#pruebas-unilaterales"><i class="fa fa-check"></i><b>11.2.3</b> Pruebas unilaterales</a></li>
<li class="chapter" data-level="11.2.4" data-path="14-capitulo13.html"><a href="#otros-ejemplos-de-prueba-de-hip%C3%B3tesis-sobre-la-media"><i class="fa fa-check"></i><b>11.2.4</b> Otros ejemplos de prueba de hipótesis sobre la media</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="14-capitulo13.html"><a href="#prueba-sobre-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>11.3</b> Prueba sobre la proporción</a></li>
<li class="chapter" data-level="11.4" data-path="14-capitulo13.html"><a href="#tipos-de-error-en-las-pruebas-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>11.4</b> Tipos de error en las pruebas de hipótesis</a></li>
<li class="chapter" data-level="11.5" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#etii-mu-alpha-y-n"><i class="fa fa-check"></i><b>11.5</b> <em>ETII:</em> <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(n\)</span></a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#curva-de-potencia"><i class="fa fa-check"></i><b>11.5.1</b> Curva de potencia</a></li>
<li class="chapter" data-level="11.5.2" data-path="14-capitulo13.html"><a href="#significaci%C3%B3n-estad%C3%ADstica-y-valor-p"><i class="fa fa-check"></i><b>11.5.2</b> Significación estadística y valor <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="14-capitulo13.html"><a href="#muestras-peque%C3%B1as-y-pruebas-t"><i class="fa fa-check"></i><b>11.6</b> Muestras pequeñas y pruebas <span class="math inline">\(t\)</span></a></li>
<li class="chapter" data-level="11.7" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#hacerlo-en-r-9"><i class="fa fa-check"></i><b>11.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#prueba-sobre-la-media-1"><i class="fa fa-check"></i><b>11.7.1</b> Prueba sobre la media</a></li>
<li class="chapter" data-level="11.7.2" data-path="14-capitulo13.html"><a href="#prueba-sobre-la-proporci%C3%B3n-1"><i class="fa fa-check"></i><b>11.7.2</b> Prueba sobre la proporción</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#resumen-de-pruebas-sobre-una-muestra"><i class="fa fa-check"></i><b>11.8</b> Resumen de pruebas sobre una muestra</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="14-capitulo13.html"><a href="#prueba-de-hip%C3%B3tesis-las-aplicaciones"><i class="fa fa-check"></i><b>12</b> Prueba de hipótesis: las aplicaciones</a>
<ul>
<li class="chapter" data-level="12.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html"><i class="fa fa-check"></i><b>12.1</b> Muestras independientes</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#prueba-de-diferencia-de-medias"><i class="fa fa-check"></i><b>12.1.1</b> Prueba de diferencia de medias</a></li>
<li class="chapter" data-level="12.1.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#muestras-apareadas"><i class="fa fa-check"></i><b>12.1.2</b> Muestras apareadas</a></li>
<li class="chapter" data-level="12.1.3" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#coeficiente-r-de-pearson"><i class="fa fa-check"></i><b>12.1.3</b> Coeficiente r de Pearson</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#hacerlo-en-r-10"><i class="fa fa-check"></i><b>12.2</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#ejemplo-1."><i class="fa fa-check"></i><b>12.2.1</b> Ejemplo 1.</a></li>
<li class="chapter" data-level="12.2.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#ejemplo-2."><i class="fa fa-check"></i><b>12.2.2</b> Ejemplo 2.</a></li>
<li class="chapter" data-level="12.2.3" data-path="14-capitulo13.html"><a href="#aplicaci%C3%B3n-a-los-datos-de-poblaci%C3%B3n-adulta-mayor"><i class="fa fa-check"></i><b>12.2.3</b> Aplicación a los datos de Población Adulta Mayor</a></li>
<li class="chapter" data-level="12.2.4" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#prueba-apareada"><i class="fa fa-check"></i><b>12.2.4</b> Prueba apareada</a></li>
<li class="chapter" data-level="12.2.5" data-path="14-capitulo13.html"><a href="#coeficiente-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>12.2.5</b> Coeficiente de correlación</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html"><i class="fa fa-check"></i><b>13</b> Cuando los supuestos no se cumplen</a>
<ul>
<li class="chapter" data-level="13.0.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#las-pruebas-ji-cuadrado-o-chi-cuadrado"><i class="fa fa-check"></i><b>13.0.1</b> Las pruebas ji cuadrado (o chi cuadrado)</a></li>
<li class="chapter" data-level="13.0.2" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#coeficiente-r_s-de-spearman"><i class="fa fa-check"></i><b>13.0.2</b> Coeficiente <span class="math inline">\(r_s\)</span> de Spearman</a></li>
<li class="chapter" data-level="13.0.3" data-path="14-capitulo13.html"><a href="#alternativas-no-param%C3%A9tricas-a-las-pruebas-t"><i class="fa fa-check"></i><b>13.0.3</b> Alternativas no paramétricas a las pruebas t</a></li>
<li class="chapter" data-level="13.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#hacerlo-en-r-11"><i class="fa fa-check"></i><b>13.1</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-1"><i class="fa fa-check"></i><b>13.1.1</b> Ejemplo 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-2"><i class="fa fa-check"></i><b>13.1.2</b> Ejemplo 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-la-mediana-1"><i class="fa fa-check"></i><b>13.1.3</b> Prueba de la mediana</a></li>
<li class="chapter" data-level="13.1.4" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-wilcoxon"><i class="fa fa-check"></i><b>13.1.4</b> Prueba de Wilcoxon</a></li>
<li class="chapter" data-level="13.1.5" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#muestras-apareadas-1"><i class="fa fa-check"></i><b>13.1.5</b> Muestras apareadas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="14-capitulo13.html"><a href="#tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>14</b> Tamaño del efecto</a>
<ul>
<li class="chapter" data-level="14.1" data-path="14-capitulo13.html"><a href="#significaci%C3%B3n-estad%C3%ADstica-y-significaci%C3%B3n-pr%C3%A1ctica"><i class="fa fa-check"></i><b>14.1</b> Significación estadística y significación práctica</a></li>
<li class="chapter" data-level="14.2" data-path="14-capitulo13.html"><a href="#medidas-de-tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>14.2</b> Medidas de tamaño del efecto</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html"><i class="fa fa-check"></i><b>14.2.1</b> Prueba t para diferencia de medias</a></li>
<li class="chapter" data-level="14.2.2" data-path="14-capitulo13.html"><a href="#an%C3%A1lisis-de-la-varianza"><i class="fa fa-check"></i><b>14.2.2</b> Análisis de la varianza</a></li>
<li class="chapter" data-level="14.2.3" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#correlaciones"><i class="fa fa-check"></i><b>14.2.3</b> Correlaciones</a></li>
<li class="chapter" data-level="14.2.4" data-path="14-capitulo13.html"><a href="#regresi%C3%B3n-lineal"><i class="fa fa-check"></i><b>14.2.4</b> Regresión lineal</a></li>
<li class="chapter" data-level="14.2.5" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#pruebas-ji-cuadrado"><i class="fa fa-check"></i><b>14.2.5</b> Pruebas ji cuadrado</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="14-capitulo13.html"><a href="#an%C3%A1lisis-de-la-potencia"><i class="fa fa-check"></i><b>14.3</b> Análisis de la potencia</a></li>
<li class="chapter" data-level="14.4" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#hacerlo-en-r-12"><i class="fa fa-check"></i><b>14.4</b> Hacerlo en R</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Generado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cuando-los-supuestos-no-se-cumplen" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Capítulo 13</span> Cuando los supuestos no se cumplen<a href="cuando-los-supuestos-no-se-cumplen.html#cuando-los-supuestos-no-se-cumplen" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>N.B. En este capítulo no nos detendremos en detalles de los procedimientos, solo las condiciones de aplicación de cada uno y, en el último apartado, el modo de reproducir los ejemplos en R.</p>
<p>Las condiciones que se han pedido hasta este punto para los
procedimientos vistos, son exigentes. Por ejemplo, en las <em>pruebas t</em>
debemos suponer que la variable tiene distribución normal en la
población<a href="#fn92" class="footnote-ref" id="fnref92"><sup>92</sup></a>. El Teorema Central del Límite nos dice que si las
muestras son lo suficientemente grandes, la distribución muestral tiende
a ser normal, por lo que puede eliminarse el supuesto de normalidad en
la población si las muestras tienen suficiente tamaño, pero a menudo no
es posible contar con muestras grandes. Todas las pruebas que hemos
visto hasta este momento hacen supuestos acerca de la población, que son
condiciones que debe cumplir la distribución de las variables bajo
análisis en la población; estos supuestos a veces se cumplen y otras no.
Los resultados que se obtengan de esas pruebas dependen del cumplimiento
de esas condiciones. En algunos casos es posible poner a prueba la
veracidad de esas exigencias, para ver si se cumplen, en otros casos,
solo es posible “suponer” que es así. Por esa razón los resultados
pueden ser aproximados o directamente incorrectos, si hay violaciones
graves a sus condiciones de aplicación.</p>
<p>Además, los cálculos hechos en las pruebas mencionadas, requieren un
nivel de medición alto, para poder calcular medias y varianzas. Hemos
resuelto parcialmente el problema cuando, al tratar con variables
nominales, usamos la proporción de casos en alguna categoría. Sin
embargo no hemos resuelto aún el problema de analizar relaciones entre
variables cualitativas, a las que no puede calcularse la media ni la
varianza, pero que a menudo aparecen en nuestros análisis. Es el mismo
caso con el coeficiente de Pearson, su cálculo requiere que se calculen
medias y varianzas, lo que no puede hacerse si las variables no son
métricas.</p>
<p>Estos problemas son muy frecuentes en investigación
social: pocos casos, variables que no son métricas, sin certeza sobre la
normalidad de las distribuciones paramétricas. Para ellos existe un conjunto de
pruebas llamadas <strong>pruebas no paramétricas</strong>. Por oposición a ellas,
todas las pruebas presentadas hasta aquí son <strong>pruebas paramétricas</strong>,
que quiere decir que especifican ciertas condiciones que deben cumplir
(o que puede suponerse que cumplan) los parámetros de la población de la
que se extrae la muestra.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Son <strong>pruebas no paramétricas</strong> las pruebas de hipótesis que no especifican condiciones sobre los parámetros de la población de la que proviene la muestra.</td>
</tr>
</tbody>
</table>
<p>La limitación de las pruebas no paramétricas respecto de las
paramétricas, es que tienen, a igual nivel de significación e igual
tamaño de muestra, menor potencia. Eso significa que, para obtener la
misma potencia en una prueba no paramétrica que en una paramétrica, es
necesario usar más casos.</p>
<p>Si el problema es el nivel de medición de las variables —que en la
mayoría de los casos no es métrico—, puede resolverse apelando a una
prueba no paramétrica y lograr resultados de la misma calidad, aunque a
un mayor costo por la mayor cantidad de casos necesarios.</p>
<p>Si el problema es el tamaño de la muestra, es decir, si tenemos muy
pocos casos observados y no puede suponerse distribución normal en la
población, entonces no hay alternativa y debe usarse una prueba no
paramétrica.</p>
<p>En este capítulo desarrollaremos tres pruebas no paramétricas basadas en
el puntaje ji cuadrado y dos alternativas a las pruebas t para muestras
independientes y apareadas. Puede consultarse el manual de <span class="citation">Siegel (<a href="#ref-siegel1957">1957</a>)</span>
para una presentación muy completa, aunque no actualizada a
procedimientos informáticos, .</p>
<div id="las-pruebas-ji-cuadrado-o-chi-cuadrado" class="section level3 hasAnchor" number="13.0.1">
<h3><span class="header-section-number">13.0.1</span> Las pruebas ji cuadrado (o chi cuadrado)<a href="cuando-los-supuestos-no-se-cumplen.html#las-pruebas-ji-cuadrado-o-chi-cuadrado" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ya hemos usado el puntaje <em>ji cuadrado</em> para derivar medidas de la asociación
entre dos variables nominales (V de Cramer, C de Pearson) y luego como
un modelo especial de probabilidades. Ahora relacionaremos esos dos usos
del puntaje <em>ji cuadrado</em>, en primer lugar para analizar la eventual
independencia entre dos variables (prueba de independencia de
atributos), luego para evaluar si una distribución se ajusta a un modelo
predicho (prueba de bondad de ajuste) y finalmente para comparar la
tendencia central entre variables de nivel ordinal (prueba de la
mediana).</p>
<div id="prueba-de-independencia-de-atributos" class="section level4 hasAnchor" number="13.0.1.1">
<h4><span class="header-section-number">13.0.1.1</span> Prueba de independencia de atributos<a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-independencia-de-atributos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>El puntaje <em>ji cuadrado</em> <span class="math inline">\((\chi^{2})\)</span> es una medida de la
distancia que hay entre una distribución de frecuencias bivariada
observada y la correspondiente distribución de frecuencias esperadas.
Estas frecuencias esperadas son las que se esperarían observar si las
variables fueran independientes. Así, cuanto más alejadas se encuentren
las frecuencias observadas de las esperadas, tanto más grande será el
puntaje <span class="math inline">\(\chi^{2}\)</span> y más alejadas de la independencia estarán las
variables que se analizan. El hecho de estar alejadas de la
independencia implica que existe alguna asociación entre ellas. El valor
mínimo de este puntaje es cero, que solo podría alcanzarse si todas las
frecuencias observadas coincidieran con las esperadas y sería el caso de
una independencia perfecta; una situación muy improbable de hallar en la
realidad. Pero el puntaje <span class="math inline">\(\chi^{2}\)</span> carece de un valor máximo, puede ser
indefinidamente grande, dependiendo no solo de lo alejadas que estén las
frecuencias observadas de las esperadas, sino también de la dimensión de
la tabla y de la cantidad de casos.</p>
<p>Como las frecuencias observadas que están en la tabla bivariada
provienen de una muestra, necesitamos poder generalizar el resultado que
hallemos a la población de referencia. Es decir que ahora, en el
contexto de la inferencia, nos preguntamos ¿Cómo debería ser de grande
el puntaje <span class="math inline">\(\chi^{2}\)</span> encontrado para que consideremos que las variables
se alejan lo suficiente de la independencia y en consecuencia, se pueda decir que la asociación es significativa? Por la redacción de la
pregunta puede verse que tratamos con una prueba de hipótesis, nos
estamos preguntando ¿A partir de qué valor podemos considerar que
<span class="math inline">\(\chi^{2}\)</span> es significativo? La respuesta dependerá del valor que asuma
<span class="math inline">\(\chi^{2}\)</span> (que está influido por el tamaño de la muestra) y de la
dimensión de la tabla. Para formular las hipótesis de esta prueba,
recordemos que la <span class="math inline">\(H_0\)</span> es aquella que indica no-diferencia, el
no-cambio, es la hipótesis “conservadora”. Por el contrario, la
hipótesis alternativa, <span class="math inline">\(H_1\)</span> presenta una diferencia en algún sentido. En este
problema, como vamos a tratar acerca de relaciones entre variables, la
<span class="math inline">\(H_0\)</span> indicará que no hay relación o, lo que es lo mismo, que las
variables son independientes.</p>
<p>Ejemplo 1 (datos ficticios) se trata analizar la posible relación entre el resultado del primer parcial de Psicoestadística (aprobado – no
aprobado) y el turno en que fue realizado. Se construye una
muestra con 180 estudiantes seleccionada entre quienes hicieron el primer parcial en los últimos cinco años. La siguiente es la tabla de
distribución de frecuencias observadas.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-554">Tabla 13.1: </span>Frecuencias conjuntas observadas del resultado del parcial y el turno en que se realizó.
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Resultado del parcial
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Turno
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Mañana
</th>
<th style="text-align:center;">
Tarde
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Aprobado
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
No aprobado
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
40
</td>
</tr>
</tbody>
</table>
<p>Para el análisis de la independencia se calculan las frecuencias
esperadas<a href="#fn93" class="footnote-ref" id="fnref93"><sup>93</sup></a>:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-555">Tabla 13.2: </span>Frecuencias conjuntas esperadas del resultado del parcial y el turno en que se realizó.
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Resultado del parcial
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Turno
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Mañana
</th>
<th style="text-align:center;">
Tarde
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Aprobado
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
28
</td>
</tr>
<tr>
<td style="text-align:left;">
No aprobado
</td>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
40
</td>
</tr>
</tbody>
</table>
<p>Las frecuencias esperadas conducen al puntaje<a href="#fn94" class="footnote-ref" id="fnref94"><sup>94</sup></a> <span class="math inline">\(\chi^{2}\)</span>, que en
este caso es <span class="math inline">\(\chi^{2} = 0.903\)</span>. En el interés por generalizar a toda la
población, se trata de alcanzar una conclusión acerca de la
independencia o no de las dos variables, que no esté limitada a estos
180 casos, sino que sea general. No debemos olvidar que los datos
disponibles son muestrales y, por el modo en que se seleccionan los
casos de la muestra, dependen del azar.</p>
<p>Nos preguntamos: ¿el valor hallado para el puntaje <span class="math inline">\(\chi^{2} = 0.903\)</span>,
puede explicarse por azar, o representa un distanciamiento
suficientemente grande como para atribuirlo a una relación entre las
variables en la población?</p>
<p>Queremos entonces decidir si lo que hemos observado para este grupo de estudiantes (la muestra de quienes cursaron en los últimos cinco años, por ejemplo) es general; es decir, si vale para estudiantes que no participaron de la muestra.<br />
Por eso, la hipótesis nula de la prueba será:</p>
<p><span class="math inline">\(H_0\)</span>: El resultado del parcial es independiente del turno en que se
realiza<a href="#fn95" class="footnote-ref" id="fnref95"><sup>95</sup></a></p>
<p>Que equivale a afirmar que no hay relación entre el turno y el
resultado.</p>
<p>Su contrapartida, la <span class="math inline">\(H_1\)</span> dirá que:</p>
<p><span class="math inline">\(H_1\)</span>: Existe relación entre el turno en el que se realiza el parcial y
el resultado que se obtiene.</p>
<p>La pregunta será entonces si la evidencia hallada a partir de nuestros
datos es suficiente para rechazar <span class="math inline">\(H_0\)</span> y concluir que las variables
están relacionadas o si, por el contrario, deberemos seguir sosteniendo
que las variables no están relacionadas.</p>
<p>La variable aleatoria <span class="math inline">\(\chi^{2}\)</span> tiene una distribución de probabilidad
asimétrica y su forma depende de los grados de libertad. Estos últimos,
para tablas de doble entrada dependen del número de filas y de columnas
que tenga la tabla, según:</p>
<p><span class="math display">\[gl = ( f - 1)*( c - 1)\]</span></p>
<p>Donde <span class="math inline">\(gl\)</span> son los grados de libertad, <span class="math inline">\(f\)</span> es el número de filas de la
tabla y <span class="math inline">\(c\)</span> el número de columnas. Entonces conocemos el puntaje
<span class="math inline">\(\chi^{2}\)</span> y su distribución de probabilidad, con lo que puede decidirse
si se trata de un valor extremo (muy poco probable si <span class="math inline">\(H_0\)</span> fuera cierta)
o bien de un valor esperable. En el primer caso rechazaremos <span class="math inline">\(H_0\)</span> y
concluiremos que hay relación entre el turno en que se hace el parcial y
el resultado que se obtiene. En el segundo caso, aceptaremos <span class="math inline">\(H_0\)</span> y
diremos que no hay evidencia para descartar la independencia, o que no
hay pruebas para sostener que las variables estén relacionadas.
Rechazaremos <span class="math inline">\(H_0\)</span> si el valor <span class="math inline">\(\chi^{2}\)</span> encontrado es grande, porque
eso es sinónimo de un gran alejamiento de nuestros datos respecto de la
independencia. En razón de ello, ésta será siempre una prueba unilateral
derecha: se rechaza para valores que excedan cierto límite.</p>
<p>El procedimiento para hacer la prueba puede ser el tradicional, que
consiste en fijar de antemano el nivel de significación
<span class="math inline">\((\alpha)\)</span>, luego determinar el (único) punto crítico y
comparar si el valor observado de <span class="math inline">\(\chi^{2}\)</span> excede ese punto crítico;
si es así se rechaza <span class="math inline">\(H_0\)</span>. O también puede usarse el <em>valor p</em> asociado
al puntaje <span class="math inline">\(\chi^{2}\)</span> observado, y si esa probabilidad es menor al nivel
de significación, se rechaza <span class="math inline">\(H_0\)</span>.</p>
<p>En este ejemplo, los grados de libertad son:</p>
<p><span class="math display">\[gl = (f - 1)*(c - 1) = (2 - 1)*(2 - 1) = 1*1 = 1\]</span></p>
<p>Se fija un nivel de significación <span class="math inline">\(\alpha = 0.05\)</span> y se
encuentra que el punto crítico que corresponde para esa área (superior)
y esos grados de libertad bajo la curva de la distribución <span class="math inline">\(\chi^{2}\)</span>. El resultado es:</p>
<pre><code>## [1] 3.841459</code></pre>
<p>Se lo llama <span class="math inline">\(\chi^{2}_{c}\)</span> (chi cuadrado crítico). La
representación gráfica de la zona de rechazo de <span class="math inline">\(H_0\)</span> es entonces:</p>
<p>Gráfico 1: Ubicación del punto crítico que deja un 5% de área superior
en una distribución <span class="math inline">\(\chi^{2}\)</span> con 2 grados de libertad.</p>
<p><img src="EstadisticaParaCienciasSocialesConR_files/figure-html/unnamed-chunk-557-1.svg" width="672" /></p>
<p>De acuerdo a este gráfico, la región de rechazo de <span class="math inline">\(H_0\)</span> es la que se
encuentra a la derecha de 3.84, formada por todos los valores de
<span class="math inline">\(\chi^{2}\)</span> que superen a 3.84. Los datos dieron un puntaje
<span class="math inline">\(\chi_{obs}^{2} = 0.903\)</span>, que no pertenece a la zona de rechazo de
<span class="math inline">\(H_0\)</span>, por lo que no se rechaza <span class="math inline">\(H_0\)</span> y se concluye que no hay relación
entre las variables; o bien que no hay evidencia suficiente para
descartar la independencia entre el resultado del parcial y el turno en
que éste se realiza.</p>
<p>Si se prefiere usar el valor de probabilidad (<em>valor p</em>) para tomar la
decisión y dar mayor claridad a los resultados, entonces, como en las
pruebas paramétricas, se informa la probabilidad de hallar un valor de
<span class="math inline">\(\chi^{2}\)</span> como el observado o más extremo que él. En esta prueba (de
independencia de atributos), “más extremo” siempre quiere decir “mayor
que”, porque es una prueba unilateral derecha. Buscamos entonces la
probabilidad que tiene la variable <span class="math inline">\(\chi^{2}\)</span> con un grado de
libertad, de asumir un valor igual o mayor al que hemos observado, es
decir:</p>
<p><span class="math display">\[P(\chi^{2}{\geq \chi}_{obs}^{2}) = P(\chi^{2} \geq 0.903)\]</span></p>
<p>Que es:</p>
<pre><code>## [1] 0.3419786</code></pre>
<p>Lo leemos diciendo
que, si las dos variables fueran independientes, la probabilidad de
hallar un puntaje <span class="math inline">\(\chi^{2}\)</span> como el observado o más extremo que él es
de 0.3420. Dado que es una probabilidad alta (sea a un nivel de
significación del 0.05 o de 0.10), consideramos a éste como un resultado
altamente probable, de ser cierto que las variables son independientes, por lo que no constituye evidencia para rechazar <span class="math inline">\(H_0\)</span>.</p>
<p>La representación gráfica de esta probabilidad es el área sombreada, a la derecha del valor <span class="math inline">\(\chi^2_{obs}=0.903\)</span>:</p>
<p><img src="EstadisticaParaCienciasSocialesConR_files/figure-html/unnamed-chunk-559-1.svg" width="672" /></p>
</div>
<div id="pruebas-de-bondad-de-ajuste" class="section level4 hasAnchor" number="13.0.1.2">
<h4><span class="header-section-number">13.0.1.2</span> Pruebas de bondad de ajuste<a href="cuando-los-supuestos-no-se-cumplen.html#pruebas-de-bondad-de-ajuste" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>El cálculo del puntaje <span class="math inline">\(\chi^{2}\)</span> ofrece la posibilidad de hacer
comparaciones entre frecuencias observadas (reales, provenientes de la
recolección de datos) y frecuencias esperadas bajo diferentes hipótesis.
En la prueba anterior, las esperadas lo han sido bajo la hipótesis de
independencia, pero la condición bajo la cual se esperan determinadas
frecuencias puede ser otra y el puntaje <span class="math inline">\(\chi^{2}\)</span> también permite medir
esas distancias.</p>
<p>Ejemplo 2 (datos ficticios): la distribución de la condición que alcanzan quienes cursan Psicoestadística ha sido, históricamente, que 35% alcanzan la promoción, 35% la regularidad y el 30% queda libre. Consideremos el subconjunto de quienes estudian otra carrera además de Psicología. Una muestra de 142 estudiantes de este grupo se distribuye, según condición, del siguiente modo:</p>
<p>Tabla 3: Distribución de frecuencias de estudiantes de Psicología que
también estudian otra carrera, según condición:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
condición
</th>
<th style="text-align:center;">
estudiantes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Promoción
</td>
<td style="text-align:center;">
53
</td>
</tr>
<tr>
<td style="text-align:left;">
Regularidad
</td>
<td style="text-align:center;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Libres
</td>
<td style="text-align:center;">
38
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:center;">
142
</td>
</tr>
</tbody>
</table>
<p>La tabla anterior muestra las frecuencias observadas. Nos preguntamos si
esta distribución se aleja significativamente de la tendencia general (del conjunto completo de quienes cursan la materia), o
bien si está dentro de lo esperado. Esta pregunta puede reformularse en
dirección a saber si los datos observados se “ajustan” a la distribución
general o se apartan de ella. Expresado en términos de hipótesis, la
<span class="math inline">\(H_0\)</span> afirmará que no hay diferencia:</p>
<p><span class="math inline">\(H_0\)</span>: La distribución de quienes alcanzan la promoción, la regularidad y quedan libres entre quienes estudian otra carrera se ajusta a la distribución del total de estudiantes.</p>
<p>Mientras que la <span class="math inline">\(H_1\)</span>, afirmará lo contrario:</p>
<p><span class="math inline">\(H_1\)</span>: La distribución de quienes alcanzan la promoción, la regularidad y quedan libres entre quienes estudian otra carrera se aparta de la distribución del total de estudiantes.</p>
<p>Si la distribución se mantuviera igual (si <span class="math inline">\(H_0\)</span> fuera verdadera),
esperaríamos que el grupo de 142 que estudian otra carrera se
distribuyeran en las tres categorías según estas proporciones: 0.35 -
0.35 - 0.30. La frecuencia que esperaríamos encontrar en la categoría
promoción es <span class="math inline">\(0.35*142= 49.7\)</span> y del mismo modo con las demás
categorías. Por lo que esperaríamos la siguiente distribución de
frecuencias:</p>
<p>Tabla 4: Frecuencias esperadas bajo la hipótesis de ajuste a la
distribución general:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
condición
</th>
<th style="text-align:center;">
estudiantes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Promoción
</td>
<td style="text-align:center;">
49,7
</td>
</tr>
<tr>
<td style="text-align:left;">
Regularidad
</td>
<td style="text-align:center;">
49,7
</td>
</tr>
<tr>
<td style="text-align:left;">
Libres
</td>
<td style="text-align:center;">
42,6
</td>
</tr>
</tbody>
</table>
<p>Disponemos ahora de las dos tablas, una de frecuencias observadas y otra
de esperadas y queremos evaluar si son similares o muy diferentes; que
es el mismo problema que en la prueba de independencia, solo que ahora
las tablas son univariadas. Para medir la distancia entre las dos tablas
nuevamente se usa el puntaje <span class="math inline">\(\chi^{2}\)</span>, que compara una a una las
frecuencias de las celdas. Aplicada a las tablas de arriba, da:</p>
<p><span class="math display">\[\chi^{2} = \sum_{}^{}{\frac{(f_{o} - f_{o} )^{2}}{f_{e}} = \frac{( 53 - 49.7 )^{2}}{49.7} + \frac{( 51 - 49.7)^{2}}{49.7} + \frac{( 38 - 42.6)^{2}}{42.6}} =0.75\]</span></p>
<p>Del mismo modo que en la prueba de independencia de atributos,
buscaremos un valor crítico de <span class="math inline">\(\chi^{2}\)</span>, para tomar la decisión. En
este caso, los grados de libertad de la distribución <span class="math inline">\(\chi^{2}\)</span> dependen
del número de categorías de la tabla univariada, simplemente es el
número de categorías menos uno:</p>
<p><span class="math display">\[gl = k - 1\]</span></p>
<p>En este ejemplo, las categorías son tres, por lo que <em>gl=2</em>. Con 2
grados de libertad y 5% de nivel de significación, el punto crítico es</p>
<pre><code>## [1] 5.991465</code></pre>
<p>Por lo que la región de rechazo es el conjunto de
valores que superan 5.99. El valor observado se encuentra fuera de la
región de rechazo, por lo que corresponde no rechazar <span class="math inline">\(H_0\)</span> y concluir
que quienes estudian otra carrera además de Psicología no
muestran, en Psicoestadística, una distribución entre las condiciones de promoción, regularidad y quedar libre, que difiera significativamente de la tendencia general de quienes cursan esa materia.</p>
</div>
<div id="prueba-de-la-mediana" class="section level4 hasAnchor" number="13.0.1.3">
<h4><span class="header-section-number">13.0.1.3</span> Prueba de la mediana<a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-la-mediana" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Cuando es necesario comparar la tendencia central de dos distribuciones,
se dispone de la <em>prueba t de diferencia de medias</em>. Sin embargo esa
prueba no es válida cuando se trabaja con variables que tienen nivel
ordinal, ya que allí no tiene interpretación la media ni tampoco la
varianza. Si se deben comprar dos muestras en una variable medida a
nivel ordinal se puede plantear la hipótesis que afirma que las medianas
son iguales, como una equivalencia a la que, en variables métricas,
plantea que las medias de dos distribuciones son iguales:</p>
<p><span class="math display">\[H_0: M_{dn_1} - M_{dn_2} = 0\]</span></p>
<p>Frente a una hipótesis alternativa que usualmente es bilateral:</p>
<p><span class="math display">\[H_0: M_{dn_1} - M_{dn_2} \neq 0\]</span></p>
<p>El procedimiento consiste en calcular, en primer lugar, la mediana del
grupo compuesto por los casos de las dos muestras, todos reunidos en una
sola distribución, se la denomina “mediana combinada” y se indica
<span class="math inline">\(M_{dn_c}\)</span>. Luego se cuentan los casos de cada grupo que quedan
por encima y por debajo de esa mediana combinada. Si la mediana de los
dos grupos fuera la misma, se esperaría que aproximadamente la mitad de
los casos de cada grupo queden por encima de la mediana combinada y la
otra mitad por debajo. En la medida que los casos de los grupos se
aparten de esa forma de distribuirse habrá evidencia para creer que las
medianas difieren. Por lo tanto, se trata de ver si una distribución
real de datos respeta una distribución teórica (esperada) o no.</p>
<p>La disposición de los datos se realiza en una tabla de dos por dos como
la siguiente:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Grupo
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
Ubicación respecto de la mediana combinada
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:left;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Por encima
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Por debajo
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
<p>Bajo la hipótesis nula, esperaríamos que la cantidad de casos por encima
y por debajo de la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> fuera la misma para los dos
grupos. Dicho de otro modo, para aceptar la <span class="math inline">\(H_0\)</span> deberíamos hallar
independencia entre la pertenencia a los grupos y la ubicación de los
casos por encima y por debajo de <span class="math inline">\(M_{\text{dn}_{c}}\)</span>. De este modo vemos
que el problema puede tratarse como una prueba de independencia: si el
puntaje <span class="math inline">\(\chi_{\text{obs}}^{2}\)</span> es tal que debe rechazarse la hipótesis
de independencia, será —en esta prueba—, equivalente a rechazar la
igualdad de las medianas.</p>
<p>Un problema que suele aparecer cuando se hace el recuento de casos por
encima y por debajo de la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> es que algunos coincidan
con ella, que no estén ni encima ni debajo. Si la cantidad total de
casos con que se cuenta es grande, se pueden dejar de lado esos casos y
solo contar los que efectivamente difieran (en más o en menos) de la
<span class="math inline">\(M_{\text{dn}_{c}}\)</span>. De lo contrario, puede hacerse el recuento de los
casos que están por encima de la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> y los que no lo
están, es decir que uno de los grupos cuenta la cantidad de casos que
hay por encima de la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> y el otro los que la igualan o
están por debajo de ella.</p>
<p>Ejemplo (datos ficticios): se comparan las calificaciones “de concepto”
asignadas por docentes de escuelas primarias de dos grupos de estudiantes.
Dichas calificaciones, presentan categorías: 1. Excelente, 2. Muy bueno,
3. Bueno, 4. Satisfactorio, 5. No satisfactorio, por lo que son de nivel
ordinal y no es posible realizar una prueba de diferencia de medias, en
su reemplazo recurrimos a la prueba de la mediana. Se seleccionan 40
estudiantes de cada docente y se relevan sus notas de concepto.
Calculamos la mediana del grupo completo (80 casos) y obtenemos 3. A
continuación contamos cuántos de los de la primera docente están por
encima y por debajo de 3 y lo mismo para la segunda docente. La
distribución queda del siguiente modo:</p>
<!--tabla XXX-->
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Grupo
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
Ubicación respecto de la mediana combinada
</th>
<th style="text-align:center;">
1
</th>
<th style="text-align:center;">
2
</th>
<th style="text-align:left;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Por encima
</td>
<td style="text-align:center;">
28
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:left;">
36
</td>
</tr>
<tr>
<td style="text-align:left;">
Por debajo
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:left;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:center;">
36
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:left;">
68
</td>
</tr>
</tbody>
</table>
<p>Aunque originalmente se relevaron 40 estudiantes de cada docente, quedaron 36 de la primera y 32 de la segunda, porque cuatro casos de un grupo y ocho del otro coincidieron con la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> y fueron
descartados, con lo que el total se redujo a 68 observaciones.</p>
<p>La sola inspección de la tabla sugiere que debe descartarse la igualdad
de las medianas de los grupos, ya que hay concentración de casos en las
celdas de la diagonal, que es una indicación de la relación que hay
entre filas y columnas. El grupo 1 está mayoritariamente por encima de
la <span class="math inline">\(M_{\text{dn}_{c}}\)</span> y el grupo 2 por debajo. En efecto, el puntaje
<span class="math inline">\(\chi_{\text{obs}}^{2} = 13.33\)</span>, con 1 grado de libertad, tiene una
probabilidad asociada (<em>valor p</em>) de 0,00026, que quiere decir que se
rechaza la hipótesis de igualdad de medianas.</p>
</div>
</div>
<div id="coeficiente-r_s-de-spearman" class="section level3 hasAnchor" number="13.0.2">
<h3><span class="header-section-number">13.0.2</span> Coeficiente <span class="math inline">\(r_s\)</span> de Spearman<a href="cuando-los-supuestos-no-se-cumplen.html#coeficiente-r_s-de-spearman" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El coeficiente <em>r de Pearson</em> solo puede interpretarse si proviene de
variables medidas a nivel intervalar o proporcional, es decir, métricas.
Cuando trabajamos con variables ordinales, disponemos de otra medida de
la asociación, el coeficiente de correlación por rangos <span class="math inline">\(r_s\)</span> de Spearman, cuyos valores se interpretan como los de <em>r de Pearson</em>. Por
trabajar con un nivel de medición no métrico, la prueba sobre este
coeficiente es no paramétrica.</p>
<p>La prueba de hipótesis que permite generalizar su valor a una población
de referencia, casi no difiere de la de <span class="math inline">\(r\)</span>. Llamaremos <span class="math inline">\(\rho_{s}\)</span> al
coeficiente de Spearman paramétrico y <span class="math inline">\(r_s\)</span> al muestral. El error
estándar de este estimador tiene la misma forma que el de Pearson:</p>
<p><span class="math display">\[\sigma_{r_{s}} = \sqrt{\frac{1 - r_{s}^{2}}{n - 2}}\]</span></p>
<p>Y cuando la muestra tiene al menos 10 observaciones, se distribuye con
una distribución t con n-2 grados de libertad <span class="citation">(<a href="#ref-Kendall1948">Kendall 1948</a>)</span>. En consecuencia, el
estadístico de prueba será:</p>
<p><span class="math display">\[t = \frac{r_{s} - \rho_{s}}{\sqrt{\frac{1 - r_{s}^{2}}{n - 2}}}\]</span></p>
<p>Ejemplo (datos ficticios): se interroga a 20 votantes de un partido político sobre las razones de su voto y a partir de las respuestas se construye un índice que clasifica el compromiso con la ideología del partido en 1. Muy débil, 2. Débil, 3. Fuerte, 4. Muy fuerte. Los resultados de este índice se ponen en correspondencia con el nivel de educación de las personas encuestadas (1. Sin escolarización, 2. Primario incompleto, etc.). En el análisis de la relación entre estas dos variables ordinales obtenemos un coeficiente de correlación de Spearman de 0.32, que indica, en la muestra, una relación positiva y débil entre el compromiso ideológico y la educación. Preguntamos si este
resultado, obtenido sobre 20 casos, autoriza a afirmar que existe
alguna asociación no nula entre las dos variables más allá de la muestra observada.
Formularemos las hipótesis correspondientes a una prueba bilateral,
porque queremos probar si el coeficiente es significativamente diferente
de cero.</p>
<p><span class="math display">\[H_{0}: \rho_{s} = 0\]</span></p>
<p><span class="math display">\[H_{1}:\ \rho_{s} \neq 0\]</span></p>
<p>Fijamos el nivel de significación en el 5% y hallamos en una
distribución t con 18 grados de libertad (<span class="math inline">\(n - 2 = 20 - 2 = 18\)</span>) los
valores críticos correspondientes son:</p>
<pre><code>## [1] -2.100922</code></pre>
<pre><code>## [1] 2.100922</code></pre>
<p>El estadístico de prueba es:</p>
<p><span class="math display">\[t = \frac{r_{s} - \rho_{s}}{\sqrt{\frac{1 - r_{s}^{2}}{n - 2}}} = \frac{0.32}{\sqrt{\frac{1 - {0.32}^{2}}{20 - 2}}} = \frac{0.32}{0.223} = 1.43\]</span></p>
<p>Este valor se ubica en la región de no rechazo de <span class="math inline">\(H_0\)</span>, con lo que la
decisión es la de no rechazar <span class="math inline">\(H_0\)</span> y concluir que “no hay evidencia para creer que la correlación a nivel poblacional no sea nula”.<br />
El valor <span class="math inline">\(p\)</span> asociado a esta observación es:</p>
<pre><code>## [1] 0.1698461</code></pre>
<p>El valor <span class="math inline">\(p\)</span>, superior a los niveles de significación usuales es señal de lo probable que resulta que este resultado provenga del azar, es decir, no es evidencia para creer que en la población, la asociación efectivamente exista. Conclusión: no se rechaza la hipótesis nula y el coeficiente no resulta significativo.</p>
</div>
<div id="alternativas-no-paramétricas-a-las-pruebas-t" class="section level3 hasAnchor" number="13.0.3">
<h3><span class="header-section-number">13.0.3</span> Alternativas no paramétricas a las pruebas t<a href="#alternativas-no-param%C3%A9tricas-a-las-pruebas-t" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="muestras-independientes-1" class="section level4 hasAnchor" number="13.0.3.1">
<h4><span class="header-section-number">13.0.3.1</span> Muestras independientes<a href="cuando-los-supuestos-no-se-cumplen.html#muestras-independientes-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La prueba U de Mann-Whitney es la versión no paramétrica de la prueba t
de Student, es decir, sirve para comparar la tendencia central entre dos
muestras independientes. Se usa cuando no se cumplen los supuestos de la
prueba t y, sobre todo cuando las variables son de nivel ordinal. La
hipótesis nula es que las muestras provienen de poblaciones iguales.</p>
<p>Si se dispone de dos muestras de tamaños <span class="math inline">\(n_{1}\)</span> y <span class="math inline">\(n_{2}\)</span>, para
realizar la prueba se ordenan las observaciones de las dos muestras
juntas, de menor a mayor, y se les asignan rangos desde <span class="math inline">\(1\)</span> hasta
<span class="math inline">\(n_{1} + n_{2}\)</span>. Si la tendencia central de ambas poblaciones es la
misma los rangos deberían distribuirse aleatoriamente entre las dos
muestras y el rango medio de las observaciones de una muestra debería
ser casi el mismo que el de la otra. El estadístico de prueba U de
Mann-Whitney se construye a partir de la suma de rangos de una de las
muestras, <span class="math inline">\(R_{i}\)</span>, elegida arbitrariamente.</p>
</div>
<div id="muestras-relacionadas" class="section level4 hasAnchor" number="13.0.3.2">
<h4><span class="header-section-number">13.0.3.2</span> Muestras relacionadas<a href="cuando-los-supuestos-no-se-cumplen.html#muestras-relacionadas" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La prueba de los rangos con signo de Wilcoxon es una prueba no
paramétrica para comparar el rango medio de dos muestras relacionadas.
Es una alternativa a la prueba t de Student para muestras relacionadas,
que se usa en los casos en que no se sostiene la normalidad de la
distribución y, especialmente cuando las variables son de nivel ordinal.</p>
<p>La hipótesis nula dice que las muestras provienen de poblaciones con la
misma distribución de probabilidad. La prueba tiene en cuenta las
diferencias entre las puntuaciones de los elementos de cada par
asociado, y considera tanto el signo, como la magnitud de la diferencia.</p>
<div style="page-break-after: always;"></div>
</div>
</div>
<div id="hacerlo-en-r-11" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Hacerlo en R<a href="cuando-los-supuestos-no-se-cumplen.html#hacerlo-en-r-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ejemplo-1" class="section level3 hasAnchor" number="13.1.1">
<h3><span class="header-section-number">13.1.1</span> Ejemplo 1<a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Como se trata de datos ficticios, debemos primero generarlos.</p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb633-1" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;aprobado&quot;</span>, <span class="dv">90</span>), <span class="fu">rep</span>(<span class="st">&quot;no aprobado&quot;</span>, <span class="dv">40</span>))</span>
<span id="cb633-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb633-2" tabindex="-1"></a>turno <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;mañana&quot;</span>, <span class="dv">60</span>), <span class="fu">rep</span>(<span class="st">&quot;tarde&quot;</span>, <span class="dv">30</span>),</span>
<span id="cb633-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb633-3" tabindex="-1"></a>           <span class="fu">rep</span>(<span class="st">&quot;mañana&quot;</span>, <span class="dv">30</span>), <span class="fu">rep</span>(<span class="st">&quot;tarde&quot;</span>, <span class="dv">10</span>))</span>
<span id="cb633-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb633-4" tabindex="-1"></a>datos_ejemplo_1_chi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(resultado, turno)</span></code></pre></div>
<p>Y construimos la tabla</p>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb634-1" tabindex="-1"></a>resultado_por_turno <span class="ot">&lt;-</span> <span class="fu">table</span>(</span>
<span id="cb634-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb634-2" tabindex="-1"></a>  datos_ejemplo_1_chi<span class="sc">$</span>resultado,</span>
<span id="cb634-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb634-3" tabindex="-1"></a>                             datos_ejemplo_1_chi<span class="sc">$</span>turno)</span>
<span id="cb634-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb634-4" tabindex="-1"></a>resultado_por_turno</span></code></pre></div>
<pre><code>##              
##               mañana tarde
##   aprobado        60    30
##   no aprobado     30    10</code></pre>
<p>Ahora solicitamos la prueba <span class="math inline">\(\chi^2\)</span>:</p>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb636-1" tabindex="-1"></a>prueba <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(resultado_por_turno, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>El objeto “prueba” contiene los resultados, veamos cuáles son:</p>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb637-1" tabindex="-1"></a><span class="fu">names</span>(prueba)</span></code></pre></div>
<pre><code>## [1] &quot;statistic&quot; &quot;parameter&quot; &quot;p.value&quot;   &quot;method&quot;    &quot;data.name&quot; &quot;observed&quot; 
## [7] &quot;expected&quot;  &quot;residuals&quot; &quot;stdres&quot;</code></pre>
<p>Consultemos algunos de los valores:</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb639-1" tabindex="-1"></a>prueba<span class="sc">$</span>statistic</span></code></pre></div>
<pre><code>## X-squared 
## 0.9027778</code></pre>
<p>Es el valor del puntaje <span class="math inline">\(\chi_{obs}^2\)</span>.<br />
La tabla de frecuencias esperadas es:</p>
<div class="sourceCode" id="cb641"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb641-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb641-1" tabindex="-1"></a>prueba<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##              
##                 mañana    tarde
##   aprobado    62.30769 27.69231
##   no aprobado 27.69231 12.30769</code></pre>
<p>Se puede solicitar el resultado completo de la prueba:</p>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  resultado_por_turno
## X-squared = 0.90278, df = 1, p-value = 0.342</code></pre>
<p>Para ver el modo en que se llegó a ese valor <span class="math inline">\(p\)</span>, se calcula la probabilidad de superar el puntaje <span class="math inline">\(\chi_{obs}^2\)</span>. Se lo obtiene complementando la probabilidad acumulada.</p>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb644-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(.<span class="dv">9028</span>, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.342032</code></pre>
<p>El resultado conduce a no rechazar la hipótesis nula.</p>
</div>
<div id="ejemplo-2" class="section level3 hasAnchor" number="13.1.2">
<h3><span class="header-section-number">13.1.2</span> Ejemplo 2<a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nuevamente, hay que generar los datos</p>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb646-1" tabindex="-1"></a>condicion <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;promoción&quot;</span>, <span class="dv">53</span>),</span>
<span id="cb646-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb646-2" tabindex="-1"></a>               <span class="fu">rep</span>(<span class="st">&quot;regularidad&quot;</span>, <span class="dv">51</span>), <span class="fu">rep</span>(<span class="st">&quot;libres&quot;</span>, <span class="dv">38</span>))</span>
<span id="cb646-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb646-3" tabindex="-1"></a>tabla_condicion <span class="ot">&lt;-</span> <span class="fu">table</span>(condicion)</span>
<span id="cb646-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb646-4" tabindex="-1"></a>tabla_condicion</span></code></pre></div>
<pre><code>## condicion
##      libres   promoción regularidad 
##          38          53          51</code></pre>
<p>Y la de relativos, redondeada a tres decimales:</p>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb648-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(tabla_condicion), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## condicion
##      libres   promoción regularidad 
##       0.268       0.373       0.359</code></pre>
<p>En la aplicación de la prueba, los argumentos son la tabla univariada y las proporciones esperadas (hipotéticas) en cada categoría (en el orden que aparecen):</p>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb650-1" tabindex="-1"></a><span class="fu">chisq.test</span>(tabla_condicion, <span class="at">p =</span> <span class="fu">c</span>(.<span class="dv">30</span>, .<span class="dv">35</span>, .<span class="dv">35</span>))</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  tabla_condicion
## X-squared = 0.74983, df = 2, p-value = 0.6873</code></pre>
<p>La salida muestra el puntaje <span class="math inline">\(\chi^2\)</span>, los grados de libertad y el valor p asociado. Por tratarse de un valor elevado, concluimos que no hay evidencia para rechazar la hipótesis según la cual quienes estudian más de una carrera se ditribuyen entre regulares, promocionales y libres del mismo modo que lo hacen quienes solo estudian una carrera.</p>
</div>
<div id="prueba-de-la-mediana-1" class="section level3 hasAnchor" number="13.1.3">
<h3><span class="header-section-number">13.1.3</span> Prueba de la mediana<a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-la-mediana-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Construimos la matriz de datos, codificando del 1 al 5 los conceptos Excelente…. No satisfactorio.</p>
<div class="sourceCode" id="cb652"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb652-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-1" tabindex="-1"></a>docente_a <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb652-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-2" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="fu">rep</span>(<span class="dv">2</span>, <span class="dv">13</span>), <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="dv">4</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="dv">5</span>, <span class="dv">2</span>))</span>
<span id="cb652-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-3" tabindex="-1"></a></span>
<span id="cb652-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-4" tabindex="-1"></a>docente_b <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb652-5"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-5" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="fu">rep</span>(<span class="dv">2</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">8</span>), <span class="fu">rep</span>(<span class="dv">4</span>, <span class="dv">18</span>), <span class="fu">rep</span>(<span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb652-6"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-6" tabindex="-1"></a></span>
<span id="cb652-7"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-7" tabindex="-1"></a>concepto <span class="ot">&lt;-</span> <span class="fu">c</span>(docente_a, docente_b)</span>
<span id="cb652-8"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-8" tabindex="-1"></a>docente <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;a&quot;</span>, <span class="dv">40</span>), <span class="fu">rep</span>(<span class="st">&quot;b&quot;</span>, <span class="dv">40</span>))</span>
<span id="cb652-9"><a href="cuando-los-supuestos-no-se-cumplen.html#cb652-9" tabindex="-1"></a>datos_prueba_mediana <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(concepto, docente)</span></code></pre></div>
<p>La prueba de la mediana está en un paquete que no hemos usado aun, será necesario instalarlo y cargarlo en esta sesión:</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb653-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;agricolae&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb654-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;agricolae&quot;</span>)</span></code></pre></div>
<p>La prueba tiene como argumentos a las dos variables y se solicita que no haga una corrección interna:</p>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb655-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb655-1" tabindex="-1"></a>prueba_mediana <span class="ot">&lt;-</span> <span class="fu">Median.test</span>(datos_prueba_mediana<span class="sc">$</span>concepto,</span>
<span id="cb655-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb655-2" tabindex="-1"></a>  datos_prueba_mediana<span class="sc">$</span>docente,</span>
<span id="cb655-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb655-3" tabindex="-1"></a>  <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb655-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb655-4" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## The Median Test for datos_prueba_mediana$concepto ~ datos_prueba_mediana$docente 
## 
## Chi Square = 13.33333   DF = 1   P.Value 0.0002607296
## Median = 3 
## 
##   Median  r Min Max Q25 Q75
## a      2 40   1   5   1   3
## b      4 40   1   5   3   4
## 
## Post Hoc Analysis
## 
## Groups according to probability of treatment differences and alpha level.
## 
## Treatments with the same letter are not significantly different.
## 
##   datos_prueba_mediana$concepto groups
## b                             4      a
## a                             2      b</code></pre>
<p>Los componentes de este objeto son:</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb657-1" tabindex="-1"></a><span class="fu">names</span>(prueba_mediana)</span></code></pre></div>
<pre><code>## [1] &quot;statistics&quot; &quot;parameters&quot; &quot;medians&quot;    &quot;comparison&quot; &quot;groups&quot;</code></pre>
<p>Que tienen los valores:</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb659-1" tabindex="-1"></a>prueba_mediana<span class="sc">$</span>statistics</span></code></pre></div>
<pre><code>##      Chisq Df      p.chisq Median
##   13.33333  1 0.0002607296      3</code></pre>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb661-1" tabindex="-1"></a>prueba_mediana<span class="sc">$</span>parameters</span></code></pre></div>
<pre><code>##     test                       name.t ntr alpha
##   Median datos_prueba_mediana$docente   2  0.05</code></pre>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb663-1" tabindex="-1"></a>prueba_mediana<span class="sc">$</span>medians</span></code></pre></div>
<pre><code>##   Median  r Min Max Q25 Q75
## a      2 40   1   5   1   3
## b      4 40   1   5   3   4</code></pre>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb665-1" tabindex="-1"></a>prueba_mediana<span class="sc">$</span>comparison</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb667-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb667-1" tabindex="-1"></a>prueba_mediana<span class="sc">$</span>groups</span></code></pre></div>
<pre><code>##   datos_prueba_mediana$concepto groups
## b                             4      a
## a                             2      b</code></pre>
<p>Se puede pedir todo de una vez:</p>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb669-1" tabindex="-1"></a>prueba_mediana</span></code></pre></div>
<pre><code>## $statistics
##      Chisq Df      p.chisq Median
##   13.33333  1 0.0002607296      3
## 
## $parameters
##     test                       name.t ntr alpha
##   Median datos_prueba_mediana$docente   2  0.05
## 
## $medians
##   Median  r Min Max Q25 Q75
## a      2 40   1   5   1   3
## b      4 40   1   5   3   4
## 
## $comparison
## NULL
## 
## $groups
##   datos_prueba_mediana$concepto groups
## b                             4      a
## a                             2      b
## 
## attr(,&quot;class&quot;)
## [1] &quot;group&quot;</code></pre>
<p>El valor <span class="math inline">\(p\)</span> conduce a rechazar la hipótesis nula.</p>
</div>
<div id="prueba-de-wilcoxon" class="section level3 hasAnchor" number="13.1.4">
<h3><span class="header-section-number">13.1.4</span> Prueba de Wilcoxon<a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-wilcoxon" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sea como ejemplo, el caso de la comparación entre los puntajes de un test estandarizado entre los grupos experimental y control, cada uno de los cuales tiene nueve casos. Los datos ficticios son los siguientes:</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb671-1" tabindex="-1"></a>puntajes_control <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb671-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb671-2" tabindex="-1"></a>  <span class="fl">38.9</span>, <span class="fl">61.2</span>, <span class="fl">73.3</span>, <span class="fl">21.8</span>, <span class="fl">63.4</span>, <span class="fl">64.6</span>, <span class="fl">48.4</span>, <span class="fl">48.8</span>, <span class="fl">48.5</span>)</span>
<span id="cb671-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb671-3" tabindex="-1"></a></span>
<span id="cb671-4"><a href="cuando-los-supuestos-no-se-cumplen.html#cb671-4" tabindex="-1"></a>puntajes_experimental <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb671-5"><a href="cuando-los-supuestos-no-se-cumplen.html#cb671-5" tabindex="-1"></a>  <span class="fl">67.8</span>, <span class="dv">60</span>, <span class="fl">63.4</span>, <span class="dv">76</span>, <span class="fl">89.4</span>, <span class="fl">73.3</span>, <span class="fl">67.3</span>, <span class="fl">61.3</span>, <span class="fl">62.4</span>)</span></code></pre></div>
<p>Los argumentos de la prueba solicitan los dos conjuntos de datos, la lateralidad, el valor bajo la hipótesis nula, y debe indicarse que no es una prueba apareada</p>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  puntajes_control and puntajes_experimental
## W = 15, p-value = 0.02712
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>El resultado, a partir del valor <span class="math inline">\(p\)</span> que ofrece, indica que se rechaza la hipótesis nula.<br />
Si hubiésemos aplicado la prueba t, primero debe construirse la matriz de datos:</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb673-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb673-1" tabindex="-1"></a>puntajes <span class="ot">&lt;-</span> <span class="fu">c</span>(puntajes_control, puntajes_experimental)</span>
<span id="cb673-2"><a href="cuando-los-supuestos-no-se-cumplen.html#cb673-2" tabindex="-1"></a>grupo <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;control&quot;</span>, <span class="st">&quot;experimental&quot;</span>), <span class="at">each =</span> <span class="dv">9</span>)</span>
<span id="cb673-3"><a href="cuando-los-supuestos-no-se-cumplen.html#cb673-3" tabindex="-1"></a>datos_prueba_wilcoxon <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(grupo, puntajes)</span></code></pre></div>
<p>Y luego aplicar la prueba</p>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb674-1" tabindex="-1"></a><span class="fu">t.test</span>(puntajes <span class="sc">~</span> grupo, <span class="at">data =</span> datos_prueba_wilcoxon)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  puntajes by grupo
## t = -2.7842, df = 13.114, p-value = 0.01538
## alternative hypothesis: true difference in means between group control and group experimental is not equal to 0
## 95 percent confidence interval:
##  -29.981920  -3.795858
## sample estimates:
##      mean in group control mean in group experimental 
##                   52.10000                   68.98889</code></pre>
<p>El resultado conduce a la misma decisión, pero para interpretarlo debe cuidarse que los puntajes estén medidos a escala cuantitativa.</p>
</div>
<div id="muestras-apareadas-1" class="section level3 hasAnchor" number="13.1.5">
<h3><span class="header-section-number">13.1.5</span> Muestras apareadas<a href="cuando-los-supuestos-no-se-cumplen.html#muestras-apareadas-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se ilustra con un ejemplo sobre evaluaciones antes y después de una intervención sobre las condiciones de trabajo en una organización, medidas en puntaje de una prueba de satisfacción. Se quiere saber si hay evidencia para creer que después de la intervención los puntajes son mayores. En primer lugar se lee la base (datos ficticios):</p>
<!--esto no se muestra-->
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb676-1" tabindex="-1"></a><span class="fu">read.csv</span>(<span class="st">&quot;bases/archivostxt/datos_apareadas.csv&quot;</span>)</span></code></pre></div>
<pre><code>##     X antes despues
## 1   1   5.8     9.2
## 2   2   5.5     8.1
## 3   3   6.7     4.9
## 4   4   3.7     4.2
## 5   5   7.2     7.3
## 6   6   5.4    10.2
## 7   7   3.4     9.0
## 8   8   4.1     4.6
## 9   9   5.1     5.9
## 10 10   5.0     5.8
## 11 11   2.7     2.5
## 12 12   5.8     6.8
## 13 13   4.5     8.1
## 14 14   5.2    10.7
## 15 15   5.6    12.9
## 16 16   6.5     8.2
## 17 17   5.7    13.5
## 18 18   6.1     8.2
## 19 19   4.2    12.3
## 20 20   4.6    12.4</code></pre>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb678-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(despues, antes, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  despues and antes
## V = 199, p-value = 0.0002407
## alternative hypothesis: true location shift is greater than 0</code></pre>
<p>Leemos que, en una prueba unilateral derecha, el valor <span class="math inline">\(p\)</span> es menor a los niveles usuales de significación, por lo que hay evidencia para afirmar que los puntajes son mayores luego de la intervención.</p>
<p>La realización de esta prueba si la satisfacción esstuviese medida a nivel métrico y se pudiera suponer la normalidad de las distribuciones, sería por medio de una prueba t para muestras apareadas:</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="cuando-los-supuestos-no-se-cumplen.html#cb680-1" tabindex="-1"></a><span class="fu">t.test</span>(despues, antes, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  despues and antes
## t = 4.5335, df = 19, p-value = 0.0001136
## alternative hypothesis: true mean difference is greater than 0
## 95 percent confidence interval:
##  1.917623      Inf
## sample estimates:
## mean difference 
##             3.1</code></pre>
<p>Que conduce al mismo resultado, pero que solo es válida si se cumplen los supuestos paramétricos.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-Kendall1948" class="csl-entry">
Kendall, M G. 1948. <em><span class="nocase">Rank correlation methods.</span></em> Oxford, England: Griffin.
</div>
<div id="ref-siegel1957" class="csl-entry">
Siegel, Sidney. 1957. <span>“Nonparametric Statistics.”</span> <em>The American Statistician</em> 11 (3): 13–19. <a href="https://doi.org/10.1080/00031305.1957.10501091">https://doi.org/10.1080/00031305.1957.10501091</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="92">
<li id="fn92"><p>Lo que puede verificarse inicialmente observando el histograma, comparando la media y la mediana, y calculando los coeficientes de asimetría y curtosis.<a href="cuando-los-supuestos-no-se-cumplen.html#fnref92" class="footnote-back">↩︎</a></p></li>
<li id="fn93"><p>Como <span class="math inline">\(f_{ij} = \frac{f_{i}*f_{j}}{n}\)</span><a href="cuando-los-supuestos-no-se-cumplen.html#fnref93" class="footnote-back">↩︎</a></p></li>
<li id="fn94"><p>Haciendo: <span class="math inline">\(\chi^{2} = \sum_{}^{}\frac{( f_{o} - f_{o} )^{2}}{f_{e}}\)</span><a href="cuando-los-supuestos-no-se-cumplen.html#fnref94" class="footnote-back">↩︎</a></p></li>
<li id="fn95"><p>De mismo modo que sucede con las pruebas paramétricas, las hipótesis se refieren a toda la población, aunque aquí no aparezca el nombre de un parámetro reconocible, como <span class="math inline">\(\mu\)</span> o <span class="math inline">\(P\)</span>.<a href="cuando-los-supuestos-no-se-cumplen.html#fnref95" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prueba-de-hipótesis-las-aplicaciones.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tamaño-del-efecto.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jcrodriguez1989/EstadisticaParaCienciasSocialesConR/edit/master/14-capitulo13.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["EstadisticaParaCienciasSocialesConR.pdf", "EstadisticaParaCienciasSocialesConR.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
