<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Los datos estadísticos | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R</title>
  <meta name="description" content="Capítulo 1 Los datos estadísticos | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Los datos estadísticos | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/imagenes/cover.jpg" />
  
  <meta name="github-repo" content="jcrodriguez1989/EstadisticaParaCienciasSocialesConR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Los datos estadísticos | Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R" />
  
  
  <meta name="twitter:image" content="/imagenes/cover.jpg" />

<meta name="author" content="Eduardo Bologna" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="antes-de-empezar.html"/>
<link rel="next" href="distribuciones-de-frecuencia.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estadística para Ciencias Sociales con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Colaboradores</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#comit%C3%A9-editorial"><i class="fa fa-check"></i>Comité Editorial</a></li>
<li class="chapter" data-level="" data-path=""><a href="#edici%C3%B3n-en-bookdown"><i class="fa fa-check"></i>Edición en bookdown</a></li>
<li class="chapter" data-level="" data-path=""><a href="#revisi%C3%B3n-de-lenguaje-incluyente"><i class="fa fa-check"></i>Revisión de lenguaje incluyente</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#presentaci%C3%B3n"><i class="fa fa-check"></i>Presentación</a>
<ul>
<li class="chapter" data-level="" data-path="presentación.html"><a href="presentación.html"><i class="fa fa-check"></i>Recorridos posibles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#introducci%C3%B3n"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html"><i class="fa fa-check"></i>Antes de empezar</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#materiales"><i class="fa fa-check"></i>Materiales</a>
<ul>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-permanente-de-hogares"><i class="fa fa-check"></i>Encuesta Permanente de Hogares</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-nacional-de-factores-de-riesgo"><i class="fa fa-check"></i>Encuesta Nacional de Factores de Riesgo</a></li>
<li class="chapter" data-level="" data-path=""><a href="#latinobar%C3%B3metro"><i class="fa fa-check"></i>Latinobarómetro</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#encuesta-nacional-sobre-prevalencias-de-consumo-de-sustancias-psicoactivas"><i class="fa fa-check"></i>Encuesta Nacional sobre Prevalencias de Consumo de Sustancias Psicoactivas</a></li>
<li class="chapter" data-level="" data-path=""><a href="#aplicaci%C3%B3n-de-la-escala-de-bayley"><i class="fa fa-check"></i>Aplicación de la escala de Bayley</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#tercera-edad"><i class="fa fa-check"></i>Tercera edad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#herramientas"><i class="fa fa-check"></i>Herramientas</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#la-elecci%C3%B3n-de-r"><i class="fa fa-check"></i>La elección de R</a></li>
<li class="chapter" data-level="" data-path=""><a href="#instalaci%C3%B3n-de-r-y-rstudio"><i class="fa fa-check"></i>Instalación de R y RStudio</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#los-componentes-de-rstudio"><i class="fa fa-check"></i>Los componentes de RStudio</a></li>
<li class="chapter" data-level="" data-path="antes-de-empezar.html"><a href="antes-de-empezar.html#operaciones-en-el-script"><i class="fa fa-check"></i>Operaciones en el script</a></li>
<li class="chapter" data-level="" data-path=""><a href="#instalaci%C3%B3n-de-paquetes"><i class="fa fa-check"></i>Instalación de paquetes</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Estadística Descriptiva</b></span></li>
<li class="chapter" data-level="1" data-path="02-capitulo1.html"><a href="#los-datos-estad%C3%ADsticos"><i class="fa fa-check"></i><b>1</b> Los datos estadísticos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="02-capitulo1.html"><a href="#la-selecci%C3%B3n-de-la-informaci%C3%B3n-pertinente"><i class="fa fa-check"></i><b>1.1</b> La selección de la información pertinente</a></li>
<li class="chapter" data-level="1.2" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html"><i class="fa fa-check"></i><b>1.2</b> Las entidades</a></li>
<li class="chapter" data-level="1.3" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#las-variables"><i class="fa fa-check"></i><b>1.3</b> Las variables</a></li>
<li class="chapter" data-level="1.4" data-path="02-capitulo1.html"><a href="#las-categor%C3%ADas"><i class="fa fa-check"></i><b>1.4</b> Las categorías</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="02-capitulo1.html"><a href="#requisitos-de-las-categor%C3%ADas"><i class="fa fa-check"></i><b>1.4.1</b> Requisitos de las categorías</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="02-capitulo1.html"><a href="#los-s%C3%ADmbolos-num%C3%A9ricos"><i class="fa fa-check"></i><b>1.5</b> Los símbolos numéricos</a></li>
<li class="chapter" data-level="1.6" data-path="02-capitulo1.html"><a href="#la-medici%C3%B3n"><i class="fa fa-check"></i><b>1.6</b> La medición</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="02-capitulo1.html"><a href="#niveles-de-medici%C3%B3n"><i class="fa fa-check"></i><b>1.6.1</b> Niveles de medición</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="02-capitulo1.html"><a href="#resumen-de-los-niveles-de-medici%C3%B3n"><i class="fa fa-check"></i><b>1.7</b> Resumen de los niveles de medición</a></li>
<li class="chapter" data-level="1.8" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#hacerlo-en-r"><i class="fa fa-check"></i><b>1.8</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#lectura-de-la-base"><i class="fa fa-check"></i><b>1.8.1</b> Lectura de la base</a></li>
<li class="chapter" data-level="1.8.2" data-path="los-datos-estadísticos.html"><a href="los-datos-estadísticos.html#las-variables-1"><i class="fa fa-check"></i><b>1.8.2</b> Las variables</a></li>
<li class="chapter" data-level="1.8.3" data-path="02-capitulo1.html"><a href="#los-niveles-de-medici%C3%B3n-en-r"><i class="fa fa-check"></i><b>1.8.3</b> Los niveles de medición en R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html"><i class="fa fa-check"></i><b>2</b> Distribuciones de frecuencia</a>
<ul>
<li class="chapter" data-level="2.1" data-path="02-capitulo1.html"><a href="#tablas-de-distribuci%C3%B3n-de-frecuencia"><i class="fa fa-check"></i><b>2.1</b> Tablas de distribución de frecuencia</a></li>
<li class="chapter" data-level="2.2" data-path="02-capitulo1.html"><a href="#recategorizaci%C3%B3n"><i class="fa fa-check"></i><b>2.2</b> Recategorización</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="02-capitulo1.html"><a href="#variable-discreta-con-muchas-categor%C3%ADas"><i class="fa fa-check"></i><b>2.2.1</b> Variable discreta con muchas categorías</a></li>
<li class="chapter" data-level="2.2.2" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#variable-continua"><i class="fa fa-check"></i><b>2.2.2</b> Variable continua</a></li>
<li class="chapter" data-level="2.2.3" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#formas-de-recategorizar"><i class="fa fa-check"></i><b>2.2.3</b> Formas de recategorizar</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="02-capitulo1.html"><a href="#la-presentaci%C3%B3n-gr%C3%A1fica-de-los-resultados"><i class="fa fa-check"></i><b>2.3</b> La presentación gráfica de los resultados</a></li>
<li class="chapter" data-level="2.4" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#hacerlo-en-r-1"><i class="fa fa-check"></i><b>2.4</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="distribuciones-de-frecuencia.html"><a href="distribuciones-de-frecuencia.html#tablas-univariadas"><i class="fa fa-check"></i><b>2.4.1</b> Tablas univariadas</a></li>
<li class="chapter" data-level="2.4.2" data-path="02-capitulo1.html"><a href="#recategorizaci%C3%B3n-1"><i class="fa fa-check"></i><b>2.4.2</b> Recategorización</a></li>
<li class="chapter" data-level="2.4.3" data-path="02-capitulo1.html"><a href="#representaciones-gr%C3%A1ficas"><i class="fa fa-check"></i><b>2.4.3</b> Representaciones gráficas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="02-capitulo1.html"><a href="#la-expresi%C3%B3n-resumida-de-la-informaci%C3%B3n"><i class="fa fa-check"></i><b>3</b> La expresión resumida de la información</a>
<ul>
<li class="chapter" data-level="3.1" data-path="02-capitulo1.html"><a href="#medidas-de-posici%C3%B3n"><i class="fa fa-check"></i><b>3.1</b> Medidas de posición</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html"><i class="fa fa-check"></i><b>3.1.1</b> Variables nominales: proporciones</a></li>
<li class="chapter" data-level="3.1.2" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-tasas"><i class="fa fa-check"></i><b>3.1.2</b> Variables nominales: tasas</a></li>
<li class="chapter" data-level="3.1.3" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-razones"><i class="fa fa-check"></i><b>3.1.3</b> Variables nominales: razones</a></li>
<li class="chapter" data-level="3.1.4" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-nominales-el-modo"><i class="fa fa-check"></i><b>3.1.4</b> Variables nominales: el modo</a></li>
<li class="chapter" data-level="3.1.5" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#variables-ordinales-cuantiles"><i class="fa fa-check"></i><b>3.1.5</b> Variables ordinales: cuantiles</a></li>
<li class="chapter" data-level="3.1.6" data-path="02-capitulo1.html"><a href="#variables-m%C3%A9tricas-la-media-o-promedio"><i class="fa fa-check"></i><b>3.1.6</b> Variables métricas: la media o promedio</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="02-capitulo1.html"><a href="#la-forma-de-la-distribuci%C3%B3n"><i class="fa fa-check"></i><b>3.2</b> La forma de la distribución</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="02-capitulo1.html"><a href="#asimetr%C3%ADa"><i class="fa fa-check"></i><b>3.2.1</b> Asimetría</a></li>
<li class="chapter" data-level="3.2.2" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#curtosis"><i class="fa fa-check"></i><b>3.2.2</b> Curtosis</a></li>
<li class="chapter" data-level="3.2.3" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#box-plots"><i class="fa fa-check"></i><b>3.2.3</b> Box-plots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="02-capitulo1.html"><a href="#medidas-de-dispersi%C3%B3n"><i class="fa fa-check"></i><b>3.3</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#recorrido"><i class="fa fa-check"></i><b>3.3.1</b> Recorrido</a></li>
<li class="chapter" data-level="3.3.2" data-path="02-capitulo1.html"><a href="#amplitud-intercuart%C3%ADlica"><i class="fa fa-check"></i><b>3.3.2</b> Amplitud intercuartílica</a></li>
<li class="chapter" data-level="3.3.3" data-path="02-capitulo1.html"><a href="#medidas-de-dispersi%C3%B3n-basadas-en-la-media"><i class="fa fa-check"></i><b>3.3.3</b> Medidas de dispersión basadas en la media</a></li>
<li class="chapter" data-level="3.3.4" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#varianza"><i class="fa fa-check"></i><b>3.3.4</b> Varianza</a></li>
<li class="chapter" data-level="3.3.5" data-path="02-capitulo1.html"><a href="#desviaci%C3%B3n-est%C3%A1ndar"><i class="fa fa-check"></i><b>3.3.5</b> Desviación estándar</a></li>
<li class="chapter" data-level="3.3.6" data-path="02-capitulo1.html"><a href="#coeficiente-de-variaci%C3%B3n"><i class="fa fa-check"></i><b>3.3.6</b> Coeficiente de variación</a></li>
<li class="chapter" data-level="3.3.7" data-path="02-capitulo1.html"><a href="#box-plots-y-dispersi%C3%B3n"><i class="fa fa-check"></i><b>3.3.7</b> Box-plots y dispersión</a></li>
<li class="chapter" data-level="3.3.8" data-path="02-capitulo1.html"><a href="#medida-de-la-dispersi%C3%B3n-cuando-no-hay-distancias"><i class="fa fa-check"></i><b>3.3.8</b> Medida de la dispersión cuando no hay distancias</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="02-capitulo1.html"><a href="#el-individuo-en-relaci%C3%B3n-a-su-grupo"><i class="fa fa-check"></i><b>3.4</b> El individuo en relación a su grupo</a></li>
<li class="chapter" data-level="3.5" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#resumen-de-medidas-descriptivas"><i class="fa fa-check"></i><b>3.5</b> Resumen de medidas descriptivas</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="02-capitulo1.html"><a href="#medidas-de-posici%C3%B3n-1"><i class="fa fa-check"></i><b>3.5.1</b> Medidas de posición</a></li>
<li class="chapter" data-level="3.5.2" data-path="02-capitulo1.html"><a href="#medidas-de-dispersi%C3%B3n-1"><i class="fa fa-check"></i><b>3.5.2</b> Medidas de dispersión</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="la-expresión-resumida-de-la-información.html"><a href="la-expresión-resumida-de-la-información.html#hacerlo-en-r-2"><i class="fa fa-check"></i><b>3.6</b> Hacerlo en R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="02-capitulo1.html"><a href="#relaci%C3%B3n-entre-variables-los-fundamentos"><i class="fa fa-check"></i><b>4</b> Relación entre variables: los fundamentos</a>
<ul>
<li class="chapter" data-level="4.1" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html"><i class="fa fa-check"></i><b>4.1</b> Tablas de contingencia</a></li>
<li class="chapter" data-level="4.2" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#frecuencias-relativas"><i class="fa fa-check"></i><b>4.2</b> Frecuencias relativas</a></li>
<li class="chapter" data-level="4.3" data-path="02-capitulo1.html"><a href="#una-clasificaci%C3%B3n-en-referencia-al-tiempo"><i class="fa fa-check"></i><b>4.3</b> Una clasificación en referencia al tiempo</a></li>
<li class="chapter" data-level="4.4" data-path="02-capitulo1.html"><a href="#la-direcci%C3%B3n-de-la-relaci%C3%B3n"><i class="fa fa-check"></i><b>4.4</b> La dirección de la relación</a></li>
<li class="chapter" data-level="4.5" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#concepto-de-riesgo-relativo"><i class="fa fa-check"></i><b>4.5</b> Concepto de riesgo relativo</a></li>
<li class="chapter" data-level="4.6" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#la-intensidad"><i class="fa fa-check"></i><b>4.6</b> La intensidad</a></li>
<li class="chapter" data-level="4.7" data-path="02-capitulo1.html"><a href="#el-concepto-de-independencia-estad%C3%ADstica"><i class="fa fa-check"></i><b>4.7</b> El concepto de independencia estadística</a></li>
<li class="chapter" data-level="4.8" data-path="relación-entre-variables-los-fundamentos.html"><a href="relación-entre-variables-los-fundamentos.html#hacerlo-en-r-3"><i class="fa fa-check"></i><b>4.8</b> Hacerlo en R</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="02-capitulo1.html"><a href="#relaci%C3%B3n-entre-variables-el-an%C3%A1lisis"><i class="fa fa-check"></i><b>5</b> Relación entre variables: el análisis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="02-capitulo1.html"><a href="#relaciones-entre-variables-vs.-comparaci%C3%B3n-de-grupos"><i class="fa fa-check"></i><b>5.1</b> Relaciones entre variables vs. comparación de grupos</a></li>
<li class="chapter" data-level="5.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html"><i class="fa fa-check"></i><b>5.2</b> Variables nominales</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="02-capitulo1.html"><a href="#coeficientes-de-asociaci%C3%B3n-para-variables-nominales"><i class="fa fa-check"></i><b>5.2.1</b> Coeficientes de asociación para variables nominales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#variables-de-nivel-ordinal"><i class="fa fa-check"></i><b>5.3</b> Variables de nivel ordinal</a></li>
<li class="chapter" data-level="5.4" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#nivel-intervalar-o-proporcional"><i class="fa fa-check"></i><b>5.4</b> Nivel intervalar o proporcional</a></li>
<li class="chapter" data-level="5.5" data-path="02-capitulo1.html"><a href="#dicotom%C3%ADas-reales-y-artificiales"><i class="fa fa-check"></i><b>5.5</b> Dicotomías reales y artificiales</a></li>
<li class="chapter" data-level="5.6" data-path="02-capitulo1.html"><a href="#niveles-de-medici%C3%B3n-combinados"><i class="fa fa-check"></i><b>5.6</b> Niveles de medición combinados</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="02-capitulo1.html"><a href="#una-variable-dicot%C3%B3mica-real-y-una-proporcional"><i class="fa fa-check"></i><b>5.6.1</b> Una variable dicotómica real y una proporcional</a></li>
<li class="chapter" data-level="5.6.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#una-variable-continua-dicotomizada-y-una-proporcional"><i class="fa fa-check"></i><b>5.6.2</b> Una variable continua dicotomizada y una proporcional</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="02-capitulo1.html"><a href="#resumen-de-coeficientes-de-asociaci%C3%B3n"><i class="fa fa-check"></i><b>5.7</b> Resumen de coeficientes de asociación</a></li>
<li class="chapter" data-level="5.8" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#matriz-de-correlaciones"><i class="fa fa-check"></i><b>5.8</b> Matriz de correlaciones</a></li>
<li class="chapter" data-level="5.9" data-path="02-capitulo1.html"><a href="#la-forma-de-la-relaci%C3%B3n"><i class="fa fa-check"></i><b>5.9</b> La forma de la relación</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#ordenada-al-origen"><i class="fa fa-check"></i><b>5.9.1</b> Ordenada al origen</a></li>
<li class="chapter" data-level="5.9.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#pendiente"><i class="fa fa-check"></i><b>5.9.2</b> Pendiente</a></li>
<li class="chapter" data-level="5.9.3" data-path="02-capitulo1.html"><a href="#obtenci%C3%B3n-de-la-recta-de-regresi%C3%B3n"><i class="fa fa-check"></i><b>5.9.3</b> Obtención de la recta de regresión</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="02-capitulo1.html"><a href="#la-visualizaci%C3%B3n-de-los-datos"><i class="fa fa-check"></i><b>5.10</b> La visualización de los datos</a></li>
<li class="chapter" data-level="5.11" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#hacerlo-en-r-4"><i class="fa fa-check"></i><b>5.11</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#distancia-chi2"><i class="fa fa-check"></i><b>5.11.1</b> Distancia <span class="math inline">\(\chi^{2}\)</span></a></li>
<li class="chapter" data-level="5.11.2" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#coeficientes"><i class="fa fa-check"></i><b>5.11.2</b> Coeficientes</a></li>
<li class="chapter" data-level="5.11.3" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#modelo-lineal"><i class="fa fa-check"></i><b>5.11.3</b> Modelo lineal</a></li>
<li class="chapter" data-level="5.11.4" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#cuarteto-de-anscombe"><i class="fa fa-check"></i><b>5.11.4</b> Cuarteto de Anscombe</a></li>
<li class="chapter" data-level="5.11.5" data-path="relación-entre-variables-el-análisis.html"><a href="relación-entre-variables-el-análisis.html#datasaurus"><i class="fa fa-check"></i><b>5.11.5</b> Datasaurus</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II De la descripción a la inferencia</b></span></li>
<li class="chapter" data-level="6" data-path="02-capitulo1.html"><a href="#obtenci%C3%B3n-de-la-muestra"><i class="fa fa-check"></i><b>6</b> Obtención de la muestra</a>
<ul>
<li class="chapter" data-level="6.1" data-path="02-capitulo1.html"><a href="#poblaci%C3%B3n"><i class="fa fa-check"></i><b>6.1</b> Población</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html"><i class="fa fa-check"></i><b>6.1.1</b> Muestra</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="02-capitulo1.html"><a href="#muestreos-probabil%C3%ADsticos"><i class="fa fa-check"></i><b>6.2</b> Muestreos probabilísticos</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-irrestricto-aleatorio-o-aleatorio-simple"><i class="fa fa-check"></i><b>6.2.1</b> Muestreo irrestricto aleatorio o aleatorio simple</a></li>
<li class="chapter" data-level="6.2.2" data-path="02-capitulo1.html"><a href="#muestreo-sistem%C3%A1tico"><i class="fa fa-check"></i><b>6.2.2</b> Muestreo sistemático</a></li>
<li class="chapter" data-level="6.2.3" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-estratificado"><i class="fa fa-check"></i><b>6.2.3</b> Muestreo estratificado</a></li>
<li class="chapter" data-level="6.2.4" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-por-conglomerados"><i class="fa fa-check"></i><b>6.2.4</b> Muestreo por conglomerados</a></li>
<li class="chapter" data-level="6.2.5" data-path="02-capitulo1.html"><a href="#m%C3%A9todo-de-kish"><i class="fa fa-check"></i><b>6.2.5</b> Método de Kish</a></li>
<li class="chapter" data-level="6.2.6" data-path="02-capitulo1.html"><a href="#uso-combinado-de-t%C3%A9cnicas-de-muestreo"><i class="fa fa-check"></i><b>6.2.6</b> Uso combinado de técnicas de muestreo</a></li>
<li class="chapter" data-level="6.2.7" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-de-panel"><i class="fa fa-check"></i><b>6.2.7</b> Muestreo de panel</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="02-capitulo1.html"><a href="#muestreos-no-probabil%C3%ADsticos"><i class="fa fa-check"></i><b>6.3</b> Muestreos no probabilísticos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-por-cuotas"><i class="fa fa-check"></i><b>6.3.1</b> Muestreo por cuotas</a></li>
<li class="chapter" data-level="6.3.2" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-de-juicio-o-intencional"><i class="fa fa-check"></i><b>6.3.2</b> Muestreo de juicio o intencional</a></li>
<li class="chapter" data-level="6.3.3" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-autoelegido"><i class="fa fa-check"></i><b>6.3.3</b> Muestreo autoelegido</a></li>
<li class="chapter" data-level="6.3.4" data-path="02-capitulo1.html"><a href="#muestreo-accidental-o-seg%C3%BAn-disponibilidad"><i class="fa fa-check"></i><b>6.3.4</b> Muestreo accidental o según disponibilidad</a></li>
<li class="chapter" data-level="6.3.5" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#muestreo-bola-de-nieve"><i class="fa fa-check"></i><b>6.3.5</b> Muestreo bola de nieve</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#hacerlo-en-r-5"><i class="fa fa-check"></i><b>6.4</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#aleatorio-simple"><i class="fa fa-check"></i><b>6.4.1</b> Aleatorio simple</a></li>
<li class="chapter" data-level="6.4.2" data-path="obtención-de-la-muestra.html"><a href="obtención-de-la-muestra.html#estratificado"><i class="fa fa-check"></i><b>6.4.2</b> Estratificado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html"><i class="fa fa-check"></i><b>7</b> Probabilidad: los fundamentos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#formas-para-asignar-probabilidades"><i class="fa fa-check"></i><b>7.1</b> Formas para asignar probabilidades</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="02-capitulo1.html"><a href="#asignaci%C3%B3n-a-priori"><i class="fa fa-check"></i><b>7.1.1</b> Asignación a priori</a></li>
<li class="chapter" data-level="7.1.2" data-path="02-capitulo1.html"><a href="#asignaci%C3%B3n-a-posteriori"><i class="fa fa-check"></i><b>7.1.2</b> Asignación a posteriori</a></li>
<li class="chapter" data-level="7.1.3" data-path="02-capitulo1.html"><a href="#la-relaci%C3%B3n-entre-asignaci%C3%B3n-a-priori-y-a-posteriori"><i class="fa fa-check"></i><b>7.1.3</b> La relación entre asignación a priori y a posteriori</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#operando-con-probabilidades"><i class="fa fa-check"></i><b>7.2</b> Operando con probabilidades</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#con-probabilidades-frecuenciales"><i class="fa fa-check"></i><b>7.2.1</b> Con probabilidades frecuenciales</a></li>
<li class="chapter" data-level="7.2.2" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#con-probabilidades-a-priori"><i class="fa fa-check"></i><b>7.2.2</b> Con probabilidades a priori</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#el-teorema-de-bayes"><i class="fa fa-check"></i><b>7.3</b> El teorema de Bayes</a></li>
<li class="chapter" data-level="7.4" data-path="probabilidad-los-fundamentos.html"><a href="probabilidad-los-fundamentos.html#variables-aleatorias"><i class="fa fa-check"></i><b>7.4</b> Variables aleatorias</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html"><i class="fa fa-check"></i><b>8</b> Probabilidad: los modelos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="02-capitulo1.html"><a href="#concepto-de-modelizaci%C3%B3n"><i class="fa fa-check"></i><b>8.1</b> Concepto de modelización</a></li>
<li class="chapter" data-level="8.2" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-binomial"><i class="fa fa-check"></i><b>8.2</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#esperanza-y-varianza"><i class="fa fa-check"></i><b>8.2.1</b> Esperanza y varianza</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-normal"><i class="fa fa-check"></i><b>8.3</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#cuantiles"><i class="fa fa-check"></i><b>8.3.1</b> Cuantiles</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#la-idea-de-grados-de-libertad"><i class="fa fa-check"></i><b>8.4</b> La idea de grados de libertad</a></li>
<li class="chapter" data-level="8.5" data-path="02-capitulo1.html"><a href="#la-distribuci%C3%B3n-ji-cuadrado-chi2"><i class="fa fa-check"></i><b>8.5</b> La distribución ji cuadrado (<span class="math inline">\(\chi^{2}\)</span>)</a></li>
<li class="chapter" data-level="8.6" data-path="02-capitulo1.html"><a href="#la-distribuci%C3%B3n-t-de-student"><i class="fa fa-check"></i><b>8.6</b> La distribución t de Student</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="02-capitulo1.html"><a href="#la-distribuci%C3%B3n-f"><i class="fa fa-check"></i><b>8.6.1</b> La distribución F</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#hacerlo-en-r-6"><i class="fa fa-check"></i><b>8.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#probabilidades-exactas"><i class="fa fa-check"></i><b>8.7.1</b> Probabilidades exactas</a></li>
<li class="chapter" data-level="8.7.2" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#probabilidades-acumuladas"><i class="fa fa-check"></i><b>8.7.2</b> Probabilidades acumuladas</a></li>
<li class="chapter" data-level="8.7.3" data-path="probabilidad-los-modelos.html"><a href="probabilidad-los-modelos.html#cuantiles-1"><i class="fa fa-check"></i><b>8.7.3</b> Cuantiles</a></li>
<li class="chapter" data-level="8.7.4" data-path="02-capitulo1.html"><a href="#%C3%A1reas-centrales"><i class="fa fa-check"></i><b>8.7.4</b> Áreas centrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html"><i class="fa fa-check"></i><b>9</b> Distribuciones en el muestreo</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#variabilidad-muestral"><i class="fa fa-check"></i><b>9.1</b> Variabilidad muestral</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#dos-aspectos-importantes-para-recordar-cuando-se-usan-muestras"><i class="fa fa-check"></i><b>9.1.1</b> Dos aspectos importantes para recordar cuando se usan muestras:</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="02-capitulo1.html"><a href="#caracter%C3%ADsticas-de-los-estimadores"><i class="fa fa-check"></i><b>9.2</b> Características de los estimadores</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#insesgabilidad"><i class="fa fa-check"></i><b>9.2.1</b> Insesgabilidad</a></li>
<li class="chapter" data-level="9.2.2" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#consistencia"><i class="fa fa-check"></i><b>9.2.2</b> Consistencia</a></li>
<li class="chapter" data-level="9.2.3" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#eficiencia"><i class="fa fa-check"></i><b>9.2.3</b> Eficiencia</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#distribuciones-de-probabilidad-de-los-estimadores"><i class="fa fa-check"></i><b>9.3</b> Distribuciones de probabilidad de los estimadores</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="02-capitulo1.html"><a href="#primera-aproximaci%C3%B3n"><i class="fa fa-check"></i><b>9.3.1</b> Primera aproximación</a></li>
<li class="chapter" data-level="9.3.2" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-de-la-media-muestral"><i class="fa fa-check"></i><b>9.3.2</b> Distribución de la media muestral</a></li>
<li class="chapter" data-level="9.3.3" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-de-la-proporci%C3%B3n-muestral"><i class="fa fa-check"></i><b>9.3.3</b> Distribución de la proporción muestral</a></li>
<li class="chapter" data-level="9.3.4" data-path="02-capitulo1.html"><a href="#muestras-peque%C3%B1as"><i class="fa fa-check"></i><b>9.3.4</b> Muestras pequeñas</a></li>
<li class="chapter" data-level="9.3.5" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-de-la-varianza"><i class="fa fa-check"></i><b>9.3.5</b> Distribución de la varianza</a></li>
<li class="chapter" data-level="9.3.6" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#muestreo-desde-dos-poblaciones"><i class="fa fa-check"></i><b>9.3.6</b> Muestreo desde dos poblaciones</a></li>
<li class="chapter" data-level="9.3.7" data-path="02-capitulo1.html"><a href="#distribuci%C3%B3n-del-cociente-de-varianzas"><i class="fa fa-check"></i><b>9.3.7</b> Distribución del cociente de varianzas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="02-capitulo1.html"><a href="#resumen-de-la-relaci%C3%B3n-entre-estimadores-y-par%C3%A1metros"><i class="fa fa-check"></i><b>9.4</b> Resumen de la relación entre estimadores y parámetros</a></li>
<li class="chapter" data-level="9.5" data-path="distribuciones-en-el-muestreo.html"><a href="distribuciones-en-el-muestreo.html#hacerlo-en-r-7"><i class="fa fa-check"></i><b>9.5</b> Hacerlo en R</a></li>
</ul></li>
<li class="part"><span><b>III Estadística inferencial</b></span></li>
<li class="chapter" data-level="10" data-path="02-capitulo1.html"><a href="#estimaci%C3%B3n-por-intervalo"><i class="fa fa-check"></i><b>10</b> Estimación por intervalo</a>
<ul>
<li class="chapter" data-level="10.1" data-path="02-capitulo1.html"><a href="#estimaci%C3%B3n-puntual"><i class="fa fa-check"></i><b>10.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="10.2" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html"><i class="fa fa-check"></i><b>10.2</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="10.3" data-path="02-capitulo1.html"><a href="#estimaci%C3%B3n-de-la-media"><i class="fa fa-check"></i><b>10.3</b> Estimación de la media</a></li>
<li class="chapter" data-level="10.4" data-path="02-capitulo1.html"><a href="#estimaci%C3%B3n-de-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.4</b> Estimación de la proporción</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-clopper-pearson"><i class="fa fa-check"></i><b>10.4.1</b> Intervalo de Clopper-Pearson</a></li>
<li class="chapter" data-level="10.4.2" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-wald"><i class="fa fa-check"></i><b>10.4.2</b> Intervalo de Wald</a></li>
<li class="chapter" data-level="10.4.3" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-de-wilson"><i class="fa fa-check"></i><b>10.4.3</b> Intervalo de Wilson</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#la-calidad-de-las-estimaciones-por-intervalo"><i class="fa fa-check"></i><b>10.5</b> La calidad de las estimaciones por intervalo</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="02-capitulo1.html"><a href="#el-error-de-estimaci%C3%B3n-en-la-media"><i class="fa fa-check"></i><b>10.5.1</b> El error de estimación en la media</a></li>
<li class="chapter" data-level="10.5.2" data-path="02-capitulo1.html"><a href="#el-error-de-estimaci%C3%B3n-en-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.5.2</b> El error de estimación en la proporción</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#probabilidad-de-cobertura"><i class="fa fa-check"></i><b>10.6</b> Probabilidad de cobertura</a></li>
<li class="chapter" data-level="10.7" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#hacerlo-en-r-8"><i class="fa fa-check"></i><b>10.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#intervalo-para-la-media"><i class="fa fa-check"></i><b>10.7.1</b> Intervalo para la media</a></li>
<li class="chapter" data-level="10.7.2" data-path="02-capitulo1.html"><a href="#intervalo-para-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>10.7.2</b> Intervalo para la proporción</a></li>
<li class="chapter" data-level="10.7.3" data-path="estimación-por-intervalo.html"><a href="estimación-por-intervalo.html#cobertura"><i class="fa fa-check"></i><b>10.7.3</b> Cobertura</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="02-capitulo1.html"><a href="#prueba-de-hip%C3%B3tesis-la-l%C3%B3gica"><i class="fa fa-check"></i><b>11</b> Prueba de hipótesis: la lógica</a>
<ul>
<li class="chapter" data-level="11.1" data-path="02-capitulo1.html"><a href="#el-razonamiento-de-la-prueba-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>11.1</b> El razonamiento de la prueba de hipótesis</a></li>
<li class="chapter" data-level="11.2" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html"><i class="fa fa-check"></i><b>11.2</b> Prueba sobre la media</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="02-capitulo1.html"><a href="#la-toma-de-decisi%C3%B3n"><i class="fa fa-check"></i><b>11.2.1</b> La toma de decisión</a></li>
<li class="chapter" data-level="11.2.2" data-path="02-capitulo1.html"><a href="#los-puntos-cr%C3%ADticos-en-t%C3%A9rminos-del-estimador"><i class="fa fa-check"></i><b>11.2.2</b> Los puntos críticos en términos del estimador</a></li>
<li class="chapter" data-level="11.2.3" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#pruebas-unilaterales"><i class="fa fa-check"></i><b>11.2.3</b> Pruebas unilaterales</a></li>
<li class="chapter" data-level="11.2.4" data-path="02-capitulo1.html"><a href="#otros-ejemplos-de-prueba-de-hip%C3%B3tesis-sobre-la-media"><i class="fa fa-check"></i><b>11.2.4</b> Otros ejemplos de prueba de hipótesis sobre la media</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="02-capitulo1.html"><a href="#prueba-sobre-la-proporci%C3%B3n"><i class="fa fa-check"></i><b>11.3</b> Prueba sobre la proporción</a></li>
<li class="chapter" data-level="11.4" data-path="02-capitulo1.html"><a href="#tipos-de-error-en-las-pruebas-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>11.4</b> Tipos de error en las pruebas de hipótesis</a></li>
<li class="chapter" data-level="11.5" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#etii-mu-alpha-y-n"><i class="fa fa-check"></i><b>11.5</b> <em>ETII:</em> <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(n\)</span></a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#curva-de-potencia"><i class="fa fa-check"></i><b>11.5.1</b> Curva de potencia</a></li>
<li class="chapter" data-level="11.5.2" data-path="02-capitulo1.html"><a href="#significaci%C3%B3n-estad%C3%ADstica-y-valor-p"><i class="fa fa-check"></i><b>11.5.2</b> Significación estadística y valor <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="02-capitulo1.html"><a href="#muestras-peque%C3%B1as-y-pruebas-t"><i class="fa fa-check"></i><b>11.6</b> Muestras pequeñas y pruebas <span class="math inline">\(t\)</span></a></li>
<li class="chapter" data-level="11.7" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#hacerlo-en-r-9"><i class="fa fa-check"></i><b>11.7</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#prueba-sobre-la-media-1"><i class="fa fa-check"></i><b>11.7.1</b> Prueba sobre la media</a></li>
<li class="chapter" data-level="11.7.2" data-path="02-capitulo1.html"><a href="#prueba-sobre-la-proporci%C3%B3n-1"><i class="fa fa-check"></i><b>11.7.2</b> Prueba sobre la proporción</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="prueba-de-hipótesis-la-lógica.html"><a href="prueba-de-hipótesis-la-lógica.html#resumen-de-pruebas-sobre-una-muestra"><i class="fa fa-check"></i><b>11.8</b> Resumen de pruebas sobre una muestra</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="02-capitulo1.html"><a href="#prueba-de-hip%C3%B3tesis-las-aplicaciones"><i class="fa fa-check"></i><b>12</b> Prueba de hipótesis: las aplicaciones</a>
<ul>
<li class="chapter" data-level="12.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html"><i class="fa fa-check"></i><b>12.1</b> Muestras independientes</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#prueba-de-diferencia-de-medias"><i class="fa fa-check"></i><b>12.1.1</b> Prueba de diferencia de medias</a></li>
<li class="chapter" data-level="12.1.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#muestras-apareadas"><i class="fa fa-check"></i><b>12.1.2</b> Muestras apareadas</a></li>
<li class="chapter" data-level="12.1.3" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#coeficiente-r-de-pearson"><i class="fa fa-check"></i><b>12.1.3</b> Coeficiente r de Pearson</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#hacerlo-en-r-10"><i class="fa fa-check"></i><b>12.2</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#ejemplo-1."><i class="fa fa-check"></i><b>12.2.1</b> Ejemplo 1.</a></li>
<li class="chapter" data-level="12.2.2" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#ejemplo-2."><i class="fa fa-check"></i><b>12.2.2</b> Ejemplo 2.</a></li>
<li class="chapter" data-level="12.2.3" data-path="02-capitulo1.html"><a href="#aplicaci%C3%B3n-a-los-datos-de-poblaci%C3%B3n-adulta-mayor"><i class="fa fa-check"></i><b>12.2.3</b> Aplicación a los datos de Población Adulta Mayor</a></li>
<li class="chapter" data-level="12.2.4" data-path="prueba-de-hipótesis-las-aplicaciones.html"><a href="prueba-de-hipótesis-las-aplicaciones.html#prueba-apareada"><i class="fa fa-check"></i><b>12.2.4</b> Prueba apareada</a></li>
<li class="chapter" data-level="12.2.5" data-path="02-capitulo1.html"><a href="#coeficiente-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>12.2.5</b> Coeficiente de correlación</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html"><i class="fa fa-check"></i><b>13</b> Cuando los supuestos no se cumplen</a>
<ul>
<li class="chapter" data-level="13.0.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#las-pruebas-ji-cuadrado-o-chi-cuadrado"><i class="fa fa-check"></i><b>13.0.1</b> Las pruebas ji cuadrado (o chi cuadrado)</a></li>
<li class="chapter" data-level="13.0.2" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#coeficiente-r_s-de-spearman"><i class="fa fa-check"></i><b>13.0.2</b> Coeficiente <span class="math inline">\(r_s\)</span> de Spearman</a></li>
<li class="chapter" data-level="13.0.3" data-path="02-capitulo1.html"><a href="#alternativas-no-param%C3%A9tricas-a-las-pruebas-t"><i class="fa fa-check"></i><b>13.0.3</b> Alternativas no paramétricas a las pruebas t</a></li>
<li class="chapter" data-level="13.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#hacerlo-en-r-11"><i class="fa fa-check"></i><b>13.1</b> Hacerlo en R</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-1"><i class="fa fa-check"></i><b>13.1.1</b> Ejemplo 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#ejemplo-2"><i class="fa fa-check"></i><b>13.1.2</b> Ejemplo 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-la-mediana-1"><i class="fa fa-check"></i><b>13.1.3</b> Prueba de la mediana</a></li>
<li class="chapter" data-level="13.1.4" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#prueba-de-wilcoxon"><i class="fa fa-check"></i><b>13.1.4</b> Prueba de Wilcoxon</a></li>
<li class="chapter" data-level="13.1.5" data-path="cuando-los-supuestos-no-se-cumplen.html"><a href="cuando-los-supuestos-no-se-cumplen.html#muestras-apareadas-1"><i class="fa fa-check"></i><b>13.1.5</b> Muestras apareadas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="02-capitulo1.html"><a href="#tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>14</b> Tamaño del efecto</a>
<ul>
<li class="chapter" data-level="14.1" data-path="02-capitulo1.html"><a href="#significaci%C3%B3n-estad%C3%ADstica-y-significaci%C3%B3n-pr%C3%A1ctica"><i class="fa fa-check"></i><b>14.1</b> Significación estadística y significación práctica</a></li>
<li class="chapter" data-level="14.2" data-path="02-capitulo1.html"><a href="#medidas-de-tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>14.2</b> Medidas de tamaño del efecto</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html"><i class="fa fa-check"></i><b>14.2.1</b> Prueba t para diferencia de medias</a></li>
<li class="chapter" data-level="14.2.2" data-path="02-capitulo1.html"><a href="#an%C3%A1lisis-de-la-varianza"><i class="fa fa-check"></i><b>14.2.2</b> Análisis de la varianza</a></li>
<li class="chapter" data-level="14.2.3" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#correlaciones"><i class="fa fa-check"></i><b>14.2.3</b> Correlaciones</a></li>
<li class="chapter" data-level="14.2.4" data-path="02-capitulo1.html"><a href="#regresi%C3%B3n-lineal"><i class="fa fa-check"></i><b>14.2.4</b> Regresión lineal</a></li>
<li class="chapter" data-level="14.2.5" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#pruebas-ji-cuadrado"><i class="fa fa-check"></i><b>14.2.5</b> Pruebas ji cuadrado</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="02-capitulo1.html"><a href="#an%C3%A1lisis-de-la-potencia"><i class="fa fa-check"></i><b>14.3</b> Análisis de la potencia</a></li>
<li class="chapter" data-level="14.4" data-path="tamaño-del-efecto.html"><a href="tamaño-del-efecto.html#hacerlo-en-r-12"><i class="fa fa-check"></i><b>14.4</b> Hacerlo en R</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Generado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Un Recorrido por los Métodos Cuantitativos en Ciencias Sociales a bordo de R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="los-datos-estadísticos" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Los datos estadísticos<a href="#los-datos-estad%C3%ADsticos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se desarrollan procedimientos para presentar la información de manera accesible para que pueda ser analizada y luego interpretada. Para poder extraer significado de los datos recogidos es necesario primero dedicar un esfuerzo a organizarlos, a presentarlos de manera comprensible, es una una operación previa a la aplicación de las técnicas de análisis que se verán más adelante.</p>
<p>La ciencia se interesa por la producción de conocimiento validado, uno de cuyos requisitos es que pueda ser comunicado de manera inequívoca, que se discutan las conclusiones a que llegan y los métodos que usan diferentes equipos de investigación, así como que los resultados que se publican puedan ser reproducidos por otros grupos de investogación. Esto implica la necesidad de usar un lenguaje que permita el intercambio al interior de las comunidades científicas y que dependa, en el menor grado posible, de las impresiones subjetivas o de las interpretaciones, o del modo en que cada integrante personalmente conciba los conceptos; en el intento de lograr un vocabulario tan unívoco como sea posible. Un modo de alcanzar esta comunicabilidad de las ideas, de los métodos y de los resultados, es definir, de la manera más precisa posible, los elementos acerca de los que se habla.<br />
Alguna vez hemos dado con expresiones como “esta persona es más inteligente que aquella”. ¿Qué se quiere decir exactamente con eso?, la afirmación podría provenir de algún evento en que se vio a esa persona actuando de manera que llamaríamos inteligente, aunque esto también puede confundirse con astucia: no es infrecuente usar el adjetivo inteligente para alguien a quien le resulta fácil engañar a otros y usar esos engaños para su beneficio; y, a la inversa, sería poco inteligente quien se deja engañar con facilidad. También suele decirse que alguien es inteligente porque obtiene buenos resultados en sus estudios. Esto es parte de la imprecisión en la definición de un concepto. Si se dispone de una definición de inteligencia, se puede saber cuándo aplicar esa idea a alguien, cuándo una conducta es inteligente, inclusive, cómo ayudar a desarrollar la inteligencia. Si se puede definir el concepto con el que se trabaja, se pueden indicar ciertas operaciones a realizar para evaluarlo y así conocer cuál es el nivel de inteligencia de una persona en particular.<br />
Luego de definir el concepto con el que se trabaja, se requiere diseñar un instrumento que refleje esa definición y finalmente aplicar este instrumento a las personas que serán evaluadas. Al hacer esto último se obtiene un resultado que, si se expresa de manera cuantitativa, permite hacer comparaciones del aspecto que representa ese concepto, entre personas, entre grupos, etc.<br />
¿Pueden compararse personas? La respuesta es no, porque cada persona tiene una infinidad de aspectos que la caracterizan y la hacen única. Por el contrario lo que sí pueden compararse son características claramente definidas de las personas. Del mismo modo no se pueden comparar escuelas, ni hogares, ni países si no se especifica en qué aspecto se realiza la comparación. O dicho de otro modo, cuál es la característica que se compara, y cómo se mide esa característica.<br />
Podemos decir que una persona tiene más escolarización formal que otra, indicando con eso que ha aprobado más años de la escuela o de la universidad. Podemos decir que un hogar es diferente a otro si uno se compone de una pareja sola y el otro incluye una hija y dos hijos. Un país puede tener más habitantes, un régimen político diferente, o mayor libertad de expresión que otro. En todos los casos especificamos una característica (un rasgo o un estado), sobre la base del cual hacemos la comparación.</p>
<div id="la-selección-de-la-información-pertinente" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> La selección de la información pertinente<a href="#la-selecci%C3%B3n-de-la-informaci%C3%B3n-pertinente" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cuando se ha decidido quienes son los entes de la observación; es decir, una vez que se sabe a quiénes se observará, deben elegirse ciertas características que serán observadas<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. Cada unidad que resulta de interés para la investigación tiene un conjunto muy grande de características observables y siempre se realiza una selección de esas características. Se trata de un recorte que permite comprender mejor ciertos aspectos, dejando de lado otros. La información que seleccionamos para observar se denomina pertinente para la investigación. Esta información puede provenir de diferentes fuentes, de manera general se distinguen dos tipos de fuentes: relevamientos y registros.<br />
Los <strong>relevamientos</strong> pueden ser censos, encuestas u observaciones experimentales, y recogen información en un momento dado, en un corte transversal; una especie de foto que toma nota de un conjunto de características de las entidades, en el instante que se realiza: un día, una semana, el momento antes y después, etc. Por ejemplo, un censo se hace en uno o dos días, una vez cada diez años y, casa por casa, se recoge información sobre sexo, edad, estudios, lugar de necimiento, etc. de todas las personas que viven en cada hogar de todo el país. Una encuesta de opinión selecciona a algunos hogares y en ellos selecciona una persona en condiciones de votar, para preguntarle a quién piensa votar, qué opina da los diferentes partidos políticos, etc. La observación puede ser directa, como cuando se anota lo que se ve en un evento (una ceremonia por ejemplo) o un espacio (el patio de una escuela), pero a la que nos referimos aquí es la que está estructurada, aquella en la se explicita qué se observa. Esta etapa de la investigación, que es de producción de los datos, se llama “trabajo de campo”, también puede ser telefónico o vía web, en todos los casos, dura un tiempo y se termina.<br />
Los <strong>registros</strong> son continuos, lo que quiere decir que captan información a medida que esta se produce o bien a intervalos regulares. No empiezan y terminan, son estables, van captando los acontecimientos mientras suceden, o mejor dicho, miestras son informados. Ejemplos de estos registros son los registros civiles (de nacimientos, uniones, defunciones), de ingresos a hospitales, de inscripción a la universidad, de frontera, etc. En cualquier momento se pueden consultar y conocer lo que está registrado hasta ese momento, por ejemplo, cuántos nacimientos se asentaron en una ciudad en un año dado. O cuántos de esos nacimientos fueron de madre menor de 16 años.<br />
- Relevamientos producen datos de stock (instantáneo).<br />
- Registros producen datos flujo (continuo).</p>
<p>Cualquiera sea la fuente de los datos, una vez que se decide cuál es la información pertinente, se la recaba de varias de las entidades definidas y se cambia la óptica desde el caso particular a la regularidad colectiva. Es un cambio desde la observación del caso hacia la mirada puesta en el grupo. La siguiente es una lista que indica el área en que les gustaría trabajar cuando se reciban, a nueve estudiantes de primer año de Psicología:</p>
<table>
<caption><span id="tab:preferida">Tabla 1.1: </span>Área de trabajo preferida.</caption>
<thead>
<tr class="header">
<th align="left">Estudiante</th>
<th align="right">Área</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Susana</td>
<td align="right">Clínica</td>
</tr>
<tr class="even">
<td align="left">Marcos</td>
<td align="right">Laboral</td>
</tr>
<tr class="odd">
<td align="left">Daniel</td>
<td align="right">Clínica</td>
</tr>
<tr class="even">
<td align="left">Federico</td>
<td align="right">Social</td>
</tr>
<tr class="odd">
<td align="left">María</td>
<td align="right">Clínica</td>
</tr>
<tr class="even">
<td align="left">Pedro</td>
<td align="right">Educacional</td>
</tr>
<tr class="odd">
<td align="left">Eugenia</td>
<td align="right">Clínica</td>
</tr>
<tr class="even">
<td align="left">Mabel</td>
<td align="right">Educacional</td>
</tr>
<tr class="odd">
<td align="left">Francisco</td>
<td align="right">Laboral</td>
</tr>
</tbody>
</table>
<p>La lista reconoce a cada estudiante por su nombre, indica qué área le gustaría a cada cual y solo indica eso, no se sabe su edad, ni cuáles son sus intereses políticos ni el deporte favorito, solo se seleccionó como pertinente para este ejemplo, el área en que le gustaría trabajar. Si ahora se transforma esa lista en una tabla:</p>
<table>
<caption><span id="tab:unnamed-chunk-66">Tabla 1.2: </span>Área de trabajo preferida.</caption>
<thead>
<tr class="header">
<th align="left">Área</th>
<th align="right">Casos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Clínica</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">Educacional</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">Laboral</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Social</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p>Se lee que Clínica es un área preferida por cuatro estudiantes, Laboral y Educacional atrae a dos y a Social solo tiene una mención. Las personas desaparecieron, ya no hay nombres, hemos abstraído para referirnos al área preferida, no a las personas que las prefieren. En la tabla se ve que lo más frecuente es que se prefiera Clínica, y que Social es poco frecuente. Se pasó de la lista de personas reconocibles a la tabla de valores. Nos despegamos de los casos a fin de buscar la regularidad en el conjunto. Más adelante diremos que se ha pasado de la matriz de datos a la distribución de frecuencias, que constituye una reducción o un primer resumen de la información disponible. Esta operación es menos obvia de lo que puede parecer y es tardía en la historia de las ideas, tiene origen en la publicación, de <span class="citation">Graunt (<a href="#ref-gaunt1662">1662</a>)</span> “Observaciones naturales y políticas hechas sobre los boletines de mortalidad”, quien tomó las listas de defunciones sucedidas en Londres durante veinte años en tiempos de la peste y las resumió en orden cronológico. Su operación fue la de cambiar la lista por la tabla, para observar al proceso (la mortalidad a lo largo del tiempo), en lugar de las muertes registradas individualmente.</p>
<p>Consideremos el siguiente cuestionario, que se aplicó en 2019 a personas con edades 18 y 35 años.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cuestionario-1"></span>
<img src="imagenes/cuestionario2019_01.png" alt="Cuestionario 2019" width="413" />
<p class="caption">
Figura 1.1: Cuestionario 2019
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cuestionario-2"></span>
<img src="imagenes/cuestionario2019_02.png" alt="Cuestionario 2019" width="413" />
<p class="caption">
Figura 1.2: Cuestionario 2019
</p>
</div>
<p>Este instrumento de producción de datos, se dirigió a una población definida: personas entre 18 y 35 años. En él se solicitó información sobre un conjunto seleccionado de características; los ítems numerados desde P1 hasta P16. Se trata de unos pocos aspectos de cada persona los que interesan para esta investigación; no se tiene en cuenta, por ejemplo la opinión política de quienes responden, ni su estatura o la región en que viven. Estas últimas y muchas más son características de estas personas, pero están fuera del alcance de la investigación. Esto muestra a qué nos referimos con que la información seleccionada constituye un recorte, es una parcialización de las entidades (no siempre son personas) que responden, en la que se eligen solo los aspectos que son de interés para una investigación particular.<br />
El cuestionario tiene 16 ítems, cada persona que lo responde marca una sola de las opciones indicadas en cada ítem. Una vez completados los cuestionarios, la información está “en bruto” y es necesario ordenarla para poder tener una visión de conjunto. Eso se logra organizando los datos recogidos en la <em>matriz de datos</em> que es equivalente a la lista de la tabla <a href="los-datos-estadísticos.html#tab:preferida">1.1</a>, pero con más aspectos relevados que solo el área preferida. Para el cuestionario mostrado, el siguiente es un fragmento de esa lista:</p>
<pre><code>##    sexo edad acceso.redes red.usada red.otra tiempo.red
## 1 mujer   19           si Instagram     &lt;NA&gt;        120
## 2 varón   29           si  Facebook     &lt;NA&gt;         90
## 3 mujer   31           si  Facebook     &lt;NA&gt;         30
## 4 mujer   28           si      Otra    gmail         30
## 5 mujer   22           si Instagram     &lt;NA&gt;        120
## 6 varón   22           si  Facebook     &lt;NA&gt;        240</code></pre>
<p>Este ordenamiento rectangular de la información tiene filas (horizontales) y columnas (verticales), en esta imagen solo se ven las primeras seis filas y seis columnas de la matriz. Cada fila es una persona que respondió y cada columna es un ítem. La primera fila es el encabezado, y muestra los nombres de los ítems del cuestionario (en este ejemplo solo los seis primeros) y las seis filas mostradas, indican las respuestas dadas por los encuestados. Así, la persona que respondió al primer cuestionario es una mujer, que tiene 19 años, tiene acceso a redes sociales y la que más usa es Instagram, como no respondió “otra”, en la columna siguiente tiene <NA>, que indica que no hay dato allí (Not Available), dedica en promedio 120 minutos diarios a las redes y así sigue toda la fila correspondiente a esa persona, que no está mostrada aquí por razones de espacio.</p>
<p>La matriz de datos contiene toda la información que será insumo de los análisis posteriores, luego será necesario definir qué es cada elemento que la constituye.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">La matriz de datos es un arreglo en el que cada fila (horizontal) representa una de las entidades de la cual proviene la información, cada columna (vertical) es un aspecto de esas entidades, que se ha seleccionado para observar, y cada celda es el valor que tiene la entidad de la fila en el aspecto de la columna correspondiente.</td>
</tr>
</tbody>
</table>
</div>
<div id="las-entidades" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Las entidades<a href="los-datos-estadísticos.html#las-entidades" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hemos dicho que cada fila representa un caso, una entidad a la que se observa. Puede ser una persona como en este ejemplo, pero también una entidad colectiva: un hogar, una empresa, una escuela, un animal de laboratorio, un país. Cada una de ellas se denomina <strong>unidad de análisis</strong>.</p>
<p>Es importante que las unidades de análisis estén claras para la interpretación de los resultados. Por ejemplo, si se afirma que “las personas de menores recursos acceden menos frecuentemente a la educación superior”, hablamos de personas, y éstas son las unidades de análisis. Y es muy diferente a decir que “en los países más pobres, es menor la proporción de personas que acceden a la educación superior”, porque aquí las unidades de análisis son los países.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Las <strong>unidades de análisis</strong> son los entes individuales acerca de los que se analizan sus cualidades.</td>
</tr>
</tbody>
</table>
<p>Si las unidades de análisis fuesen escuelas, sus características, dependiendo de la investigación de que se trate, podrían ser: sector de gestión (estatal o privada), nivel (primaria, secundaria, ambas), cantidad de bancos por aula (#), turnos (mañana, tarde, ambos), etc. Si se tratara de hogares, puede observarse: cantidad de miembros, composición, actividad económica, etc. Si se observan países, sus características de interés pueden ser: su régimen político, cantidad de habitantes, distribución de la riqueza, etc.</p>
</div>
<div id="las-variables" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Las variables<a href="los-datos-estadísticos.html#las-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cada columna de la matriz de datos es un ítem del cuestionario, es decir un aspecto seleccionado de las unidades de análisis hacia el cual se dirige la atención, que se consideró necesario para la investigación. Esos aspectos se denominan <strong>variables</strong>. Así, el <em>sexo</em> es una variable, como lo es <em>con quién vive</em>, <em>cuánto daría en el experimento</em>, etc. Cada ítem del cuestionario se constituye en una variable, a veces su expresión interrogativa en el cuestionario se transforma en algo más abreviado, como la pregunta: “¿Cuánto tiempo (en minutos) estuviste conectado/a a las redes sociales en el día de ayer?” se trata como la variable <em>tiempo.red</em>. Las variables son los aspectos de las entidades que se someterán al análisis, aquellos aspectos que se han seleccionado como información pertinente para un estudio en particular. Su cualidad central es la que le da nombre: la de variar.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Una <strong>variable</strong> es una característica de las unidades de análisis que puede asumir diferentes valores en cada una de ellas.</td>
</tr>
</tbody>
</table>
<p>Cada vez que se haga referencia a una variable, debe conocerse cuál es la unidad de análisis a la que se refiere, si no resulta claro, se debe indicar. Es diferente afirmar que un país es rico que decir que sus habitantes lo son.</p>
</div>
<div id="las-categorías" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Las categorías<a href="#las-categor%C3%ADas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El cuerpo de la matriz de datos tiene números que corresponden a las respuestas que cada respondente dio a cada ítem. En la primera fila, primera columna dice “mujer” esa es la respuesta que dió esa persona. En esta pregunta, se podía elegir entre dos respuestas diferentes (varón, mujer), en el lenguaje que estamos introduciendo, diremos que esta variable (<em>sexo</em>) puede asumir dos <strong>categorías</strong> diferentes. Para el primer caso, la variable <em>sexo</em> asume la categoría “mujer”. Las categorías son las posibilidades que tiene una variable, son sus alternativas, dentro de las cuales a todas las unidades de análisis les corresponde una y solo una.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Las <strong>categorías</strong> de una variable son los valores que ésta puede asumir.</td>
</tr>
</tbody>
</table>
<p>Cada vez que se define una variable ─es decir cada vez que se selecciona un aspecto de las unidades de análisis para observar─, debe indicarse también el conjunto de categorías que le corresponden, aunque a veces esto está implícito. Si la variable es <em>nivel de escolaridad alcanzado</em>, pueden considerarse las siguientes categorías: “ninguno”, “primario incompleto”, “primario completo”, “secundario incompleto”, “secundario completo”, “terciario o universitario incompleto”, “terciario o universitario completo” y “postgrado”. Si tratamos con la variable <em>edad</em>, sus categorías son valores numéricos, entre cero y un máximo de años que se fija según el caso.</p>
<div id="requisitos-de-las-categorías" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Requisitos de las categorías<a href="#requisitos-de-las-categor%C3%ADas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hay dos propiedades que debemos asegurar que cumplan las categorías que construyamos. La primera se llama <strong>exclusión mutua</strong>, es decir que cada categoría excluya a todas las demás. Dicho de otra manera, si a una unidad de análisis le corresponde una categoría, entonces sabemos que no le corresponde ninguna otra. Si analizamos hogares y a cada persona le preguntamos por su parentesco, sin indicar con quién, tendremos una categorización defectuosa, porque una persona del hogar puede al mismo tiempo ser hijo y hermano, o hija y madre, si conviven tres generaciones. En cualquiera de los dos casos, a una misma persona le corresponderían dos categorías y se viola el requisito de exclusión mutua. Esto se resuelve estableciendo respecto de quién se declara el parentesco, y cada integrante del hogar lo refiere a la misma persona<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.</p>
<p>Al analizar los tipos de lectura preferida, nos equivocaríamos si los categorizáramos como de ficción, de misterio, policiales, románticas, biográficas, de aventuras; ya que la categoría ficción puede incluir misterio, policiales, novelas románticas o de aventuras.</p>
<p>También se comete ese error si se clasifica a las escuelas como céntricas, parroquiales, urbanas y rurales. Dado que una escuela puede ser al mismo tiempo parroquial y urbana. Es necesario separar, para que quede claro, lo que interesa en el análisis: si lo que queremos distinguir son escuelas céntricas de barriales, entonces la variable será la ubicación geográfica y no importa si la escuela depende de una iglesia o del estado; es decir, primero identificar la variable (que aspecto se quiere observar) y luego sus categorías (cuáles son las posibilidades de ese aspecto).</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Las categorías de una variable son <strong>mutuamente excluyentes</strong> si a cada individuo le corresponde no más de una categoría.</td>
</tr>
</tbody>
</table>
<p>El segundo requisito que solicitaremos a las categorías de una variable es que agoten todas las posibilidades de variación, es decir, que todos los valores posibles estén contemplados. Esta cualidad se llama <strong>exhaustividad</strong>.</p>
<p>Veamos qué sucede si no respetamos este requisito. Si evaluamos la variable situación conyugal y ofrecemos como categorías: “casada/casado”, “soltera/soltero”, “divorciada/divorciado”, “viuda/viudo”; las personas que estén viviendo juntas sin estar casadas no encuentran un lugar donde ubicarse, como tampoco lo encuentran quienes están separados sin haberse divorciado. Para resolver esto es necesario, o bien incluir estas categorías explícitamente, agregando “unida/unido”, “separada/separado”; con lo que se amplía el número de categorías, o bien fusionarlas con las existentes: “casada/casado o unida/unido”, “soltera/soltero”, “separada/separado o divorciada/divorciado”, “viuda/viudo”.<br />
Con la edad, las categorías son valores numéricos que pueden ir del cero hasta el un máximo, pero ¿dónde fijarlo? Si se eligiera un límite como 100 años, algunas personas quedarían fuera, quizás sean pocas, pero no pueden quedar sin categoría donde incluirse. Por lo demás, puede haber solo una persona de 103 años, otra de 105, por lo que no se justifica seguir extendiendo categorías. Una solución frecuente es la de tomar una categoría abierta final, fijando como última categoría “100 y más”, e incluir allí a todas las personas que declaren una edad de 100 años o superior. Puede verse que esta opción conlleva una pérdida de información, ya que no sabemos la edad exacta de quienes se ubican en esa categoría. Aceptamos esa pérdida a cambio de reducir el número de categorías de la variable, luego volveremos sobre eso.<br />
Algunas preguntas de cuestionarios, luego de un conjunto de opciones para responder, incluyen una categoría que dice “Otro<span class="math inline">\(\ldots\)</span> especificar”. Se trata de casos de categorizaciones en las que no se sabe de antemano cuáles son todas las respuestas posibles; son frecuentes en las encuestas de opinión. Por ejemplo, si alguien declara que en las próximas elecciones va a votar en blanco y preguntamos por qué, podemos conocer de antemano algunas de las respuestas posibles, pero debemos dejar espacio para que se expresen razones que no habíamos previsto. De este modo aseguramos la exhaustividad de las categorías. En el cuestionario del ejemplo, la P7 tiene, en la opción 5, la posibilidad de otras alternativas de convivencia, aparte de las ofrecidas.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Las categorías de una variable son <strong>exhaustivas</strong> si todo individuo tiene alguna categoría que le corresponda.</td>
</tr>
</tbody>
</table>
<p>En algunas situaciones, el número de categorías de una variable es parte de las decisiones de la investigación. Hay casos en que las categorías están establecidas de antemano: por ejemplo, en la variable sexo se tiende a usar como categorías las de varón y mujer; sin embargo, si estamos frente a un estudio que trate precisamente sobre identidad de género, deberá considerarse un espectro más amplio de categorías, o bien ofrecer preguntas abiertas, sin establecer categorías de antemano. Como ha sido el caso de P2 en el cuestionario, que no ha sido cargada en la matriz de datos, porque requiere una codificación posterior.<br />
Como se señaló, en la edad de las personas suele elegirse terminar las categorías con “100 y más”. De hecho, también se podrían mantener las edades exactas hasta 109 años y cerrar con 110 y más. Qué se elija depende de cuánta información y cuánta claridad se decida que tenga la clasificación; lamentablemente, no es posible lograr al mismo tiempo el máximo de información y de claridad en la presentación<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
</div>
</div>
<div id="los-símbolos-numéricos" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Los símbolos numéricos<a href="#los-s%C3%ADmbolos-num%C3%A9ricos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las categorías pueden tener diferente naturaleza: algunas se expresan con números (como la edad) y otras con palabras (como la carrera que cursa), otras en graduaciones (como el grado de acuerdo); sin embargo es muy común representar con números a las categorías, aun cuando lo que se observe no sea numérico. Así, en la variable nivel de educación, pueden codificarse las categorías de la siguiente manera:</p>
<table>
<caption><span id="tab:unnamed-chunk-68">Tabla 1.3: </span>Nivel de educación alcanzado.</caption>
<thead>
<tr class="header">
<th align="center">Código</th>
<th align="left">Máximo nivel de educación formal alcanzado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="left">ninguno</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="left">primario incompleto</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="left">primario completo</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="left">secundario incompleto</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="left">secundario completo</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="left">terciario o universitario incompleto</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="left">terciario o universitario completo</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="left">postgrado</td>
</tr>
</tbody>
</table>
<p>Hemos usado números para referirnos a las categorías a fin de simplificar la notación.<br />
De manera equivalente podemos codificar las categorías de otras variables:</p>
<table>
<caption><span id="tab:unnamed-chunk-69">Tabla 1.4: </span>Distribución por sexos.</caption>
<thead>
<tr class="header">
<th align="center">Código</th>
<th align="center">Sexo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">Varón</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">Mujer</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-70">Tabla 1.5: </span>Satisfacción con el progreso en la carrera.</caption>
<thead>
<tr class="header">
<th align="center">Código</th>
<th align="left">Estoy muy satisfecho con el modo en que he progresado en mi carrera</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="left">Completamente en desacuerdo</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="left">En desacuerdo</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="left">Indiferente</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="left">De acuerdo</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="left">Completamente de acuerdo</td>
</tr>
</tbody>
</table>
<p>En las variables cuyas categorías son numéricas, no es necesario hacer ninguna codificación. Así, la edad quedará expresada de manera numérica directamente por la cantidad de años, como sucede con la cantidad de materias aprobadas, el número de hijos e hijas o la cantidad de habitantes de un país. En estos casos, la exclusión mutua y la exhaustividad se cumplen sin más.</p>
</div>
<div id="la-medición" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> La medición<a href="#la-medici%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En Ciencias Sociales tiene plena vigencia el debate acerca de las posibilidades de medición de los fenómenos que se estudian. Buena parte de la discusión gira en torno a una definición de medición, ya que según qué sea lo que se considere como tal, se tratará de una medición o no. La posición más tradicional corresponde a lo que el sentido común trata como medición: la estatura, las distancias, el peso, etc. Esta definición demanda que los números que codifican a las categorías tengan algunas propiedades para considerarlos como mediciones. Se conoce como teoría clásica de la medición, y desde ese punto de vista sería muy difícil realizar mediciones sobre las variables que manejamos en Ciencias Sociales. Una definición menos restrictiva es la que propuso <span class="citation">Stevens (<a href="#ref-Stevens1946">1946</a>)</span>, según la cual:</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">“medir es asignar números a los objetos según cierta regla, de manera que los números asignados en la medición, no representan propiamente cantidades, sino relaciones”.</td>
</tr>
</tbody>
</table>
<p>Esta última definición, basada en la teoría representacional de la medición, es la que adoptaremos en este curso aunque la discusión sigue vigente. Desde esta definición, evaluar una variable para una unidad de análisis dada, equivale a medir esa unidad de análisis en el aspecto que la variable expresa.</p>
<p>Aun cuando se adopte una definición amplia de lo que es medir, podemos intuir que no se mide una opinión del mismo modo que se mide el salario o la estatura. Además, hay ocasiones en que la palabra <em>medición</em> parece forzada. Si se asigna el número 1 a los varones y 2 a las mujeres, decir que con estos números se <em>mide el sexo</em> es extraño. Por el contrario, resulta familiar <em>medir la estatura</em> asignando a cada persona el número de centímetros que indica una cinta métrica. Sin embargo, desde la teoría representacional, ambas son mediciones. Esto sugiere que, dentro de las variables de las que hemos hablado hasta aquí habrá que reconocer diferencias, y estas diferencias vendrán dadas por el significado que tengan los números que asignamos a las categorías, es decir, por las reglas que ligan los números con lo que se observa.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">El <strong>nivel de medición</strong> de una variable está determinado por el significado que tengan los símbolos numéricos que se asignan a las categorías.</td>
</tr>
</tbody>
</table>
<p>Existe una graduación en el significado que tienen los números, y por eso se habla de niveles, que pueden ser más altos o más bajos. En la variable <em>sexo</em>, haber elegido “1” para varones y “2” para mujeres es de una arbitrariedad total (de la que alguien podría quejarse). Si la codificación hubiese sido al revés, habría estado igual de bien, y también habría estado bien usar el número “75” para representar a los varones y el “38” para las mujeres, aunque esto resulta un poco incómodo. Por el contrario, en la variable <em>edad</em>, asignar el número “20” a quien tiene 20 años, parece totalmente “natural” ¿qué otro número podríamos haber asignado? ¿Qué sucede con el <em>nivel de educación</em>? En el ejemplo elegimos numerar las categorías del 1 al 8; habría habido otras opciones, por ejemplo usar solo números pares o números impares u otra secuencia arbitraria, pero algo importante es que cualquier secuencia que se elija debe respetar el orden de las categorías de la variable, por lo que los números deben reflejarlo; no habría sido correcto usar números que no vayan aumentando, como lo hacen los niveles de educación.</p>
<p>Así entonces, hay grados diferentes en la libertad que existe para asignar los números a las categorías. Esas diferencias distinguen los niveles de medición de las variables.</p>
<div id="niveles-de-medición" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Niveles de medición<a href="#niveles-de-medici%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Según la mayor o menor arbitrariedad que exista en la relación que liga los números a las categorías, hablaremos de diferentes niveles de medición: cuánta más restricción haya en la asignación de los números a las categorías, más alto será el nivel de medición de las variables. Cuanto más alto sea el nivel de medición, mayores son las propiedades que tienen los números, es decir son más amplias las operaciones que puede hacerse son ellos. Si los números se asignan de manera totalmente arbitraria, el nivel de medición es el más bajo de todos y se llama <strong>nivel nominal</strong> (como en la variable <em>sexo</em>); si los números deben respetar el orden de las categorías (como en la <em>educación</em>), la variable se llama de <strong>nivel ordinal</strong>. Por ahora, nos detenemos en estos dos niveles.</p>
<div id="el-nivel-nominal" class="section level4 hasAnchor" number="1.6.1.1">
<h4><span class="header-section-number">1.6.1.1</span> El nivel nominal<a href="los-datos-estadísticos.html#el-nivel-nominal" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Es el nivel más elemental de medición: las variables de este nivel tienen categorías que son solo nombres (de allí que se llamen nominales). La asignación de códigos numéricos cumple la función de designar las categorías, es decir, de distinguirlas unas de otras. Por ejemplo, <em>área de especialización preferida</em> (UA = estudiantes de Psicología) y <em>carrera que cursa</em> (UA = estudiantes de nivel universitario), podrían tener las siguientes codificaciones:</p>
<table>
<caption><span id="tab:nivelNomCod">Tabla 1.6: </span>Ejemplos de codificación de variables nominales.</caption>
<thead>
<tr class="header">
<th align="center">Código</th>
<th align="left">Carrera</th>
<th align="center">Código</th>
<th align="left">Área</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="left">Psicología</td>
<td align="center">1</td>
<td align="left">Clínica</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="left">Filosofía</td>
<td align="center">2</td>
<td align="left">Educacional</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="left">Medicina</td>
<td align="center">3</td>
<td align="left">Jurídica</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="left">Otras</td>
<td align="center">4</td>
<td align="left">Laboral</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="left"></td>
<td align="center">5</td>
<td align="left">Sanitaria</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="left"></td>
<td align="center">6</td>
<td align="left">Social</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="left"></td>
<td align="center">7</td>
<td align="left">Experimental</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="left"></td>
<td align="center">8</td>
<td align="left">Otra</td>
</tr>
</tbody>
</table>
<p>Por comodidad, se empieza en el “1” y desde allí correlativamente, pero no hay ninguna prohibición para codificar con cualquier conjunto de números. Aun con esta amplia libertad para elegir los códigos numéricos, hay algo que no se puede hacer: no es válido usar el mismo número más de una vez. Si hiciéramos esto, confundiríamos las categorías que corresponden a cada individuo. Así, a un estudiante de Psicología, le asignamos el valor “1” en la variable <em>carrera</em>, ya no podría usarse ese mismo número en la misma variable también para alguien que estudia Medicina. Diremos que la condición que deben cumplir los números en este nivel de medición es que: a categorías diferentes correspondan números distintos.<br />
Entonces, en este nivel de medición a cada categoría puede asignarse, de manera arbitraria, uno y solo un número. Esta forma de asignar los valores numéricos solo implica que éstos designan las categorías (que las distinguen a una de otra), por eso, no es posible tratarlos como números en cuanto a sus propiedades aritméticas. En particular no puede sumárselos: nada puede significar que se sumen los números “1” y “2” que codifican a las carreras de Psicología y Filosofía.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Una variable está medida a nivel <strong>nominal</strong> si los números que representan cada categoría son asignados de manera arbitraria y solo cumplen con la función de designar y distinguir categorías diferentes.</td>
</tr>
</tbody>
</table>
<p>Para unidades de análisis medidas a través de una variable de nivel nominal, es posible saber si corresponden a la misma categoría o a una diferente, es decir si tienen la misma cualidad (o atributo) o una diferente.</p>
<p>En la tabla <a href="los-datos-estadísticos.html#tab:nivelNomCod">1.6</a> si a una persona le corresponde el número “1” y a otra también, podemos decir que coinciden en esta variable, ambas estudian la misma carrera (Psicología), y si a una le corresponde el “1” y a otra el “3”, sabremos que la primera estudia Psicología y la otra Medicina. El hecho que el número “3” sea más grande que el “1”, no tiene ninguna interpretación en este nivel de medición, no puede decirse que Psicología sea menos que Medicina. Como tampoco vale que “3” sea el triple de “1”.</p>
<p>Si “1” y “2” son dos categorías de una variable medida a nivel nominal, el único tipo de relación que puede establecerse entre ellas es <span class="math display">\[1\neq2\]</span>
Es decir que 1 es diferente de 2.</p>
<p>La regla de transformación de una escala nominal en otra es que cualquier número puede cambiarse por cualquiera a condición de no repetir ninguno. La escala nominal “1”, “2”, “3”, “4” puede cambiarse por la “5”, “8”, “4”, “2”. Aunque no es obligatorio, en la práctica, lo más frecuente es usar los primeros números naturales para codificar las categorías.</p>
</div>
<div id="el-nivel-ordinal" class="section level4 hasAnchor" number="1.6.1.2">
<h4><span class="header-section-number">1.6.1.2</span> El nivel ordinal<a href="los-datos-estadísticos.html#el-nivel-ordinal" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Aquí subimos un nivel, ya que a los números que solo tienen la propiedad de designar en las variables nominales, se agrega otra: la de reflejar el orden que existe entre las categorías.
Simplemente ahora se trata de variables cuyas categorías indican alguna cualidad de las unidades de análisis que crece en una dirección. Eso equivale a decir que se pueden hacer entre ellas, juicios de orden, tales como una categoría es mayor que otra, una categoría es menor que otra. El <em>grado de escolarización</em> cumple con ese requisito: efectivamente, el “primario incompleto” es un nivel de estudios superior a “ninguno”, pero inferior a “primario completo”.
Los valores numéricos que representan las categorías rescatan ahora una propiedad adicional: el orden. Además de poder distinguir si dos sujetos tienen la misma característica analizada o una distinta, como en el nivel nominal, ahora también podemos saber si un individuo tiene esa característica en mayor o menor grado. Así como “ninguno” es menor que “primario incompleto”, los números correspondientes cumplen con que “1” es menor que “2” y resulta más sencillo escribirlo como <span class="math display">\[1 &lt; 2\]</span>.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Una variable está medida a nivel <strong>ordinal</strong> si los números que representan cada categoría son asignados de manera que respeten el orden según aumenta o disminuye la característica que la variable mide.</td>
</tr>
</tbody>
</table>
<p>Estos números designan las categorías y son expresión de la jerarquía que hay entre ellas. Otro ejemplos de variable medida a nivel ordinal y su correspondiente codificación numérica es la pregunta ¿Alguna vez en tu vida golpeaste a alguien tan fuerte que necesitó atención médica u hospitalaria? (P14) del cuestionario, que fue codificada de manera creciente con la intensidad:</p>
<table>
<caption><span id="tab:unnamed-chunk-72">Tabla 1.7: </span>Ejemplo de codificación de una variable ordinal.</caption>
<thead>
<tr class="header">
<th align="center">Código</th>
<th align="left">P14</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1.</td>
<td align="left">Nunca</td>
</tr>
<tr class="even">
<td align="center">2.</td>
<td align="left">Una vez</td>
</tr>
<tr class="odd">
<td align="center">3.</td>
<td align="left">Dos o tres veces</td>
</tr>
<tr class="even">
<td align="center">4.</td>
<td align="left">De cuatro a seis veces</td>
</tr>
<tr class="odd">
<td align="center">5.</td>
<td align="left">Más de seis veces</td>
</tr>
</tbody>
</table>
<p>De aquí en adelante ya no usaremos una columna especial de la tabla para indicar el código, simplemente lo señalamos junto al nombre de la categoría, encabezado con el nombre abreviado de la variable:</p>
<table>
<caption><span id="tab:unnamed-chunk-73">Tabla 1.8: </span>Ejemplo de una variable ordinal codificada.</caption>
<thead>
<tr class="header">
<th align="left">Golpeó</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Nunca</td>
</tr>
<tr class="even">
<td align="left">2. Una vez</td>
</tr>
<tr class="odd">
<td align="left">3. Dos o tres veces</td>
</tr>
<tr class="even">
<td align="left">4. De cuatro a seis veces</td>
</tr>
<tr class="odd">
<td align="left">5. Más de seis veces</td>
</tr>
</tbody>
</table>
<p>Acerca del significado de los valores numéricos en las variables de nivel ordinal, si bien hemos agregado el orden, aun no es posible hacer operaciones con ellos. Es decir, no es posible sumar dos valores y que la suma tenga algún significado. Por ejemplo, en la última variable, no es cierto que <span class="math inline">\(3 = 2+1\)</span>, porque no es cierto que “dos o tres veces” sea lo mismo que “nunca” más “una vez”. Tampoco es válido restarlos, veamos que la diferencia entre 1 y 2 es 1 y la diferencia entre 4 y 5 también es 1, pero eso no tiene un correlato entre las categorías: no es cierto que haya la misma distancia entre “nunca” y “una vez” que entre “de cuatro a seis” y “más de seis”, simplemente porque no tenemos definida la idea de <em>distancia</em> para esta variable.<br />
Si “1” y “2” son dos categorías de una variable medida a nivel ordinal, se pueden establecer las relaciones: <span class="math display">\[1 \neq 2\]</span> y <span class="math display">\[1&lt;2\]</span> Es decir que, uno es diferente que dos y que uno es menor que dos. A la relación de distinción que existe entre categorías de la escala nominal se agrega la relación de orden.</p>
<p>La regla de transformación de una escala ordinal en otra consiste en cambiar los números por cualquiera, a condición que no se repita ninguno (como en la nominal) y además, que sigan el mismo orden. La escala ordinal “1”, “2”, “3”, “4” puede cambiarse por la “5”, “8”, “15”, “23”. Nuevamente, esto es poco común y suelen usarse números correlativos.</p>
<p>Los dos niveles (o escalas) de medición siguientes se llaman intervalares y proporcionales y usan las codificaciones numéricas con un significado un poco diferente al visto hasta aquí. La principal diferencia es que el grado de arbitrariedad para asignar los números se reduce sustancialmente. En primer lugar, las escalas intervalares conservan las distancias entre los valores. En las variables medidas a nivel proporcional, además de conservarse la distancia, se verifica la proporcionalidad de los valores: es decir que, recién en estas escalas, cuatro será el doble de dos.</p>
</div>
<div id="el-nivel-intervalar" class="section level4 hasAnchor" number="1.6.1.3">
<h4><span class="header-section-number">1.6.1.3</span> El nivel intervalar<a href="los-datos-estadísticos.html#el-nivel-intervalar" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Veamos un ejemplo antes de definir este nivel. Cuando decimos que estamos en el año 2020, hacemos implícitamente una afirmación que supone una medición del tiempo transcurrido desde un determinado evento, cuya elección no es única. En cierto modo decimos “han transcurrido 2020 años desde el momento que se acordó usar como inicio de este calendario”. En culturas no cristianas, el origen en la medición de los tiempos puede ubicarse en otro momento y, en consecuencia, el año actual es otro. En el calendario judío, por ejemplo, el presente es el año 5780. Hay entonces libertad para decidir la ubicación del punto desde donde empezar a contar los años. Lo que podría llamarse el “año cero”, no es necesariamente el mismo. Sin embargo, el tiempo transcurrido entre la Toma de la Bastilla en Paris y la Toma del Palacio de Invierno en Petrogrado es de 128 años, que es el período entre 1789 y 1917 en el calendario gregoriano y entre 5549 y 5677 según el calendario judío. Es decir que la transformación que lleva los años de un calendario al otro, conserva las distancias. Independientemente de la escala con que hayamos medido el año, la diferencia entre dos años, se mantiene constante. Eso sucede porque las dos escalas (en este ejemplo, la medición del tiempo según las tradiciones cristiana y judía) se distinguen solo en la elección del origen (la posición del cero) pero no en la definición de lo que es un año. Para ambas escalas un año corresponde a una vuelta de la tierra al sol, por lo que la unidad de medición es la misma<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>. Si alguien tiene 30 años en el calendario gregoriano, también tiene 30 años con el calendario judío; porque, aunque tanto el año de nacimiento como el actual sean diferentes en los dos calendarios, la diferencia (el tiempo transcurrido) entre las dos fechas es la misma. Ubicar el cero en un momento (en un determinado hecho histórico) o en otro es una elección; ese cero no indica la “ausencia de tiempo”. En este caso, cero no quiere decir “nada”, sino “origen elegido”.</p>
<p>Una forma de medir la inteligencia es la de observar cuántos problemas de una serie de dificultad creciente se es capaz de resolver correctamente. Pero, ¿podría decirse que quien no resuelve ninguno de ellos tiene inteligencia cero?, esto es claramente incorrecto, porque la ubicación del cero no implica la ausencia de lo que estamos midiendo (ausencia de inteligencia en este caso).</p>
<p>Las escalas intervalares, mantienen las propiedades de las escalas ordinales y nominales, es decir, los números designan categorías y permiten ordenarlas; pero además permiten decir a qué distancia está una de otra, porque cada categoría se expresa también en sentido cuantitativo. La medición intervalar implica construir una escala en la que las categorías están proporcionalmente distanciadas entre sí. Esto permite especificar la distancia que separa a cada categoría de las demás. Este nivel de medición requiere que se establezca algún tipo de unidad de medida que pueda ser considerado como una norma común y que sea repetible, esto es, que se pueda aplicar reiteradamente a las mismas observaciones produciendo los mismos resultados.</p>
<p>La medición de los rendimientos individuales por medio de pruebas suele expresarse en puntajes que provienen del tiempo requerido para realizar una determinada tarea o de la cantidad de trabajo realizado. En este tipo de prueba, es común que los puntajes partan de un mínimo establecido (por ejemplo el mínimo tiempo posible de ejecución o la mínima cantidad de tareas que una persona puede realizar en una prueba) y esto constituye el puntaje mínimo o la categoría más baja. Los puntajes de las pruebas mentales varían de acuerdo con el rendimiento y un mayor rendimiento siempre significará un mayor puntaje. Por ejemplo, el manual original del Inventario de Depresión de Beck-II <span class="citation">(<a href="#ref-Upton2013">Upton 2013</a>)</span> establece niveles (ordinales) para los puntajes (intervalares) que resultan de la aplicación del instrumento:</p>
<table>
<caption><span id="tab:unnamed-chunk-74">Tabla 1.9: </span>Ejemplo de codificación de rangos de puntajes para una variable intervalar.</caption>
<thead>
<tr class="header">
<th align="left">Puntaje en la escala</th>
<th align="left">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0 - 13</td>
<td align="left">depresión mínima</td>
</tr>
<tr class="even">
<td align="left">14 - 19</td>
<td align="left">depresión leve</td>
</tr>
<tr class="odd">
<td align="left">20 - 28</td>
<td align="left">depresión moderada</td>
</tr>
<tr class="even">
<td align="left">29 - 63</td>
<td align="left">depresión grave</td>
</tr>
</tbody>
</table>
<p>De este modo se ha bajado el nivel de medición, de intervalar a ordinal.</p>
<p>A nivel intervalar, ya es posible expresar la regla de transformación de manera formal; así, si <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> representan la medición del mismo atributo en diferentes escalas, puede obtenerse <span class="math inline">\(y\)</span> a partir de <span class="math inline">\(x\)</span> a través de la siguiente operación:</p>
<p><span class="math display">\[y = b_0 + b_1*x\]</span></p>
<p>Se usan los símbolos <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span> para indicar dos números fijos elegidos arbitrariamente. El primero de ellos indica el desplazamiento en el origen de la escala: allí donde <span class="math inline">\(x\)</span> valga 0, <span class="math inline">\(y\)</span> tomará el valor de <span class="math inline">\(b_0\)</span>. Por su parte, <span class="math inline">\(b_1\)</span> es un factor de escala, que modifica el tamaño de la unidad de medida.<br />
En el ejemplo de la medición del año según dos calendarios diferentes, si <span class="math inline">\(x\)</span> es la medición en el calendario gregoriano e <span class="math inline">\(y\)</span> con el calendario judío, la relación es:</p>
<p><span class="math display">\[y = 3760 + x\]</span></p>
<p>En la que <span class="math inline">\(b_0\)</span> se reemplazó por 3760 y <span class="math inline">\(b_0\)</span> ha desaparecido, es decir que vale 1 (que no tiene efecto cuando multiplica a <span class="math inline">\(x\)</span>). El valor 3760 representa el cambio en el origen: cuando el calendario gregoriano marcó cero (hipotéticamente, porque su implementación es posterior a esa época), el judío indicaba el año 3760. El <span class="math inline">\(1\)</span> correspondiente a <span class="math inline">\(b_1\)</span>, indica que no hay cambio en el tamaño de la unidad, como dijimos antes, ambas culturas acuerdan en que el año es una vuelta de la tierra al sol<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Una variable está medida a nivel <strong>intervalar</strong> cuando las distancias entre las categorías son proporcionales.</td>
</tr>
</tbody>
</table>
<p>Si 1, 2, 3 y 4 son categorías de una variable medida a nivel intervalar, se pueden establecer las relaciones:</p>
<p><span class="math display">\[1 \neq 2\]</span><br />
<span class="math display">\[1 &lt; 2\]</span><br />
<span class="math display">\[2 - 1 = 4 - 3\]</span></p>
<p>Se agrega la conservación de las distancias a las propiedades que ya tenía la escala anterior.</p>
</div>
<div id="el-nivel-proporcionalescalas_de_razon" class="section level4 hasAnchor" number="1.6.1.4">
<h4><span class="header-section-number">1.6.1.4</span> El nivel proporcional<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a><a href="los-datos-estadísticos.html#el-nivel-proporcionalescalas_de_razon" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Este es el último nivel de medición que trataremos y es el más intuitivo, es el único nivel considerado efectivamente como medición por la teoría clásica, ya que en él se integran todas las propiedades de los niveles anteriores y además se agrega la proporcionalidad de los valores numéricos y el carácter absoluto del cero. Recién a este nivel, los números se comportan realmente como números, ya que se puede operar con ellos del modo al que estamos acostumbrados (sumarlos, multiplicarlos, etc.). ¿Qué variables pueden medirse a este nivel? Todas aquellas para las cuales tengan sentido las dos propiedades adicionales que esta escala incorpora: proporcionalidad de valores y cero absoluto. La <em>cantidad de errores ortográficos cometidos en una prueba de dictado</em>, admite el valor cero como correspondiente a “no errores”, es la ausencia de lo que se mide, se trata de un cero absoluto. Además, cometer 10 errores es el doble que cometer 5. Por eso, la variable <em>número de errores ortográficos</em> es de nivel proporcional. El <em>tiempo que una persona tarda en resolver una tarea</em>, si se mide en minutos, admite considerar que 4 minutos es el doble de 2, por lo que estamos también en presencia de una escala proporcional, aunque el cero no sea un valor observable. También es proporcional la variable <em>ingresos mensuales del hogar</em> o el <em>número de materias aprobadas</em>, <em>cantidad de diputadas que aporta cada partido a la cámara</em>, <em>población de las provincias</em>.</p>
<p>En general, los valores que provengan de procesos de conteo (como el <em>número de errores</em>) serán siempre proporcionales, como también aquellos que hagan referencia a una unidad de medida estándar como el <em>tiempo</em><a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> o la <em>distancia</em>.</p>
<p>La expresión formal de la regla de transformación entre escalas proporcionales es, si <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> representan la medición del mismo atributo en diferentes escalas:</p>
<p><span class="math display">\[y = b_1 * x\]</span></p>
<p>En la que ahora solo tenemos un número fijo: <span class="math inline">\(b_1\)</span>, que es el factor de escala, que modifica el tamaño de la unidad de medida. Esto simplemente significa que pueden cambiarse las unidades con que se miden las variables proporcionales. Por ejemplo para pasar de metros a centímetros, se multiplica por cien:</p>
<p><span class="math display">\[y = 100 * x\]</span></p>
<p>Donde <span class="math inline">\(x\)</span> es la medida en metros e <span class="math inline">\(y\)</span> la misma medida expresada en centímetros. Si <span class="math inline">\(x=3\)</span> metros entonces <span class="math inline">\(y=300\)</span> centímetros</p>
<p>Como una hora tiene sesenta minutos, la transfomación es:</p>
<p><span class="math display">\[y = 60 * x\]</span></p>
<p>El factor 60 transforma a las horas (<span class="math inline">\(x\)</span>) en minutos (<span class="math inline">\(y\)</span>). Si <span class="math inline">\(x=2\)</span> horas entonces <span class="math inline">\(y=120\)</span> minutos</p>
<p>Otro ejemplo, si el tiempo que tardan quienes participan de un experimento en reconocer una expresión facial se mide en milisegundos (<span class="math inline">\(x\)</span>), esa medición se puede pasar a segundos (<span class="math inline">\(y\)</span>), dividiendo por mil.</p>
<p><span class="math display">\[y=\dfrac{1}{1000}*x\]</span></p>
<p>Ninguna de esas transformaciones pueden modificar la posición del cero, porque en esta escala es absoluto: allí donde <span class="math inline">\(x\)</span> valga cero, <span class="math inline">\(y\)</span> deberá también valer cero, por eso no aparece el término <span class="math inline">\(b_0\)</span> que estaba en las intervalares. Cero metros son también cero centímetros y cero horas son cero minutos.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="center">Una variable está medida a nivel <strong>proporcional</strong> cuando sus valores respetan relaciones de proporcionalidad y, en consecuencia, el cero tiene un valor absoluto.</td>
</tr>
</tbody>
</table>
<p>Si 1, 2, 3 y 4 son categorías de una variable medida a nivel proporcional, se pueden establecer las relaciones:</p>
<p><span class="math display">\[1 \neq 2\]</span><br />
<span class="math display">\[1 &lt; 2\]</span><br />
<span class="math display">\[2 - 1 = 4 - 3\]</span><br />
<span class="math display">\[4 = 2 * 2\]</span></p>
<div id="una-subdivisión-en-las-escalas-proporcionales" class="section level5 hasAnchor" number="1.6.1.4.1">
<h5><span class="header-section-number">1.6.1.4.1</span> Una subdivisión en las escalas proporcionales<a href="#una-subdivisi%C3%B3n-en-las-escalas-proporcionales" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Entre las variables medidas a nivel proporcional, debe hacerse una diferenciación, según los valores solo puedan ser números enteros o admitan números decimales, porque cambia la forma de presentación. El primer tipo es el que se llama variable <strong>discreta</strong>, los siguientes son ejemplos de ella:</p>
<table>
<caption><span id="tab:unnamed-chunk-75">Tabla 1.10: </span>Ejemplos de variable proporcional discreta.</caption>
<thead>
<tr class="header">
<th align="center">Cantidad de aplazos</th>
<th align="center">Número de materias aprobadas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">2</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">3</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center">4</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">5</td>
<td align="center">5</td>
</tr>
<tr class="odd">
<td align="center">6</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">7 o más</td>
</tr>
</tbody>
</table>
<p>Aquí podría suceder que la variable tenga un gran número de valores. En el ejemplo de la <em>cantidad de materias aprobadas</em>, puede restringirse a las aprobadas por quienes han terminado de cursar primer año y en condición de regular, de modo que el máximo sea de 6. Pero si fueran estudiantes de toda la carrera, la cantidad podría ir desde cero hasta el número total de materias. En esos casos, resultaría poco claro hacer la lista con todos los valores posibles.</p>
<p>Cuando una variable discreta tiene una cantidad grande de valores, el problema de la presentación de las categorías se resuelve agrupándolas. Esto se llama recategorización porque consiste en construir nuevas categorías (volver a categorizar) a partir de las originales de la variable, a fin de resumir la información. Por ejemplo, la primera categoría puede contar a quienes aprobaron una materia o ninguna, la segunda a quienes aprobaron dos o tres y así sucesivamente:</p>
<table>
<caption><span id="tab:unnamed-chunk-76">Tabla 1.11: </span>Ejemplo de recategorización de una variable discreta.</caption>
<thead>
<tr class="header">
<th align="center">Número de materias aprobadas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0-1</td>
</tr>
<tr class="even">
<td align="center">2-3</td>
</tr>
<tr class="odd">
<td align="center">4-6</td>
</tr>
</tbody>
</table>
<p>Cuando la variable admite números decimales se la llama <strong>continua</strong>, y allí el problema es mayor, porque el número de valores puede ser muy elevado<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a> y la única opción es la de construir categorías.</p>
<table>
<caption><span id="tab:unnamed-chunk-77">Tabla 1.12: </span>Ejemplo de recategorización de una variable continua</caption>
<thead>
<tr class="header">
<th align="center">Estatura (en metros)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">hasta 1.55</td>
</tr>
<tr class="even">
<td align="center">1.55 - 1.65</td>
</tr>
<tr class="odd">
<td align="center">1.65 - 1.75</td>
</tr>
<tr class="even">
<td align="center">1.75 - 1.85</td>
</tr>
<tr class="odd">
<td align="center">1.85 - 1.95</td>
</tr>
<tr class="even">
<td align="center">1.95 - 2.05</td>
</tr>
<tr class="odd">
<td align="center">más de 2.05</td>
</tr>
</tbody>
</table>
<p>En el próximo capítulo nos detendremos en las formas de construir estos agrupamientos y despejaremos las dudas que provengan de la diferente cantidad de valores que se agruparon en la variable discreta de este ejemplo (las dos primera categorías contienen dos valores cada una, y la tercera tres) y la aparente superposición entre el inicio de una categoría y el fin de la anterior en el caso de la continua, que sería una violación de la exclusión mutua, porque alguien con una talla de 1.85 podría ir tanto a la cuarta como a la quinta categoría.</p>
</div>
</div>
</div>
</div>
<div id="resumen-de-los-niveles-de-medición" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Resumen de los niveles de medición<a href="#resumen-de-los-niveles-de-medici%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Nivel de medición
</th>
<th style="text-align:left;">
Significado de los símbolos numéricos
</th>
<th style="text-align:left;">
Condición para cambio de escala
</th>
<th style="text-align:left;">
Ubicación del cero
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Nominal
</td>
<td style="text-align:left;">
Designan, distinguen
</td>
<td style="text-align:left;">
No repetir los números
</td>
<td style="text-align:left;">
Sin significado
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:left;">
Expresan orden
</td>
<td style="text-align:left;">
Respetar el orden ascendente o descendente
</td>
<td style="text-align:left;">
Sin signifcado
</td>
</tr>
<tr>
<td style="text-align:left;">
Intervalar
</td>
<td style="text-align:left;">
Proporcionalidad de distancias
</td>
<td style="text-align:left;">
<span class="math inline">\(y = b_0 + b_1*x\)</span>
</td>
<td style="text-align:left;">
Arbitrario
</td>
</tr>
<tr>
<td style="text-align:left;">
Proporcional
</td>
<td style="text-align:left;">
Proporcionalidad de valores
</td>
<td style="text-align:left;">
<span class="math inline">\(y = b_1*x\)</span>
</td>
<td style="text-align:left;">
Absoluto
</td>
</tr>
</tbody>
</table>
<p>Ejemplos de diferentes niveles de medición</p>
<ul>
<li>Nominales:</li>
</ul>
<p>Valores (supervivencia vs autoexpresión, tradicionales vs racionales) <span class="citation">R. F. Inglehart (<a href="#ref-inglehart2018">2018</a>)</span></p>
<ul>
<li>Ordinales:</li>
</ul>
<p>Las escalas de compromiso politico, acuerdo partidario y consistencia ideológica <span class="citation">Gerber et al. (<a href="#ref-gerber2016">2016</a>)</span>, la pobreza medida según Línea de pobreza <span class="citation">(<a href="#ref-Gomez2004">Gómez, Álvarez, and Mario Fernanda 2004</a>)</span>, el grado de acuerdo en escalas de actitud <span class="citation">(<a href="#ref-robinson1991">Robinson et al. 1991</a>)</span></p>
<ul>
<li>Cuantitativas discretas:</li>
</ul>
<p>Cantidad de partidos políticos, cantidad de palabras recordadas en una prueba de memoria, número de hijos e hijas</p>
<ul>
<li>Cuantitativas continuas:</li>
</ul>
<p>Tiempo requerido para completar una tarea, ingreso per cápita familiar, gasto total en campaña electoral <span class="citation">(<a href="#ref-moralesquiroga2010">Morales Quiroga and Pineiro Rodriguez 2010</a>)</span></p>
<div style="page-break-after: always;"></div>
</div>
<div id="hacerlo-en-r" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Hacerlo en R<a href="los-datos-estadísticos.html#hacerlo-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="lectura-de-la-base" class="section level3 hasAnchor" number="1.8.1">
<h3><span class="header-section-number">1.8.1</span> Lectura de la base<a href="los-datos-estadísticos.html#lectura-de-la-base" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para operar sobre un conjunto de datos es necesario contar con la matriz de datos cargada en la sesión de trabajo; debe ser un objeto disponible para usarlo. Para ello, se elige el nombre que se dará a ese objeto y se le asigna (con el signo <span class="math inline">\(&lt;-\)</span> o bien <span class="math inline">\(=\)</span>) la lectura de la base.
La lectura debe hacerse desde el lugar donde se encuentra el archivo. Si no se conoce su ruta, el comando <code>file.choose()</code> abre una ventana para llegar él. La respuesta de ese comando es la ruta completa que aparece en la consola de resultados.
La lectura de los archivos .txt se puede realizar con varios comandos, que dependen de que el archivo tenga o no encabezado, del separador que se use para delimitar los campos, del separador de decimales, etc. El comando read.table es el más genérico y debe indicársele:</p>
<ul>
<li>El nombre del archivo a leer junto con la ruta para llegar a él: que se copia de la consola.<br />
</li>
<li>Si el archivo tiene encabezado: este es el caso casi siempre, porque la primera fila de la matriz de datos tiene los nombres de las variables. Se indica: <span class="math inline">\(header=TRUE\)</span>.<br />
</li>
<li>El separador de campos: suelen ser comas, punto y comas, tabulaciones, espacio en blanco o pipe | (alt124 en windows). Si los campos están separados por comas, se indica <span class="math inline">\(sep=&quot;,&quot;\)</span> y así con los demás separadores, siempre entrecomillados.<br />
</li>
<li>Si a los casos perdidos se los ha codificado de algún modo particular, por ejemplo como 9999, debe indicarse <span class="math inline">\(na.strings=&quot;9999&quot;\)</span>.</li>
</ul>
<p>Conviene mirar la base original, desde el archivo .txt, que puede abrirse con bloc de notas, para asegurarse qué sepadores tiene.</p>
<p>A continuación se usarán datos de la matriz de datos que proviene de la aplicación del cuestionario que se mostró antes. La matriz (o base) de datos que tiene los datos cargados está en formato txt, tiene los campos separados por espacios en blanco y se llama base2019.txt. Para leer esa base, primero se ubica la ruta del archivo:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="los-datos-estadísticos.html#cb138-1" tabindex="-1"></a><span class="fu">file.choose</span>()</span></code></pre></div>
<p>Aquí se abre un explorador para llegar al archivo que se busca, cuando se lo selecciona, la respuesta es su ruta, que debe pegarse como argumento de <code>read.table</code>. Luego se pide su lectura, asignando el resultado al objeto base.ejemplo:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="los-datos-estadísticos.html#cb139-1" tabindex="-1"></a>base.ejemplo <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;bases/archivostxt/base2019.txt&quot;</span>,</span>
<span id="cb139-2"><a href="los-datos-estadísticos.html#cb139-2" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>, <span class="at">na.strings =</span> <span class="st">&quot;999&quot;</span></span>
<span id="cb139-3"><a href="los-datos-estadísticos.html#cb139-3" tabindex="-1"></a>)</span></code></pre></div>
<p>Además del nombre y la ruta del archivo, en este caso indicamos que la primera fila contiene los nombres de las variables y que los casos perdidos están codificados como 999.</p>
<p>En el panel superior derecho ha aparecido este primer objeto, del que se indica el tipo, su tamaño, y las cantidades de observaciones y de variables.<br />
El tipo de objeto se solicita:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="los-datos-estadísticos.html#cb140-1" tabindex="-1"></a><span class="fu">class</span>(base.ejemplo)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Es una matriz de datos, como se esperaba y se la puede ver pidiendo:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="los-datos-estadísticos.html#cb142-1" tabindex="-1"></a><span class="fu">View</span>(base.ejemplo)</span></code></pre></div>
<p>En esta exploración inicial, se pueden listar los nombres de las columnas (las variables):</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="los-datos-estadísticos.html#cb143-1" tabindex="-1"></a><span class="fu">names</span>(base.ejemplo)</span></code></pre></div>
<pre><code>##  [1] &quot;caso&quot;         &quot;grupo&quot;        &quot;cuestionario&quot; &quot;nombre&quot;       &quot;P1&quot;          
##  [6] &quot;P2&quot;           &quot;P3&quot;           &quot;P4&quot;           &quot;P5&quot;           &quot;P5.otra&quot;     
## [11] &quot;P6&quot;           &quot;P7&quot;           &quot;P7.otra&quot;      &quot;P8&quot;           &quot;P9&quot;          
## [16] &quot;P10&quot;          &quot;P11&quot;          &quot;P11.otra&quot;     &quot;P12&quot;          &quot;P13&quot;         
## [21] &quot;P14&quot;          &quot;P15&quot;          &quot;P16&quot;          &quot;comision&quot;</code></pre>
<p>Y pedir las primeras filas de la matriz. Para la presentación aquí y para que quede visible, elegimos solo las columnas de la quinta a la undécima; es lo que está indicado en el corchete que acompaña al nombre de la base. Cuando se aplica a una matriz de datos, ese corchete es para seleccionar algunas filas o algunas columnas y admite dos valores separados por una coma, el primero se refiere a la o las fila(s) y el segundo la o las columna(s). En este caso el primer elemento está en blanco, eso quiere decir que se usen todas las filas, el segundo elemento dice que se seleccionen solo las columnas de la 5 a la 11:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="los-datos-estadísticos.html#cb145-1" tabindex="-1"></a><span class="fu">head</span>(base.ejemplo[, <span class="dv">5</span><span class="sc">:</span><span class="dv">11</span>])</span></code></pre></div>
<pre><code>##   P1        P2 P3 P4 P5 P5.otra  P6
## 1  2  femenino 19  1  1    &lt;NA&gt; 120
## 2  1 masculino 29  1  2    &lt;NA&gt;  90
## 3  2  femenino 31  1  2    &lt;NA&gt;  30
## 4  2  femenino 28  1  8   gmail  30
## 5  2         f 22  1  1    &lt;NA&gt; 120
## 6  1         m 22  1  2    &lt;NA&gt; 240</code></pre>
<p>Si no se hubiera hecho la selección de esas columnas, por defecto se muestran las seis primera filas, en todas las columnas. Los <NA> son casos sin respuesta.<br />
Para tener más accesibles las variables, vamos a ponerle un nombre a cada columna:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="los-datos-estadísticos.html#cb147-1" tabindex="-1"></a><span class="fu">names</span>(base.ejemplo) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb147-2"><a href="los-datos-estadísticos.html#cb147-2" tabindex="-1"></a>  <span class="st">&quot;caso&quot;</span>, <span class="st">&quot;grupo&quot;</span>, <span class="st">&quot;n.cuest&quot;</span>, <span class="st">&quot;nombre&quot;</span>, <span class="st">&quot;sexo&quot;</span>, <span class="st">&quot;genero&quot;</span>,</span>
<span id="cb147-3"><a href="los-datos-estadísticos.html#cb147-3" tabindex="-1"></a>  <span class="st">&quot;edad&quot;</span>, <span class="st">&quot;acceso.redes&quot;</span>, <span class="st">&quot;red.usada&quot;</span>, <span class="st">&quot;red.otra&quot;</span>,</span>
<span id="cb147-4"><a href="los-datos-estadísticos.html#cb147-4" tabindex="-1"></a>  <span class="st">&quot;tiempo.red&quot;</span>, <span class="st">&quot;con.q.vive&quot;</span>, <span class="st">&quot;relacion.otros&quot;</span>,</span>
<span id="cb147-5"><a href="los-datos-estadísticos.html#cb147-5" tabindex="-1"></a>  <span class="st">&quot;q.aporta&quot;</span>, <span class="st">&quot;q.aporta.amigos&quot;</span>, <span class="st">&quot;edad.partida&quot;</span>,</span>
<span id="cb147-6"><a href="los-datos-estadísticos.html#cb147-6" tabindex="-1"></a>  <span class="st">&quot;razon.partida&quot;</span>,</span>
<span id="cb147-7"><a href="los-datos-estadísticos.html#cb147-7" tabindex="-1"></a>  <span class="st">&quot;razon.partida.otra&quot;</span>, <span class="st">&quot;calidad.sueño&quot;</span>,</span>
<span id="cb147-8"><a href="los-datos-estadísticos.html#cb147-8" tabindex="-1"></a>  <span class="st">&quot;preocupacion&quot;</span>, <span class="st">&quot;golpeo&quot;</span>, <span class="st">&quot;robo&quot;</span>, <span class="st">&quot;cuanto.da&quot;</span>, <span class="st">&quot;comision&quot;</span></span>
<span id="cb147-9"><a href="los-datos-estadísticos.html#cb147-9" tabindex="-1"></a>)</span></code></pre></div>
<p>De este modo se sobreescriben los nombres originales y quedan los nuevos. Si pedimos nuevamente los nombres, tenemos:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="los-datos-estadísticos.html#cb148-1" tabindex="-1"></a><span class="fu">names</span>(base.ejemplo)</span></code></pre></div>
<pre><code>##  [1] &quot;caso&quot;               &quot;grupo&quot;              &quot;n.cuest&quot;           
##  [4] &quot;nombre&quot;             &quot;sexo&quot;               &quot;genero&quot;            
##  [7] &quot;edad&quot;               &quot;acceso.redes&quot;       &quot;red.usada&quot;         
## [10] &quot;red.otra&quot;           &quot;tiempo.red&quot;         &quot;con.q.vive&quot;        
## [13] &quot;relacion.otros&quot;     &quot;q.aporta&quot;           &quot;q.aporta.amigos&quot;   
## [16] &quot;edad.partida&quot;       &quot;razon.partida&quot;      &quot;razon.partida.otra&quot;
## [19] &quot;calidad.sueño&quot;      &quot;preocupacion&quot;       &quot;golpeo&quot;            
## [22] &quot;robo&quot;               &quot;cuanto.da&quot;          &quot;comision&quot;</code></pre>
<p>Y puede verse la matriz por medio de:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="los-datos-estadísticos.html#cb150-1" tabindex="-1"></a><span class="fu">View</span>(base.ejemplo)</span></code></pre></div>
</div>
<div id="las-variables-1" class="section level3 hasAnchor" number="1.8.2">
<h3><span class="header-section-number">1.8.2</span> Las variables<a href="los-datos-estadísticos.html#las-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cada variable es una columna de la matriz, que ahora tienen los nombres que acabamos de darles. Para acceder a cada una y operar con ellas, se usa el signo “pesos” <span class="math inline">\(\$\)</span> luego del nombre de la matriz. Por ejemplo, la codificación numérica de la variable sexo (1 y 2 para varones y mujeres respectivamente), fue útil para la recolección y la carga de los datos, pero ahora necesitamos tratarla como lo que es. En efecto:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="los-datos-estadísticos.html#cb151-1" tabindex="-1"></a><span class="fu">class</span>(base.ejemplo<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>Esta almacenada como un número entero, pero es nominal, que en el lenguaje de R, se llama factor, y sus categorías, se llaman “niveles” (levels) o “niveles del factor” (factor levels). Para transformarla a ese tipo de variable hay dos opciones:</p>
<ul>
<li>Redefinir la variable sexo, cambiándola por una que en lugar de entera sea nominal, o bien</li>
<li>Crear una nueva variable en la matriz, a partir de sexo, con un nombre diferente.</li>
</ul>
<p>Elegimos la primera opción, es decir que operamos sobre la misma variable sexo, con lo que sobreescribimos la original. Primero la volvemos factor:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="los-datos-estadísticos.html#cb153-1" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>sexo)</span></code></pre></div>
<p>Si preguntamos por los niveles que tiene este factor, obtenemos:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="los-datos-estadísticos.html#cb154-1" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot;</code></pre>
<p>Mantiene los valores 1 y 2 pero entre comillas, lo que indica que no los trata como números sino como códigos de una variable nominal (categórica).<br />
Ahora le damos nombres a las categorías (los niveles del factor):</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="los-datos-estadísticos.html#cb156-1" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>sexo) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;varones&quot;</span>, <span class="st">&quot;mujeres&quot;</span>)</span></code></pre></div>
<p>Si se observa la matriz, aparecen ahora los nuevos nombres de las categorías.<br />
Repetimos estas operaciones sobre las otras preguntas del cuestionario:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="los-datos-estadísticos.html#cb157-1" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>con.q.vive <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>con.q.vive)</span>
<span id="cb157-2"><a href="los-datos-estadísticos.html#cb157-2" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>con.q.vive) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb157-3"><a href="los-datos-estadísticos.html#cb157-3" tabindex="-1"></a>  <span class="st">&quot;flia.origen&quot;</span>, <span class="st">&quot;flia.nueva&quot;</span>,</span>
<span id="cb157-4"><a href="los-datos-estadísticos.html#cb157-4" tabindex="-1"></a>  <span class="st">&quot;hermanes.o.amigues&quot;</span>, <span class="st">&quot;sole&quot;</span>,</span>
<span id="cb157-5"><a href="los-datos-estadísticos.html#cb157-5" tabindex="-1"></a>  <span class="st">&quot;con.otres&quot;</span></span>
<span id="cb157-6"><a href="los-datos-estadísticos.html#cb157-6" tabindex="-1"></a>)</span>
<span id="cb157-7"><a href="los-datos-estadísticos.html#cb157-7" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>q.aporta <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>q.aporta)</span>
<span id="cb157-8"><a href="los-datos-estadísticos.html#cb157-8" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>q.aporta) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb157-9"><a href="los-datos-estadísticos.html#cb157-9" tabindex="-1"></a>  <span class="st">&quot;el.mismo&quot;</span>, <span class="st">&quot;flia.origen&quot;</span>,</span>
<span id="cb157-10"><a href="los-datos-estadísticos.html#cb157-10" tabindex="-1"></a>  <span class="st">&quot;flia.nueva&quot;</span>, <span class="st">&quot;entre.amigos&quot;</span></span>
<span id="cb157-11"><a href="los-datos-estadísticos.html#cb157-11" tabindex="-1"></a>)</span>
<span id="cb157-12"><a href="los-datos-estadísticos.html#cb157-12" tabindex="-1"></a></span>
<span id="cb157-13"><a href="los-datos-estadísticos.html#cb157-13" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>acceso.redes <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>acceso.redes)</span>
<span id="cb157-14"><a href="los-datos-estadísticos.html#cb157-14" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>acceso.redes) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;si&quot;</span>, <span class="st">&quot;no&quot;</span>)</span>
<span id="cb157-15"><a href="los-datos-estadísticos.html#cb157-15" tabindex="-1"></a></span>
<span id="cb157-16"><a href="los-datos-estadísticos.html#cb157-16" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>red.usada <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>red.usada)</span>
<span id="cb157-17"><a href="los-datos-estadísticos.html#cb157-17" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>red.usada) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb157-18"><a href="los-datos-estadísticos.html#cb157-18" tabindex="-1"></a>  <span class="st">&quot;Instagram&quot;</span>, <span class="st">&quot;Facebook&quot;</span>, <span class="st">&quot;Twitter&quot;</span>,</span>
<span id="cb157-19"><a href="los-datos-estadísticos.html#cb157-19" tabindex="-1"></a>  <span class="st">&quot;Linkedin&quot;</span>, <span class="st">&quot;Tinder/Grindr/happn&quot;</span>,</span>
<span id="cb157-20"><a href="los-datos-estadísticos.html#cb157-20" tabindex="-1"></a>  <span class="st">&quot;Snapchat&quot;</span>, <span class="st">&quot;Ninguna&quot;</span>, <span class="st">&quot;Otra&quot;</span></span>
<span id="cb157-21"><a href="los-datos-estadísticos.html#cb157-21" tabindex="-1"></a>)</span>
<span id="cb157-22"><a href="los-datos-estadísticos.html#cb157-22" tabindex="-1"></a></span>
<span id="cb157-23"><a href="los-datos-estadísticos.html#cb157-23" tabindex="-1"></a>base.ejemplo<span class="sc">$</span>razon.partida <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(base.ejemplo<span class="sc">$</span>razon.partida)</span>
<span id="cb157-24"><a href="los-datos-estadísticos.html#cb157-24" tabindex="-1"></a><span class="fu">levels</span>(base.ejemplo<span class="sc">$</span>razon.partida) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb157-25"><a href="los-datos-estadísticos.html#cb157-25" tabindex="-1"></a>  <span class="st">&quot;estudio&quot;</span>, <span class="st">&quot;nueva.flia&quot;</span>, <span class="st">&quot;ganas&quot;</span>, <span class="st">&quot;otras&quot;</span></span>
<span id="cb157-26"><a href="los-datos-estadísticos.html#cb157-26" tabindex="-1"></a>)</span></code></pre></div>
<p>La cantidad de casos es el número de filas de la matriz de datos. En el caso de una variable, es decir de una columna, la cantidad de observaciones es la longitud del vector que la representa. Para conocer cuántos casos tiene una variable en particular, el comando es length:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="los-datos-estadísticos.html#cb158-1" tabindex="-1"></a><span class="fu">length</span>(base.ejemplo<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## [1] 5003</code></pre>
<p>Cuando se aplica a una matriz de datos, su longitud en el número de variables:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="los-datos-estadísticos.html#cb160-1" tabindex="-1"></a><span class="fu">length</span>(base.ejemplo)</span></code></pre></div>
<pre><code>## [1] 24</code></pre>
<p>Los elementos de la matriz de datos pueden accederse por filas o por columnas. Unos corchetes puestos a continuación del nombre identifican filas (casos), columnas (variables) o elementos (categorías). El corchete tiene como argumento dos números separados por una coma; el primero se refiere a la fila, el segundo a la columna, ambos juntos determinan un valor.</p>
<p>El valor que está en la fila 254, columna 7 de base.ejemplo es 30, que es la edad (columna 7) de la persona que está en la fila 254</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="los-datos-estadísticos.html#cb162-1" tabindex="-1"></a>base.ejemplo[<span class="dv">254</span>, <span class="dv">7</span>]</span></code></pre></div>
<pre><code>## [1] 30</code></pre>
<p>Si uno de los dos elementos del corchete se deja en blanco, toma todos los correspondientes de fila o de columna. No vamos a hacer el experimento, porque tendríamos, o bien los valores en cada una de las 24 variables de un sujeto, si pedimos una fila; o bien los 5003 valores de alguna variable, si pedimos una columna; pero es el recurso que se usó para seleccionar algunas columnas en la visualización de la matriz.</p>
</div>
<div id="los-niveles-de-medición-en-r" class="section level3 hasAnchor" number="1.8.3">
<h3><span class="header-section-number">1.8.3</span> Los niveles de medición en R<a href="#los-niveles-de-medici%C3%B3n-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Como se ha visto, en el lenguaje de R, el concepto de variable, se asimila a un vector. Es cada columna de la matriz de datos, compuesta por símbolos que pueden ser numéricos o no. En cuanto a sus tipos:</p>
<ul>
<li>Las que hemos llamado nominales son factores y sus categorías se llaman niveles.<br />
</li>
<li>Las ordinales, son factores ordenados.<br />
</li>
<li>Las cuantitativas (sin distinción entre intervalares y proporcionales) son:<br />
– numéricas las continuas y<br />
– enteras las discretas.</li>
</ul>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-gerber2016" class="csl-entry">
Gerber, Alan S., Gregory A. Huber, David Doherty, and Conor M. Dowling. 2016. <span>“Why People Vote: Estimating the Social Returns to Voting.”</span> <em>British Journal of Political Science</em> 46 (2): 241–64. <a href="https://doi.org/10.1017/S0007123414000271">https://doi.org/10.1017/S0007123414000271</a>.
</div>
<div id="ref-Gomez2004" class="csl-entry">
Gómez, Alicia, Gustavo Álvarez, and Silvia Mario Fernanda. 2004. <span>“<span class="nocase">El estudio de la pobreza seg<span class="nocase">ú</span>n el Censo Nacional de Poblaci<span class="nocase">ó</span>n, Hogares y Viviendas 2001 Metodolog<span class="nocase">í</span>a de elaboraci<span class="nocase">ó</span>n del <span>Í</span>ndice de Privaci<span class="nocase">ó</span>n Material de los Hogares (IPMH)</span>.”</span> <a href="https://www.indec.gob.ar/ftp/cuadros/sociedad/metodologia%7B\_%7Dipmh%7B\_%7D2016.pdf">https://www.indec.gob.ar/ftp/cuadros/sociedad/metodologia{\_}ipmh{\_}2016.pdf</a>.
</div>
<div id="ref-gaunt1662" class="csl-entry">
Graunt, John. 1662. <em><span class="nocase">Natural and Political Observations Mentioned in the following INDEX and made upon the Bills of Mortality</span></em>. Edited by Royal Society. London: John Martin.
</div>
<div id="ref-inglehart2018" class="csl-entry">
Inglehart, Ronald F. 2018. <em>Cultural Evolution: People’s Motivations Are Changing, and Reshaping the World</em>. Cambridge University Press. <a href="https://doi.org/10.1017/9781108613880">https://doi.org/10.1017/9781108613880</a>.
</div>
<div id="ref-moralesquiroga2010" class="csl-entry">
Morales Quiroga, Mauricio, and Rafael Pineiro Rodriguez. 2010. <span>“<span class="nocase">Gasto en campana y exito electoral de los candidatos a diputados en chile 2005</span>.”</span> <em><span>Revista de Ciencia Politica (Santiago)</span></em> 30: 645–67. <a href="https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0718-090X2010000300004&amp;nrm=iso">https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0718-090X2010000300004&amp;nrm=iso</a>.
</div>
<div id="ref-robinson1991" class="csl-entry">
Robinson, John P., Phillip R. Shaver, Lawrence S. Wrightsman, and Frank M. Andrews. 1991. <em><span class="nocase">Measures of personality and social psychological attitudes</span></em>. Academic Press.
</div>
<div id="ref-Stevens1946" class="csl-entry">
Stevens, Stanley. 1946. <span>“<span class="nocase">On the Theory of Scales of Measurement</span>.”</span> <em>Science, New Series</em> 103 (2684): 677–80. <a href="http://www.jstor.org/stable/1671815">http://www.jstor.org/stable/1671815</a>.
</div>
<div id="ref-Upton2013" class="csl-entry">
Upton, Jane. 2013. <span>“Beck Depression Inventory (BDI).”</span> In <em>Encyclopedia of Behavioral Medicine</em>, edited by Marc D. Gellman and J. Rick Turner, 178–79. New York, NY: Springer New York. <a href="https://doi.org/10.1007/978-1-4419-1005-9_441">https://doi.org/10.1007/978-1-4419-1005-9_441</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>La palabra observar aquí se utiliza en un sentido general, puede tratarse de una observación directa como la que se realiza al mirar (o filmar) un comportamiento, o bien de la presentación de preguntas que alguien debe responder.<a href="los-datos-estadísticos.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>A quien se llama “Jefe o jefa de Hogar”.<a href="los-datos-estadísticos.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>A menudo que, en Estadística, es necesario llegar a puntos de equilibrio entre el grado de detalle de la información que se ofrece y la claridad con que esa información puede presentarse.<a href="los-datos-estadísticos.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>Si bien la corrección que se introduce cada año no es idéntica, por lo que el momento de cambio de año no es el mismo en las dos escalas.<a href="los-datos-estadísticos.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>Con la salvedad indicada antes sobre la no coincidencia del momento de cambio de año.<a href="los-datos-estadísticos.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Este nivel de medición aparece mencionado en alguna bibliografía como “escalas de razón” se pueden tratar como sinónimos, ya que la razón se refiere al cociente de números, que permanece constante en el caso de valores proporcionales.<a href="los-datos-estadísticos.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>El ejemplo de los calendarios judío y cristiano, aunque es una medición de tiempo, no es absoluta. Es diferente de la medición con un cronómetro, que establece un inicio de cuenta al momento en que se lo dispara y da lugar a una variable de nivel proporcional.<a href="los-datos-estadísticos.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>La cantidad de valores depende de la precisión con que se mida. Si se mide con precisión de un centímetro, en un metro caben 100 valores, pero si se mide al milímetro en el mismo intervalo de un metro se ubican 1000 categorías. Una aproximación al concepto de continuidad es que entre dos valores hay infinitos cortes, sin embargo, en procesos observables, la medición tiene un límite que está dado por la mínima graduación que admita el instrumento. Esta es la concepción habitual de variables continuas en estadística, que las distingue de las discretas en que estas provienen de procesos de conteo, mientras que las primeras se generan a partir de mediciones, en alguna unidad de medida. Sin embargo, esta idea no se corresponde con la definición matemática de continuidad, sino con la de “densidad”. El conjunto de números racionales es denso, porque entre dos cualesquiera de ellos pueden encontrarse otro (<span class="math inline">\(\forall a\: \in \: \mathbb{Q},\: \forall b \in \: \mathbb{Q},\:\: / \: a\: &lt;\: b,\:  \exists \: c\in \: \mathbb{Q},\:\: /\: a\: &lt;\: c\: &lt;b\)</span>). Pero este conjunto no es completo, debido a tiene discontinuidades en los números irracionales. En este curso, en los problemas prácticos que enfrentamos, las variables cuantitativas podrán tomar valores enteros o decimales y mantendremos la convención de llamar discretas a las primeras y continuas a las segundas.<a href="los-datos-estadísticos.html#fnref8" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="antes-de-empezar.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="distribuciones-de-frecuencia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jcrodriguez1989/EstadisticaParaCienciasSocialesConR/edit/master/02-capitulo1.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["EstadisticaParaCienciasSocialesConR.pdf", "EstadisticaParaCienciasSocialesConR.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
